CHANGELOG.md, phpstan-baseline.neon, phpstan.neon
=> [TASK] Raise PHPStan to level 9

README.md
=> [TASK] Drop the V9 badge from the README

CHANGELOG.md, composer.json
=> [TASK] Drop support for Emogrifier 4 and 5

CHANGELOG.md, Tests/Functional/Localization/TranslateTraitTest.php, Tests/Functional/Traits/LanguageHelper.php, Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/Unit/Traits/EmailTraitTest.php
=> [TASK] Drop 9LTS-only code from the tests

CHANGELOG.md, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [BUGFIX] Stop using the deprecated `Web\Response` class

.github/dependabot.yml, composer.json
=> [TASK] Update `ergebnis/composer-normalize`

.github/dependabot.yml, composer.json
=> [TASK] Update `phpstan/extension-installer`

CHANGELOG.md, Classes/Csv/AbstractListView.php, Configuration/TCA/Overrides/tt_content.php, ext_localconf.php, ext_tables.php
=> [TASK] Drop 9LTS-only production code

Documentation/EN/Index.rst, README.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> [TASK] Remove the crowdfunding campaign ads

CHANGELOG.md, composer.json, ext_emconf.php
=> [TASK] Drop obsolete package conflicts

composer.json
=> [TASK] Drop the `typo3/class-alias-loader` dev dependency

.github/dependabot.yml, composer.json, phpstan-baseline.neon
=> [TASK] Upgrade `saschaegerer/phpstan-typo3 `

CHANGELOG.md, Configuration/TCA/tx_seminars_seminars.php
=> [TASK] Stop allowing single events as topics for date records

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_categories.php, Configuration/TCA/tx_seminars_checkboxes.php, Configuration/TCA/tx_seminars_event_types.php, Configuration/TCA/tx_seminars_foods.php, Configuration/TCA/tx_seminars_lodgings.php, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_payment_methods.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_skills.php, Configuration/TCA/tx_seminars_speakers.php, Configuration/TCA/tx_seminars_target_groups.php, Configuration/TCA/tx_seminars_timeslots.php
=> [TASK] Drop the deprecated `showRecordFieldList` from the TCA

CHANGELOG.md, ext_tables.sql
=> [TASK] Shrink some DB fields to save some space

Classes/FrontEnd/RegistrationForm.php, Configuration/TypoScript/Forms/RegistrationStep1.typoscript, Tests/Functional/FrontEnd/EventEditorTest.php, Tests/Functional/FrontEnd/RegistrationFormTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php, phpstan-baseline.neon
Also add some missing `@covers` annotations.
Fixes #2192
=> [TASK] Drop storing default registration form data in the session

CHANGELOG.md, Classes/FrontEnd/EventEditor.php, Classes/Mapper/CheckboxMapper.php, Classes/Mapper/PlaceMapper.php, Classes/Mapper/SpeakerMapper.php, Classes/Mapper/TargetGroupMapper.php, Classes/Model/Checkbox.php, Classes/Model/Place.php, Classes/Model/Speaker.php, Classes/Model/TargetGroup.php, Classes/OldModel/LegacySpeaker.php, Configuration/TCA/tx_seminars_checkboxes.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_speakers.php, Configuration/TCA/tx_seminars_target_groups.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/Mapper/CheckboxMapperTest.php, Tests/LegacyUnit/Mapper/PlaceMapperTest.php, Tests/LegacyUnit/Mapper/SpeakerMapperTest.php, Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php, Tests/Unit/OldModel/LegacySpeakerTest.php, ext_tables.sql, phpstan-baseline.neon
=> [TASK] Drop the owner concept for auxiliary records

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Tests/Functional/FrontEnd/Fixtures/TestingDefaultController.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
=> [TASK] Remove the "duplicate event" functionality from the FE editor

CHANGELOG.md, Classes/Configuration/ListViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Templates/FrontEnd/FrontEnd.html, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, phpstan-baseline.neon
=> [TASK] Drop the status column from the "my VIP events" list

CHANGELOG.md, Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [TASK] Drop the JavaScript of the legacy registration form

CHANGELOG.md, Classes/Domain/Model/Event/EventStatistics.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
=> [BUGFIX] Fix crash saving an event in the FE editor

CHANGELOG.md, Resources/Private/CSS/thankYouMail.css
=> [FEATURE] Use SimpleCSS for the email CSS

CHANGELOG.md, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [BUGFIX] Stop testing for the exact email markup

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/OldModel/LegacyEvent.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Tests/Functional/OldModel/LegacyEventTest.php, Tests/LegacyUnit/OldModel/LegacyEventTest.php, phpstan-baseline.neon
Also drop the `showTimeOf*` configuration options.
Fixes #1789
=> [TASK] Always show the time of deadlines and of the registration start

CHANGELOG.md, Classes/Configuration/LegacyConfiguration.php, Classes/Service/RegistrationProcessor.php, Tests/Unit/Configuration/LegacyConfigurationTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
This configuration is not registration-specific anymore.
=> [TASK] Rename `LegacyRegistrationConfiguration` to `LegacyConfiguration`

Tests/Functional/Configuration/RegistrationListConfigurationCheckTest.php
=> [TASK] Add missing `@covers` annotation

CHANGELOG.md, Classes/Email/Salutation.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [TASK] Drop the automatic gender-specific salutations

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacySpeaker.php, Configuration/TCA/tx_seminars_speakers.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Language/ru.locallang_db.xlf, Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/Unit/OldModel/LegacySpeakerTest.php, ext_tables.sql, phpstan-baseline.neon
=> [TASK] Drop the gender field for speakers

CHANGELOG.md, Documentation/Installation/InstallingTheExtension/Index.rst, Documentation/Installation/Upgrading.rst, Documentation/KnownProblems/Index.rst
Fixes #1664
Fixes #1733
Fixes #1804
Fixes #2099
[ci skip]
=> [TASK] Improve the upgrade notes

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, ext_conf_template.txt, phpstan-baseline.neon
=> [TASK] Always send HTML and plain text emails

Classes/Domain/Model/EventTypeInterface.php
=> [TASK] Use native return types in `EventTypeInterface`

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf
=> [TASK] Drop obsolete file upload messages

Classes/Service/RegistrationManager.php
=> [TASK] Drop the unused `RegistrationManager::getRegistrationMapper`

CHANGELOG.md, Classes/Mapper/RegistrationMapper.php, Configuration/TCA/tx_seminars_attendances.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang_db.xlf, ext_tables.sql
These fields were never used.
Fixes #1990
=> [TASK] Drop currency and tax information from registrations

Tests/LegacyUnit/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [TASK] Drop an unused method from a test

ext_localconf.php
=> [TASK] Drop the `saveDocNew` stuff from `ext_localconf.php`

CHANGELOG.md, Classes/Configuration/SingleViewConfigurationCheck.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
This setting did not have any affect for quite some time now.
Fixes #2233
=> [TASK] Drop the `externalLinkTarget` setting

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/OldModel/LegacyEvent.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
=> [TASK] Remove the `showToBeAnnouncedForEmptyPrice` setting

CHANGELOG.md, Classes/Model/Event.php, Tests/LegacyUnit/Model/EventTest.php, phpstan-baseline.neon
=> [TASK] Drop the `Event::STATUS_*` constants

CHANGELOG.md, Classes/UpgradeWizards/SeparateBillingAddressUpgradeWizard.php, Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithMarkedBillingAddress.xml, Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithUnmarkedBillingAddressCity.xml, Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithoutBillingAddress.xml, Tests/Functional/UpgradeWizards/SeparateBillingAddressUpgradeWizardTest.php, Tests/Unit/UpgradeWizards/SeparateBillingAddressUpgradeWizardTest.php, composer.json, ext_localconf.php, phpstan-baseline.neon
=> [FEATURE] Add an upgrade wizard for the separate billing address

.github/workflows/ci.yml, CHANGELOG.md, Classes/Bag/AbstractBag.php, Tests/LegacyUnit/Bag/AbstractBagTest.php, Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/CategoryBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php, Tests/Unit/Controller/Fixtures/TestingQueryResult.php
Also fix some PHP 8.1 warnings.
Fixes #1790
=> [TASK] Switch the code quality checks to PHP 8.1

CHANGELOG.md, Classes/FrontEnd/SelectorWidget.php, phpstan-baseline.neon
=> [BUGFIX] Fix array access warnings in `SelectorWidget` in PHP 8.1

CHANGELOG.md, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/LegacyTimeSlot.php, Classes/Service/RegistrationManager.php, phpstan-baseline.neon
=> [BUGFIX] Stop using the deprecated `strftime` in some places

CHANGELOG.md, Classes/Service/DateFormatConverter.php, Tests/Unit/Service/DateFormatConverterTest.php
=> [FEATURE] Add a date format converter

CHANGELOG.md, Classes/Configuration/Traits/SharedPluginConfiguration.php, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/OldModel/LegacyTimeSlot.php, Classes/Service/RegistrationManager.php, Classes/ViewHelpers/DateRangeViewHelper.php, phpstan-baseline.neon
=> [BUGFIX] Replace usages of `strftime` in the production code

.github/workflows/ci.yml
=> [TASK] Switch the legacy test back to Composer >= 2.5

CHANGELOG.md
=> [TASK] Add changelog entry

CHANGELOG.md, Classes/Email/Salutation.php, Classes/FrontEnd/DefaultController.php, Classes/Model/Registration.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacySpeaker.php, Configuration/TCA/tx_seminars_attendances.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Functional/OldModel/LegacyRegistrationTest.php, Tests/LegacyUnit/Model/RegistrationTest.php
=> [FEATURE] Add a "diverse" gender

Documentation/Index.rst, Documentation/Settings.yml
=> [TASK] Change copyright year

CHANGELOG.md, Documentation/Index.rst, README.md
=> [TASK] Remove the links to the feature survey

CHANGELOG.md, Documentation/Introduction/Index.rst, README.md
=> [TASK] Mention the 12LTS crowdfunding campaign

Classes/Controller/EventRegistrationController.php, Tests/Unit/Controller/EventRegistrationControllerTest.php
Also improve some test names.
Part of #1972
=> [TASK] Move the maximum bookable seats default to a constant

CHANGELOG.md
=> [TASK] Clean up the changelog formatting a bit

Tests/Unit/Controller/EventRegistrationControllerTest.php
=> [BUGFIX] Fix a nonsensical test name

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Classes/Service/RegistrationProcessor.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Partials/EventRegistration/Headline.html, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Private/Templates/EventRegistration/ThankYou.html, Tests/Unit/Controller/EventRegistrationControllerTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
=> [FEATURE] Add a waiting list functionality to the new registration form

Classes/Service/RegistrationManager.php
=> [CLEANUP] Improve some method comments

composer.json
=> [BUGFIX] Also drop `.idea` and `.git` for the releases

Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/LegacyUnit/OldModel/LegacyOrganizerTest.php
=> [TASK] Stop using the `test.com` domain in the tests

CHANGELOG.md, Classes/BagBuilder/EventBagBuilder.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Classes/Mapper/EventMapper.php, Classes/OldModel/LegacyEvent.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [BUGFIX] Use `Connection` instead of `PDO` for the named param types

CHANGELOG.md, Tests/Unit/Traits/MakeInstanceTrait.php, Tests/Unit/Traits/MakeInstanceTraitTest.php
=> [TASK] Improve the type declarations of `MakeInstanceTrait`

CHANGELOG.md
=> [TASK] Improve the changelog

CHANGELOG.md, Classes/BackEnd/Permissions.php, Classes/Service/EventStatisticsCalculator.php, Tests/Unit/BackEnd/PermissionsTest.php, Tests/Unit/Service/EventStatisticsCalculatorTest.php
=> [BUGFIX] Convert most classes that get injected into singletons

CHANGELOG.md, Resources/Private/Templates/EventRegistration/New.html
=> [BUGFIX] Apply the "register myself" default even if hidden

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/ThankYou.html
=> [TASK] Show a different thank-you text for waiting list registrations

CHANGELOG.md, Resources/Private/Partials/EventDate.html
=> [BUGFIX] Do not display single-day events as multi-day events

CHANGELOG.md, Documentation/Configuration/Index.rst, Documentation/Configuration/Routing.rst
=> [TASK] Document how to set up nice registration URLs

Classes/UpgradeWizards/SeparateBillingAddressUpgradeWizard.php
=> [TASK] Deprecate the upgrade wizard

CHANGELOG.md, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Configuration/TCA/tx_seminars_seminars.php, Documentation/Configuration/Routing.rst, Documentation/Installation/Upgrading.rst, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Functional/Seo/Fixtures/EventDateWithDeletedTopic.xml, Tests/Functional/Seo/Fixtures/EventDateWithTopic.xml, Tests/Functional/Seo/Fixtures/EventDateWithTopicWithoutTitle.xml, Tests/Functional/Seo/Fixtures/EventDateWithoutTopic.xml, Tests/Functional/Seo/SlugGeneratorTest.php, Tests/Functional/UpgradeWizards/Fixtures/EventWithSlug.xml, Tests/Functional/UpgradeWizards/Fixtures/EventsWithAndWithoutSlug.xml, Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php, Tests/Unit/Seo/SlugGeneratorTest.php, Tests/Unit/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php, ext_localconf.php, ext_tables.sql, phpstan-baseline.neon
=> [FEATURE] Implement nice single view URLs

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/Seo/SingleViewPageTitleProvider.php, Documentation/Configuration/Index.rst, Documentation/Configuration/SEO.rst, Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php, Tests/Unit/Seo/SingleViewPageTitleProviderTest.php, phpstan-baseline.neon
Also drop an unused variable.
Fixes #2517
=> [FEATURE] Add nice page titles in the single view

CHANGELOG.md, Resources/Private/CSS/thankYouMail.css
=> [TASK] Update the email CSS to simple.css v2.2.1

Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Tests/Functional/UpgradeWizards/Fixtures/DeletedEventWithNullSlug.xml, Tests/Functional/UpgradeWizards/Fixtures/HiddenEventWithNullSlug.xml, Tests/Functional/UpgradeWizards/Fixtures/TimedEventWithNullSlug.xml, Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php
=> [BUGFIX] Also update slug for non-visible events in the upgrade wizard

CHANGELOG.md, Classes/Seo/SlugGenerator.php, Configuration/TCA/tx_seminars_seminars.php, Tests/Functional/Seo/SlugGeneratorTest.php
=> [BUGFIX] Fix the slug generation for event date records

CHANGELOG.md, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Tests/Functional/UpgradeWizards/Fixtures/SlugCollisionWithExistingSlug.xml, Tests/Functional/UpgradeWizards/Fixtures/SlugCollisionWithNewlyCreatedSlug.xml, Tests/Functional/UpgradeWizards/Fixtures/SlugCollisionWithSuffixedSlug.xml, Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php, phpstan-baseline.neon
=> [BUGFIX] Ensure the upgrade wizard generates unique slugs

CHANGELOG.md, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Tests/Functional/Seo/Fixtures/SingleEventWithSlug.xml, Tests/Functional/Seo/Fixtures/TwoSingleEventsWithSlug.xml, Tests/Functional/Seo/SlugGeneratorTest.php, phpstan-baseline.neon
This will allow us to reuse the slug generation in the `DataHandler` if we need it as well.
=> [TASK] Move the uniqueness promise to `SlugGenerator`

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Hooks/Fixtures/DataMapperHook.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/EventDateWithSlug.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/EventDateWithoutSlug.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/SingleEventWithSlug.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/SingleEventWithoutSlug.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/TopicWithSlug.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/TopicWithoutSlug.xml
=> [BUGFIX] Also set/update the slug if the slug field is not shown

Documentation/UsersManual/ManagingRegistrations/Index.rst
=> [TASK] Rework the documentation for the CSV export

CHANGELOG.md, ext_localconf.php
=> [TASK] Always provide the canonical URL for the single view

CHANGELOG.md, Documentation/Configuration/SEO.rst
=> [TASK] Document how to set up robots configuration for single view pages

Documentation/Configuration/SEO.rst, Documentation/Reference/Hooks/Index.rst
=> [CLEANUP] Fix the indentation of code blocks in the documentation

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/Seo/Event/AfterSlugGeneratedEvent.php, Classes/Seo/SlugContext.php, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Documentation/Configuration/SEO.rst, Tests/Functional/Seo/SlugGeneratorTest.php, Tests/Unit/Seo/Event/AfterSlugGeneratedEventTest.php, Tests/Unit/Seo/Fixtures/TestingSlugEventDispatcher.php, Tests/Unit/Seo/SlugContextTest.php, Tests/Unit/Seo/SlugGeneratorTest.php, composer.json
=> [FEATURE] Add a PSR-14 event for creating/modifying event slugs

CHANGELOG.md, Classes/Seo/SlugContext.php, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, phpstan-baseline.neon
Also add a few `assert`s to ensure some integer ranges.
Fixes #2618
=> [TASK] Improve the code documentation concerning slug generation

Documentation/Introduction/LiveExamples.rst
=> [TASK] Update the list of live examples in the manual

CHANGELOG.md, Resources/Private/Templates/BackEnd/Event/Index.html, Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
=> [TASK] Move the CSV export buttons in the BE module next to the headings

Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/ModuleController.php, Classes/Controller/BackEnd/PageUidTrait.php, Resources/Private/Templates/BackEnd/Module/Overview.html, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, ext_tables.php, phpstan-baseline.neon
=> [TASK] Restructure the BE module controllers

CHANGELOG.md, Classes/Controller/BackEnd/ModuleController.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/BackEnd/Module/Overview.html, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, phpstan-baseline.neon
=> [FEATURE] Show registration statistics in the BE module

Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/CsvDownloader.php, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/Functional/Csv/Fixtures/EventsAndRegistrations.xml, phpstan-baseline.neon
=> [FEATURE] Allow CSV-exporting registrations by page UID

CHANGELOG.md, Classes/Controller/BackEnd/RegistrationController.php, Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/CsvDownloader.php, Resources/Private/Templates/BackEnd/Module/Overview.html, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/LegacyUnit/Csv/CsvDownloaderTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, ext_tables.php, phpstan-baseline.neon
=> [FEATURE] Allow CSV export of all registrations in a folder

CHANGELOG.md, Resources/Private/Templates/BackEnd/Module/Overview.html
=> [BUGFIX] Only show the CSV export button if there are any records

Classes/Domain/Model/Event/EventTrait.php, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php
This is a pre-patch for #2653.
=> [FEATURE] Add `Event.hidden` and `EventRepository.findOneByUidForBackend`

Classes/Controller/BackEnd/RegistrationController.php
=> [TASK] Make a type annotation more specific

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html
=> [TASK] Allow showing and exporting registrations for hidden events

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html
=> [BUGFIX] Allow listing waiting-list-only registrations in the BE module

CHANGELOG.md, Documentation/Settings.yml, ext_emconf.php
=> V5.5.1: Bug fixes

.github/workflows/ci.yml, composer.json
=> [TASK] Re-enable some unit tests on CI

CHANGELOG.md, composer.json
=> [TASK] Drop the `nimut/testing-framework` dependency

README.md
=> [TASK] Autoformat the README

.github/workflows/ci.yml
=> [BUGFIX] Fix a label on CI

Tests/LegacyFunctional/Mapper/CategoryMapperTest.php, Tests/LegacyFunctional/Mapper/CheckboxMapperTest.php, Tests/LegacyFunctional/Mapper/EventMapperTest.php, Tests/LegacyFunctional/Mapper/EventTopicMapperTest.php, Tests/LegacyFunctional/Mapper/EventTypeMapperTest.php, Tests/LegacyFunctional/Mapper/FoodMapperTest.php, Tests/LegacyFunctional/Mapper/LodgingMapperTest.php, Tests/LegacyFunctional/Mapper/OrganizerMapperTest.php, Tests/LegacyFunctional/Mapper/PaymentMethodMapperTest.php, Tests/LegacyFunctional/Mapper/PlaceMapperTest.php, Tests/LegacyFunctional/Mapper/RegistrationMapperTest.php, Tests/LegacyFunctional/Mapper/SingleEventMapperTest.php, Tests/LegacyFunctional/Mapper/SkillMapperTest.php, Tests/LegacyFunctional/Mapper/SpeakerMapperTest.php, Tests/LegacyFunctional/Mapper/TargetGroupMapperTest.php, Tests/LegacyFunctional/Mapper/TimeSlotMapperTest.php, Tests/LegacyFunctional/Model/EventDateTest.php, Tests/LegacyFunctional/Model/FoodTest.php, Tests/LegacyFunctional/Model/FrontEndUserTest.php, Tests/LegacyFunctional/Model/LodgingTest.php, Tests/LegacyFunctional/Model/OrganizerTest.php, Tests/LegacyFunctional/Model/PaymentMethodTest.php, Tests/LegacyFunctional/Model/RegistrationTest.php, Tests/LegacyFunctional/Model/SingleEventTest.php, Tests/LegacyFunctional/Model/SpeakerTest.php, Tests/LegacyFunctional/Model/TargetGroupTest.php, Tests/LegacyFunctional/Model/TimeSlotTest.php
=> [BUGFIX] Fix incorrect namespace in tests

CHANGELOG.md, Configuration/TCA/Overrides/tt_content.php
=> [TASK] Drop obsolete option from the plugin registration

Resources/Private/Partials/BackEnd/EventList.html
=> [CLEANUP] Autoformat a Fluid partial

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html
=> [TASK] Drop the additional icon placeholders from the BE module

CHANGELOG.md, Resources/Private/Partials/BackEnd/RegistrationList.html
=> [FEATURE] Add a button for (un)hiding registrations in the BE module

CHANGELOG.md, Classes/Service/RegistrationManager.php, phpstan-baseline.neon
Also fix the casing of a private method as a drive-by change.
Part of #2810
=> [TASK] Reduce usage of `AbstractPlugin->cObj` in `RegistrationManager`

Tests/Unit/Service/PriceFinderTest.php, Tests/Unit/Service/RegistrationGuardTest.php
=> [TASK] Fix a typo in some comments

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_categories.php, Configuration/TCA/tx_seminars_checkboxes.php, Configuration/TCA/tx_seminars_event_types.php, Configuration/TCA/tx_seminars_foods.php, Configuration/TCA/tx_seminars_lodgings.php, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_payment_methods.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_skills.php, Configuration/TCA/tx_seminars_speakers.php, Configuration/TCA/tx_seminars_target_groups.php, Configuration/TCA/tx_seminars_test.php, Configuration/TCA/tx_seminars_timeslots.php, Tests/LegacyFunctional/OldModel/AbstractModelTest.php
=> [BUGFIX] Avoid the deprecated `cruser_id`

CHANGELOG.md, Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/Fixtures/BackEndUser.csv, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/Functional/Csv/Fixtures/BackEndUser.csv, Tests/Functional/SchedulerTasks/Fixtures/BackEndUser.csv, Tests/Functional/SchedulerTasks/MailNotifierConfigurationTest.php, Tests/Functional/ViewHelpers/Fixtures/BackEndUser.csv, Tests/Functional/ViewHelpers/Fixtures/BackEndUser.xml, Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php
Also drop an unused fixture file.
Fixes #2820
=> [BUGFIX] Replace deprecated `setUpBackendUserFromFixture` calls in tests

CHANGELOG.md, Classes/Templating/TemplateHelper.php
Also drop unused properties from `TemplateHelper`.
=> [TASK] Drop nonsensical deprecation marks

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [TASK] Make the `TemplateHelper` abstract

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/AbstractModel.php, Classes/Templating/TemplateHelper.php
=> [TASK] Avoid calling `AbstractPlugin::pi_RTEcssText`

CHANGELOG.md, Classes/Controller/BackEnd/EmailController.php, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Tests/LegacyFunctional/Csv/CsvDownloaderTest.php, Tests/Support/BackEndTestsTrait.php, Tests/Unit/Controller/BackEnd/EmailControllerTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, phpstan-baseline.neon
=> [CLEANUP] Access superglobals directly

.github/workflows/ci.yml, composer.json
=> [TASK] Prevent generation of `composer.lock`

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Language/ru.locallang_db.xlf
=> [BUGFIX] Add `resname` to all language labels

Tests/Functional/BackEnd/Fixtures/TestingEventMailForm.php, Tests/Functional/BagBuilder/Fixtures/TestingBagBuilder.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/FrontEnd/Fixtures/TestingDefaultController.php
=> [CLEANUP] Drop dead code in tests

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BagBuilder/EventBagBuilder.php, Classes/Controller/BackEnd/EmailController.php, Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/Service/EmailService.php, Classes/Service/RegistrationManager.php, Classes/Templating/TemplateHelper.php, Resources/Private/Templates/BackEnd/Email/Compose.html, Tests/Unit/Controller/BackEnd/EmailControllerTest.php, phpstan-baseline.neon
=> [TASK] Drop dead code

Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [CLEANUP] Drop the last traces of jQuery

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/FlexForms.php, Classes/BackEnd/GeneralEventMailForm.php, Classes/BackEnd/TceForms.php, Classes/Bag/AbstractBag.php, Classes/BagBuilder/AbstractBagBuilder.php, Classes/Configuration/AbstractFrontEndConfigurationCheck.php, Classes/Configuration/CategoryListConfigurationCheck.php, Classes/Configuration/CsvExportConfigurationCheck.php, Classes/Configuration/EventRegistrationFlexForms.php, Classes/Configuration/ListViewConfigurationCheck.php, Classes/Configuration/MyVipEventsConfigurationCheck.php, Classes/Configuration/RegistrationListConfigurationCheck.php, Classes/Configuration/SharedConfigurationCheck.php, Classes/Configuration/SingleViewConfigurationCheck.php, Classes/Configuration/Traits/SharedPluginConfiguration.php, Classes/Csv/AbstractListView.php, Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/CsvDownloader.php, Classes/Csv/CsvResponse.php, Classes/Email/EmailBuilder.php, Classes/FrontEnd/AbstractView.php, Classes/Localization/TranslateTrait.php, Classes/OldModel/AbstractModel.php, Classes/Rendering/NullRenderingContext.php, Classes/Rendering/NullRequest.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Classes/ViewHelpers/DateRangeViewHelper.php
=> [TASK] Mark some classes as `@internal`

Classes/Middleware/ResponseHeadersModifier.php, Configuration/RequestMiddlewares.php, Tests/Functional/Middleware/ResponseHeadersModifierTest.php, Tests/Unit/Middleware/ResponseHeadersModifierTest.php
=> [FEATURE] Add a middleware for modifying/adding HTTP headers

.github/dependabot.yml
=> [BUGFIX] Fix the Dependabot milestone

Classes/Csv/CsvDownloader.php, Tests/Functional/Csv/CsvDownloaderTest.php
=> [BUGFIX] Stop using the deprecated HTTP functions in `CsvDownloader`

Classes/FrontEnd/RegistrationForm.php, Classes/Service/RegistrationManager.php, composer.json
=> [FEATURE] Add logging for the (un)registration process

.github/workflows/automerge.yml, .github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/release.yml
=> [TASK] Switch the Ubuntu CI runners to 24.04

CHANGELOG.md, Classes/Rendering/NullRenderingContext.php, Tests/Unit/Rendering/NullRenderingContextTest.php
=> [BUGFIX] Avoid crash with Fluid 2.12.0 due to signature change

Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/OldModel/AbstractModelTest.php, Tests/Functional/OldModel/LegacyEventTest.php, Tests/Functional/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [TASK] Use only core DB access methods in the functional tests

Documentation/Index.rst, Documentation/Settings.yml
=> [TASK] Bump the copyright year to 2024

Tests/Functional/BackEnd/AbstractEventMailFormTest.php, phpstan-baseline.neon
This reverts commit b0262f10cf05ee988bf7d96d05ec91865ba85d8c.
=> [TASK] Re-add some tests that now pass

CHANGELOG.md, Configuration/TCA/tx_seminars_seminars.php
5 files is not enough for some real-world use cases a customer of mine has.
=> [TASK] Allow up to 50 attached files per event

phpstan-baseline.neon, phpstan.neon
=> [TASK] Stop using a deprecated PHPStan option

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/DeletedSingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/HiddenSingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/NoEvents.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventOnPage.csv
=> [FEATURE] Add repository method for hiding events

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/DeletedHiddenSingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/NoEvents.csv
=> [FEATURE] Add repository method for unhiding events

Classes/Controller/BackEnd/EventController.php, Resources/Private/Partials/BackEnd/EventList.html, Tests/Unit/Controller/BackEnd/EventControllerTest.php, ext_tables.php
=> [FEATURE] Use real buttons for (un)hiding events in the BE module

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php
=> [FEATURE] Add an additional permissions check for (un)hiding events

CHANGELOG.md
=> [DOCS] Update changelog

Documentation/Introduction/Index.rst, README.md
=> [TASK] Mention the newsletter in the README and in the documentation

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Domain/Repository/Event/EventRepository.php, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventList.html, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, ext_tables.php
=> [FEATURE] Add a button for deleting events in the BE module

Tests/Functional/Domain/Repository/Event/Fixtures/DeletedSingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/HiddenSingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventOnPage.csv
We also want to explicitly check that some records are _not_ deleted or hidden.
=> [TASK] Make some DB fixtures more specific

CHANGELOG.md, Classes/Controller/BackEnd/RegistrationController.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html, Tests/Functional/Domain/Repository/Registration/Fixtures/BackEndUser.csv, Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedHiddenRegistrationOnPage.csv, Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedRegistrationOnPage.csv, Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenRegistrationOnPage.csv, Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationOnPage.csv, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, ext_tables.php, phpstan-baseline.neon
=> [FEATURE] Add a button for deleting registrations in the BE module

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
Approving only applies to translations, not to the original English labels.
Fixes #3016
=> [TASK] Drop `approved="yes"` from the English locallang files

CHANGELOG.md, Classes/Controller/BackEnd/RegistrationController.php, Resources/Private/Partials/BackEnd/RegistrationList.html, Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [TASK] Show the registrations list after deleting a registration

CHANGELOG.md, Resources/Private/Templates/BackEnd/Email/Compose.html
=> [TASK] Increase height of the content area in the BE module email form

CHANGELOG.md
=> [TASK] Improve a changelog entry

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/DeletedSingleEventWithTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicWithTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithIntegerTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithSqlCharactersTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithWhitespaceIntegerTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/TimedSingleEventWithTitleOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/TwoSingleEventsOnPage.csv, phpstan-baseline.neon
=> [FEATURE] Add a search method to the `EventRepository`

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/SearchForm.html, Resources/Private/Templates/BackEnd/Event/Search.html, Resources/Private/Templates/BackEnd/Module/Overview.html, Tests/Unit/Controller/BackEnd/EventControllerTest.php, ext_tables.php
=> [FEATURE] Add search functionality to the BE module

Classes/Templating/TemplateHelper.php
This slightly improves performance.
=> [TASK] Prefix native PHP functions with a backslash

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [TASK] Document internal variables for the list view

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [TASK] Drop unused elements from internal list view data

Classes/Templating/TemplateHelper.php
=> [TASK] Add some more blank lines to improve code readability

Classes/Templating/TemplateHelper.php
=> [TASK] Delete commented-out code

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [TASK] Improve a type annotation for `pi_wrapInBaseClass()`

Classes/Templating/TemplateHelper.php
=> [TASK] Use spaces for indentation

Classes/Templating/TemplateHelper.php
=> [TASK] Drop `@see` annotations from `TemplateHelper`

Classes/Templating/TemplateHelper.php
=> [TASK] Use spaces for indentation in output HTML

Classes/Templating/TemplateHelper.php
=> [TASK] Fix a comment

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/AbstractModel.php, Classes/ViewHelpers/RichTextViewHelper.php, Tests/Unit/ViewHelpers/RichTextViewHelperTest.php
=> [BUGFIX] Fix deprecation warning when rendering rich text

.github/workflows/codecoverage.yml, composer.json
=> [TASK] Switch to the Coveralls GitHub action

README.md
=> [TASK] Remove the download counter badge from the README

.gitattributes, .github/workflows/ci.yml, Build/xliff/xliff-lint, composer.json
=> [FEATURE] Add XLIFF linting to the CI toolchain

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php
=> [BUGFIX] Work around problems with back button in the BE module search

.github/workflows/codecoverage.yml
=> [TASK] Show more debug information in the code coverage CI job

CHANGELOG.md, Resources/Private/Layouts/BackEndModule.html
=> [BUGFIX] Use the correct queue for flash messages in the BE module

phpstan.neon
=> [TASK] Reduce redundancies in the PHPStan configuration

CHANGELOG.md, Classes/BagBuilder/EventBagBuilder.php, Classes/Controller/BackEnd/EventController.php, Classes/Csv/CsvDownloader.php, Classes/Csv/EventListView.php, Classes/Email/EmailBuilder.php, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/LegacyRegistration.php, Classes/OldModel/LegacySpeaker.php, Classes/Service/RegistrationManager.php, Classes/Service/SingleViewLinkBuilder.php, Classes/Templating/TemplateHelper.php, ext_tables.php
Fixes #2960
Fixes #2962
Fixes #2964
Fixes #2974
Fixes #2966
Fixes #2978
Fixes #3156
Fixes #3133
Fixes #3271
=> [TASK] Deprecate some things

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/Templating/TemplateHelper.php, Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php
=> [TASK] Add `rel="nofollow"` to the sorting links in the list view

Tests/Unit/Hooks/HookProviderTest.php, Tests/Unit/SchedulerTasks/MailNotifierConfigurationTest.php
=> [TASK] Add missing `@covers` annotations

CHANGELOG.md, Tests/Unit/Controller/BackEnd/EmailControllerTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, Tests/Unit/Controller/EventRegistrationControllerTest.php, Tests/Unit/Controller/EventUnregistrationControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [BUGFIX] Mock controller methods in a TYPO3-version-specific way

CHANGELOG.md, Classes/OldModel/LegacyRegistration.php
=> [BUGFIX] Avoid using the deprecated Extbase models

Tests/Functional/Templating/TemplateHelperTest.php, Tests/Unit/Configuration/LegacyConfigurationTest.php, Tests/Unit/Templating/TemplateHelperTest.php
This paves the way to PHPUnit 9.
=> [TASK] Use the newer mocking API

CHANGELOG.md, Classes/FrontEnd/CategoryList.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/SelectorWidget.php, Classes/Model/Event.php, Classes/Model/Organizer.php, Classes/Model/Place.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/SchedulerTasks/MailNotifier.php, phpstan-baseline.neon
=> [BUGFIX] Always use strict comparisons

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_seminars.php
=> [FEATURE] Allow viewing event UIDs in the TCEforms

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Resources/Private/Language/locallang.xlf, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [FEATURE] Show flash message after deleting an event/registration

CHANGELOG.md, Classes/Controller/BackEnd/EventStatisticsTrait.php, Classes/Controller/BackEnd/PageUidTrait.php, Classes/Controller/BackEnd/PermissionsTrait.php, Classes/Domain/Model/Event/EventDateTrait.php, Classes/Domain/Model/Event/EventTopicTrait.php, Classes/Domain/Model/Event/EventTrait.php, Classes/Domain/Model/RawDataTrait.php, Classes/Domain/Model/Registration/AttendeesTrait.php, Classes/Domain/Model/Registration/BillingAddressTrait.php, Classes/Domain/Model/Registration/PaymentTrait.php, Tests/Functional/Traits/BagHelper.php, Tests/Functional/Traits/CollectionHelper.php, Tests/Functional/Traits/FalHelper.php, Tests/Support/BackEndTestsTrait.php, Tests/Support/LanguageHelper.php, Tests/Unit/Traits/EmailTrait.php, Tests/Unit/Traits/MakeInstanceTrait.php
=> [CLEANUP] Replace incorrectly used `@mixin` annotations

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/TCA/tx_seminars_seminars.php, Resources/Private/Language/locallang_db.xlf, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, composer.json, ext_tables.sql
=> [FEATURE] Add event formats (on-site, hybrid, online)

.github/workflows/ci.yml
Performance, baby!
Fixes #3301
=> [TASK] Switch the code quality checks to PHP 8.3

CHANGELOG.md, Resources/Private/Language/locallang_db.xlf
=> [BUGFIX] Fix locallang key for the online event format

Resources/Private/Language/locallang_db.xlf
=> [FEATURE] Add TCEforms labels for the new venue fields

CHANGELOG.md, Classes/Domain/Model/Venue.php, Configuration/TCA/tx_seminars_sites.php, Tests/Functional/Domain/Repository/Fixtures/VenueRepository/VenueWithAllFields.xml, Tests/Functional/Domain/Repository/VenueRepositoryTest.php, Tests/Unit/Domain/Model/VenueTest.php, ext_tables.sql
- contact person
- email address
- phone number
Fixes #3353
=> [FEATURE] Add more fields to the venues

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/TCA/tx_seminars_seminars.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_tables.sql
=> [FEATURE] Add a field for the webinar URLs to events

.github/dependabot.yml
=> [TASK] Set the Dependabot target milestone to 5.7.0

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/Functional/Service/RegistrationManagerTest.php
=> [FEATURE] Include the webinar URL in the calendar invite

CHANGELOG.md, Classes/Service/RegistrationManager.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Mail/e-mail.html, Tests/Functional/Service/RegistrationManagerTest.php
=> [FEATURE] Include the webinar email in the thank-you email

CHANGELOG.md, Resources/Private/Language/locallang_db.xlf
=> [FEATURE] Add TCA label for the additional email text

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/TCA/tx_seminars_seminars.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_tables.sql
=> [FEATURE] Add `Event.additionalEmailText`

CHANGELOG.md, Resources/Private/Templates/Mail/e-mail.html
Also move the webinar URL around for consistency.
=> [BUGFIX] Fix the webinar URL in the email

CHANGELOG.md, Configuration/TCA/tx_seminars_seminars.php
=> [TASK] Make the additional email text an exclude field

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
This will break in TYPO3 12LTS.
Fixes #3368
=> [BUGFIX] Do not provide the `LanguageService` via DI anymore

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/EventDate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/EventDateAndDuplicate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/HiddenSingleEvent.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/HiddenSingleEventAndDuplicate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventAndDuplicateOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventAndDuplicateWithResetData.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithDataToReset.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithOrganizer.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithOrganizerAndDuplicate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithScalarData.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithScalarDataAndDuplicate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithToOneRelations.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithToOneRelationsAndDuplicate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/VisibleSingleEvent.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/VisibleSingleEventAndDuplicate.csv
=> [FEATURE] Add `EventRepository.duplicateViaDataHandler()`

ext_tables.sql
=> [DOCS] Fix target milestone of a deprecation

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Classes/Hooks/DataHandlerHook.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithOneRegistration.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithOneRegistrationAndDuplicateWithRegistrations.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithOneRegistrationAndDuplicateWithoutRegistrations.csv, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Hooks/Fixtures/DataHandlerHook/BackEndUser.csv, Tests/Functional/Hooks/Fixtures/DataHandlerHook/copy/SingleEventOnPage.csv, Tests/Functional/Hooks/Fixtures/DataHandlerHook/copy/SingleEventOnPageAndDuplicate.csv, Tests/Functional/Hooks/Fixtures/DataHandlerHook/copy/SingleEventWithOneRegistration.csv, Tests/Functional/Hooks/Fixtures/DataHandlerHook/copy/SingleEventWithOneRegistrationAndDuplicateWithRegistrations.csv, ext_localconf.php, phpstan-baseline.neon
=> [BUGFIX] Do not duplicate registrations when duplicating an event

CHANGELOG.md
=> [DOCS] Autoformat the changelog

CHANGELOG.md, Resources/Private/Language/locallang.xlf
=> [FEATURE] Add localized label for the "duplicate event" button

CHANGELOG.md, Resources/Private/Language/locallang.xlf
=> [TASK] Move and improve a label

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Resources/Private/Partials/BackEnd/EventList.html, Tests/Unit/Controller/BackEnd/EventControllerTest.php, ext_tables.php
=> [FEATURE] Add a "duplicate event" button to the BE module

CHANGELOG.md, Classes/Configuration/ListViewConfigurationCheck.php, Classes/FrontEnd/CategoryList.php, Classes/FrontEnd/DefaultController.php, Classes/Model/Category.php, Classes/OldModel/LegacyCategory.php, Classes/OldModel/LegacyEvent.php, Configuration/FlexForms/flexforms_pi1.xml, Configuration/TCA/tx_seminars_categories.php, Configuration/TypoScript/FrontEnd.typoscript, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, ext_tables.sql
=> [TASK] Deprecate icons for categories

CHANGELOG.md, Classes/OldModel/LegacyEvent.php
- `canSomebodyRegister`
- `canSomebodyRegisterMessage`
- `isRegistrationDeadlineOver`
Fixes #3395
[ci skip]
=> [TASK] Deprecate some functions from `LegacyEvent`

CHANGELOG.md, composer.json, ext_emconf.php
=> [TASK] Require oelib >= 6.0.0

ext_tables.sql
=> [TASK] Drop the dummy record marker columns from the DB

.github/dependabot.yml, composer.json
=> [TASK] Update `composer-normalize`

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [TASK] Drop `$isFileName` parameter in `::getConfValueString()`

.gitattributes, .github/workflows/ci.yml, CHANGELOG.md, composer-unused.php, composer.json
=> [FEATURE] Include composer-unused to find unused packages

CHANGELOG.md, composer.json
=> [TASK] Require Emogrifier >= 7.2.0

.github/workflows/ci.yml
=> [TASK] Also run CI on the 5.x branch

.github/workflows/ci.yml
This will help speed up the builds without losing any vital information.
=> [TASK] Reduce the inner parts of the CI matrix

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/OldModel/AbstractModel.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/OldModel/LegacyTimeSlot.php, Classes/Seo/SlugGenerator.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/OldModel/AbstractModelTest.php, Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php, phpstan-baseline.neon
=> [CLEANUP] Stop calling deprecated DBAL methods

.github/workflows/ci.yml
=> [TASK]  Reduce the CI matrix even more

.github/workflows/ci.yml, composer.json
=> [TASK] Drop `composer normalize`

CHANGELOG.md, Classes/BackEnd/TceForms.php, Classes/Bag/AbstractBag.php, Classes/BagBuilder/EventBagBuilder.php, Classes/Configuration/SharedConfigurationCheck.php, Classes/Domain/Repository/AbstractRawDataCapableRepository.php, Classes/FrontEnd/SelectorWidget.php, Classes/Hooks/DataHandlerHook.php, Classes/Mapper/EventMapper.php, Classes/OldModel/AbstractModel.php, Classes/OldModel/LegacyEvent.php, Tests/Functional/OldModel/AbstractModelTest.php, phpstan-baseline.neon
=> [BUGFIX] Avoid more deprecated DBAL `fetch*` methods

CHANGELOG.md, Classes/Bag/AbstractBag.php, Classes/BagBuilder/EventBagBuilder.php, Classes/Domain/Repository/AbstractRawDataCapableRepository.php, Classes/Domain/Repository/Event/EventRepository.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Classes/FrontEnd/SelectorWidget.php, Classes/Hooks/DataHandlerHook.php, Classes/Mapper/EventMapper.php, Classes/OldModel/AbstractModel.php, Classes/OldModel/LegacyEvent.php, Classes/Seo/SlugGenerator.php, Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [TASK] Avoid calling the deprecated DBAL `execute()`

.github/dependabot.yml, .phive/phars.xml, CHANGELOG.md, Configuration/FunctionalTests.xml, Configuration/UnitTests.xml, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyFunctional/Csv/AbstractRegistrationListViewTest.php, Tests/LegacyFunctional/Csv/CsvDownloaderTest.php, Tests/LegacyFunctional/Csv/EventListViewTest.php, Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php, Tests/LegacyFunctional/FrontEnd/RegistrationsListTest.php, Tests/LegacyFunctional/FrontEnd/RequirementsListTest.php, Tests/LegacyFunctional/OldModel/LegacyEventTest.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php, Tests/Unit/Service/RegistrationProcessorTest.php, composer.json, phpstan-baseline.neon
=> [TASK] Upgrade to PHPUnit 9.x

.gitattributes, .github/workflows/ci.yml, Classes/Hooks/DataHandlerHook.php, Classes/Templating/TemplateHelper.php, composer.json, phpcs.xml.dist
This reverts commit 757244cda432c42c9f6f288c1842a775027416ff.
=> Revert "[TASK] Drop PHP_CodeSniffer (#3574)"

Tests/Unit/Controller/BackEnd/EmailControllerTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
This allows us to simplify our code a bit.
=> [TASK] Do not mock methods that do not get called

CHANGELOG.md, Configuration/FlexForms/flexforms_pi1.xml, Resources/Private/Language/locallang.xlf
=> [TASK] Remove the salutation mode setting from the flexforms

CHANGELOG.md, Tests/Unit/ViewHelpers/RichTextViewHelperTest.php
=> [BUGFIX] Provide PSR-7 request when testing `RichTextViewHelper`

CHANGELOG.md, Classes/Templating/TemplateHelper.php
=> [BUGFIX] Drop unused dependency on `MarkerBasedTemplateService`

composer.json, rector.php
=> [TASK] Add Rector as a development dependency

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/Seo/SlugGenerator.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Seo/SlugGeneratorTest.php, Tests/Unit/Seo/SlugGeneratorTest.php
=> [TASK] Make `SlugGenerator` and `DataHandlerHook` DI-capable

CHANGELOG.md, Tests/Unit/Hooks/DataHandlerHookTest.php, Tests/Unit/Seo/SlugGeneratorTest.php
=> [TASK] Add tests for the singleton property

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Classes/Controller/EventUnregistrationController.php, Classes/Controller/FrontEndEditorController.php, Tests/Unit/Controller/EventRegistrationControllerTest.php, Tests/Unit/Controller/EventUnregistrationControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [TASK] Use constructor DI for the controllers

CHANGELOG.md, Classes/Service/EventStatisticsCalculator.php, Classes/Service/RegistrationGuard.php, Tests/Unit/Service/EventStatisticsCalculatorTest.php, Tests/Unit/Service/RegistrationGuardTest.php
=> [TASK] Use constructor DI for more services

CHANGELOG.md, Classes/Service/RegistrationProcessor.php, Tests/Functional/Service/RegistrationProcessorTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
=> [TASK] Use constructor DI for `RegistrationProcessor`

.github/workflows/ci.yml
=> [FEATURE] Add a Rector CI job

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, Classes/Service/RegistrationManager.php, Classes/Templating/TemplateHelper.php, Tests/Functional/FrontEnd/DefaultController/ListViewTest.php, Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php, Tests/Functional/FrontEnd/Fixtures/TestingDefaultController.php, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php, Tests/Unit/Configuration/LegacyConfigurationTest.php, Tests/Unit/Templating/Fixtures/TestingTemplateHelper.php
=> [TASK] Stop setting `TemplateHelper::cObj`

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Classes/Controller/EventUnregistrationController.php
=> [TASK] Add broader return type to some controller actions

CHANGELOG.md, Classes/Service/RegistrationManager.php
=> [TASK] Drop the obsolete `RegistrationManager::SEND_*_EMAIL` constants

CHANGELOG.md, Classes/OldModel/LegacySpeaker.php
=> [TASK] Drop `LegacySpeaker::isHidden()`

CHANGELOG.md, Classes/OldModel/AbstractTimeSpan.php
=> [TASK] Drop `LegacyAbstractTimeSpam::getEndDate()`

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php
=> [TASK] Drop `RegistrationManager::existsSeminar/existsSeminarMessage`

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Classes/Controller/EventUnregistrationController.php, Tests/Unit/Controller/EventUnregistrationControllerTest.php, phpstan-baseline.neon
=> [TASK] Mock the behavior of `redirect` more accurately in tests

CHANGELOG.md
=> [DOCS] De-duplicate changelog entries

rector.php
=> [TASK] Bump Rector to TYPO3 11LTS

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, Tests/LegacyFunctional/Csv/AbstractRegistrationListViewTest.php
=> [TASK] Use arrow functions

rector.php
=> [TASK] Set Rector to PHP 7.4

Tests/Unit/Controller/EventRegistrationControllerTest.php
=> [TASK] Remove non-essential assertions from controller tests

CHANGELOG.md, Classes/Controller/BackEnd/EmailController.php, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Tests/Unit/Controller/BackEnd/EmailControllerTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [BUGFIX] Always return a response in the BE controllers

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Tests/Unit/Controller/EventRegistrationControllerTest.php
=> [BUGFIX] Always return a response in `EventRegistrationController`

CHANGELOG.md, Classes/Controller/EventUnregistrationController.php, Tests/Unit/Controller/EventUnregistrationControllerTest.php
=> [BUGFIX] Always return a response in `EventUnregistrationController`

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/FlexForms.php, Classes/BackEnd/Permissions.php, Tests/Unit/BackEnd/PermissionsTest.php, phpstan-baseline.neon
Also improve some type annotations and drop an
unnecessary property.
Part of #3376
=> [TASK] Use native type declarations in `BackEnd/`

CHANGELOG.md, Classes/Bag/AbstractBag.php, Classes/Bag/CategoryBag.php, Classes/Bag/EventBag.php, Classes/Bag/OrganizerBag.php, Classes/Bag/RegistrationBag.php, Classes/Bag/SpeakerBag.php, Classes/Bag/TimeSlotBag.php, Tests/Unit/Bag/Fixtures/TestingBag.php
=> [TASK] Use native type declarations in `Bag/`

Documentation/Introduction/KeyFeatures/Index.rst
=> [DOCS] Drop removed features from the feature list

CHANGELOG.md, Classes/Configuration/Traits/SharedPluginConfiguration.php
=> [TASK] Use native type declarations in `Configuration/`

CHANGELOG.md, Classes/Controller/BackEnd/EventStatisticsTrait.php, Classes/Controller/BackEnd/PermissionsTrait.php
=> [TASK] Use native type declarations in `Controller/`

CHANGELOG.md, Classes/Csv/AbstractListView.php, Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/CsvDownloader.php, Classes/Csv/DownloadRegistrationListView.php, Classes/Csv/EmailRegistrationListView.php, Classes/SchedulerTasks/MailNotifier.php, Tests/LegacyFunctional/Csv/AbstractRegistrationListViewTest.php, phpstan-baseline.neon
=> [TASK] Use native type declarations in `Csv/`

CHANGELOG.md, Classes/Domain/Model/AccommodationOption.php, Classes/Domain/Model/EventType.php, Classes/Domain/Model/FoodOption.php, Classes/Domain/Model/Organizer.php, Classes/Domain/Model/PaymentMethod.php, Classes/Domain/Model/Price.php, Classes/Domain/Model/RawDataTrait.php, Classes/Domain/Model/RegistrationCheckbox.php, Classes/Domain/Model/Speaker.php, Classes/Domain/Model/Venue.php
=> [TASK] Use native types for the other domain models

CHANGELOG.md, Classes/Domain/Model/Event/EventDate.php, Classes/Domain/Model/Event/EventDateTrait.php, Classes/Domain/Model/Event/EventStatistics.php, Classes/Domain/Model/Event/EventTopicTrait.php, Classes/Domain/Model/Event/EventTrait.php, Classes/Domain/Model/Registration/AttendeesTrait.php, Classes/Domain/Model/Registration/BillingAddressTrait.php, Classes/Domain/Model/Registration/PaymentTrait.php, Classes/Domain/Model/Registration/Registration.php
=> [TASK] Use native types for the event and registration models

CHANGELOG.md, Classes/Email/EmailBuilder.php, Classes/Email/Salutation.php, phpstan-baseline.neon
=> [TASK] Use native types in `Email/`

CHANGELOG.md, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationsList.php, Classes/FrontEnd/SelectorWidget.php
=> [TASK] Use native types in `FrontEnd/`

CHANGELOG.md, Classes/Hooks/HookProvider.php, Tests/Unit/Hooks/HookProviderTest.php, phpstan-baseline.neon
=> [TASK] Use native types in `Hooks/`

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, phpstan-baseline.neon
=> [TASK] Improve type safety in `LegacyEvent`

CHANGELOG.md, Documentation/Installation/Upgrading.rst
Fixes #2515
Fixes #3497
Fixes #3498
=> [DOCS] Add 6.x upgrade notes and remove 5.x upgrade notes

CHANGELOG.md, Classes/SchedulerTasks/MailNotifier.php, Classes/SchedulerTasks/MailNotifierConfiguration.php, phpstan-baseline.neon
=> [TASK] Use native types in `SchedulerTasks/`

CHANGELOG.md, Classes/Seo/SlugContext.php, Classes/Seo/SlugGenerator.php
=> [TASK] Use native types in `Seo/`

CHANGELOG.md, Classes/Service/EmailService.php, Classes/Service/RegistrationManager.php, phpstan-baseline.neon
=> [TASK] Use native types in `Service/`

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/Templating/TemplateHelper.php, phpstan-baseline.neon
=> [TASK] Use native types in `Templating/`

CHANGELOG.md, Classes/ViewHelpers/RichTextViewHelper.php
=> [TASK] Use native types in `ViewHelpers/`

CHANGELOG.md, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/Support/BackEndTestsTrait.php, Tests/Support/LanguageHelper.php, phpstan-baseline.neon
=> [TASK] Use native types in `Tests/Support`

CHANGELOG.md, Tests/Functional/Domain/Repository/AccommodationOptionRepositoryTest.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/EventTypeRepositoryTest.php, Tests/Functional/Domain/Repository/FoodOptionRepositoryTest.php, Tests/Functional/Domain/Repository/OrganizerRepositoryTest.php, Tests/Functional/Domain/Repository/PaymentMethodRepositoryTest.php, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Functional/Domain/Repository/RegistrationCheckboxRepositoryTest.php, Tests/Functional/Domain/Repository/SpeakerRepositoryTest.php, Tests/Functional/Domain/Repository/VenueRepositoryTest.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php
=> [TASK] Use native types in `Tests/Functional/`

CHANGELOG.md, Tests/Unit/Controller/BackEnd/EmailControllerTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, Tests/Unit/Controller/EventRegistrationControllerTest.php, Tests/Unit/Controller/EventUnregistrationControllerTest.php, Tests/Unit/Hooks/HookProviderTest.php, Tests/Unit/Model/EventTest.php, Tests/Unit/Traits/EmailTrait.php, Tests/Unit/Traits/MakeInstanceTrait.php, phpstan-baseline.neon
=> [TASK] Use native types in `Tests/Unit/`

CHANGELOG.md, Classes/UpgradeWizards/RemoveDuplicateEventVenueRelationsUpgradeWizard.php, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/NoRelations.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/OneDuplicateAndOneUniqueRelationFromOneEventToTwoVenues.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/OneUniqueRelation.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/ThreeDuplicateRelations.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/TwoDuplicateRelations.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/TwoUniqueRelationsFromOneEventToTwoVenues.csv, Tests/Functional/UpgradeWizards/Fixtures/RemoveDuplicateEventVenueRelationsUpgradeWizard/TwoUniqueRelationsFromTwoEventsToTheSameVenue.csv, Tests/Functional/UpgradeWizards/RemoveDuplicateEventVenueRelationsUpgradeWizardTest.php, Tests/Unit/UpgradeWizards/RemoveDuplicateEventVenueRelationsUpgradeWizardTest.php, ext_localconf.php
=> [BUGFIX] Add upgrade wizard to remove duplicate event-venue relations

CHANGELOG.md, Tests/Functional/UpgradeWizards/RemoveDuplicateEventVenueRelationsUpgradeWizardTest.php
=> [TASK] Skip some tests in V12 that are not relevant to V12 anymore

Classes/OldModel/LegacyEvent.php, phpstan-baseline.neon
=> [TASK] Drop obsolete de-duplication code for the venue display

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php
=> [TASK] Make `DataHandlerHook` stateless

CHANGELOG.md, Classes/Service/RegistrationManager.php, Classes/Service/RegistrationProcessor.php, Tests/Unit/Service/RegistrationManagerTest.php, Tests/Unit/Service/RegistrationProcessorTest.php, phpstan-baseline.neon
=> [TASK] Make the `RegistrationManager` stateless

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/Service/RegistrationManager.php, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/Functional/FrontEnd/DefaultController/ListViewTest.php, Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyFunctional/Bag/EventBagTest.php, Tests/LegacyFunctional/BagBuilder/EventBagBuilderTest.php, Tests/LegacyFunctional/BagBuilder/RegistrationBagBuilderTest.php, Tests/LegacyFunctional/Csv/CsvDownloaderTest.php, Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php, Tests/LegacyFunctional/FrontEnd/RegistrationsListTest.php, Tests/LegacyFunctional/FrontEnd/RequirementsListTest.php, Tests/LegacyFunctional/FrontEnd/SelectorWidgetTest.php, Tests/LegacyFunctional/OldModel/LegacyEventTest.php, Tests/LegacyFunctional/OldModel/LegacyRegistrationTest.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php, Tests/Unit/Service/RegistrationManagerTest.php
=> [TASK] Make the `RegistrationManager` a proper TYPO3 singleton

CHANGELOG.md, Documentation/Introduction/Index.rst, README.md
=> [DOCS] Announce the early-access program

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventAndDuplicateWithResetData.csv, Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithDataToReset.csv
=> [BUGFIX] Ignore the webinar URL when duplicating an event

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [BUGFIX] Fix translation for flash message in BE module

Documentation/Introduction/LiveExamples.rst
- fix ReST syntax
- add another reference
- change the heading from "live examples" to "references"
- use a less clunky syntax for providing the URLs
Fixes #3786
Fixes #3787
Fixes #3788
Fixes #3789
=> [DOCS] Rework the references/live examples section

CHANGELOG.md, Classes/OldModel/LegacyTimeSlot.php, Tests/LegacyFunctional/OldModel/LegacyTimeSlotTest.php
=> [TASK] Do not display "will be announced" for time slots

CHANGELOG.md, Classes/OldModel/AbstractTimeSpan.php, Tests/Functional/OldModel/AbstractTimeSpanTest.php
This makes the display a bit more compact.
Fixes #3814
=> [TASK] Do not display "will be announced" for date or time of not set

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithBeginAndWithEndDate.csv, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithBeginAndWithoutEndDate.csv, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithOneTimeSlot.csv, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithTwoTimeSlots.csv, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithoutBeginAndWithEndDate.csv, Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithoutDate.csv, Tests/Functional/OldModel/LegacyEventTest.php
=> [BUGFIX] Only display the event times if there are no time slots

Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyTimeSlot.php, Configuration/TCA/tx_seminars_timeslots.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, ext_tables.sql
=> [TASK] Deprecate time slot entry dates

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventListHeader.html, Resources/Private/Templates/BackEnd/Event/Search.html, Resources/Private/Templates/BackEnd/Module/Overview.html
=> [FEATURE] Add button in the BE module to create an event

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/ModuleController.php, Classes/Controller/BackEnd/RegistrationController.php, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html, Resources/Public/JavaScript/BackEnd/DeleteConfirmation.js, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/ModuleControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
=> [FEATURE] Show a confirmation when deleting a record in the BE module

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
This is the 5.x backport of #3871.
=> [TASK] Remove unneeded `resname` from the language files

Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
=> [DOCS] Fix version number in deprecation comment

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html, Resources/Private/Templates/BackEnd/Module/Overview.html, Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/FrontEnd/FrontEnd.html, Resources/Private/Templates/FrontEndEditor/Index.html, Resources/Public/CSS/FrontEnd/FrontEnd.css
=> [TASK] Use responsive Bootstrap tables in the FE and BE

CHANGELOG.md, Resources/Private/Templates/FrontEnd/FrontEnd.html
=> [TASK] Make the time slot table in the FE striped as well

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php
=> [BUGFIX] Use the mapped property name in queries

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Event/ArchiveList.html, Tests/Functional/Controller/EventControllerTest.php, Tests/Functional/Controller/Fixtures/EventController/archiveAction/MultiDayPastEvent.csv, Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEvent.csv, Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithOneVenue.csv, Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithTwoVenuesInDifferentCities.csv, Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithTwoVenuesInSameCity.csv, Tests/Functional/Controller/Fixtures/EventController/archiveAction/SingleDayPastEvent.csv, phpstan-baseline.neon
=> [FEATURE] Add more columns to the event archive

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Event/ArchiveList.html
- have the date column first, then the title
- use "topic" as heading for the title
=> [TASK] Polish the event archive list

CHANGELOG.md, Resources/Private/Language/locallang_db.xlf
=> [TASK] Make the TCEforms labels for the email footer more concise

CHANGELOG.md, Classes/OldModel/LegacyEvent.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
=> [TASK] Make the label for the additional terms more generic

CHANGELOG.md, Classes/Model/Event.php, Tests/Unit/Model/EventTest.php, phpstan-baseline.neon
This method is only called from tests.
Part of #3422
=> [TASK] Drop `Event.getAttendeeNamesAfterLastDigest`

CHANGELOG.md, Resources/Private/Language/locallang.xlf
=> [TASK] Lowercase the (un)registration link labels

Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyTimeSlot.php, Configuration/TCA/tx_seminars_timeslots.php, Resources/Private/Language/locallang_db.xlf, ext_tables.sql
=> [TASK] Deprecate speakers for time slots

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyTimeSlot.php, Configuration/TCA/tx_seminars_timeslots.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Templates/FrontEnd/FrontEnd.html, Tests/LegacyFunctional/OldModel/LegacyTimeSlotTest.php, Tests/Unit/OldModel/Fixtures/TestingLegacyTimeSlot.php, ext_tables.sql
=> [TASK] Drop the entry date and speakers from the timeslots

CHANGELOG.md, Classes/Model/Event.php, Tests/LegacyFunctional/Model/EventTest.php, Tests/Unit/Model/EventTest.php
- `get/set/hasLanguage`
- TYPE_DATE
=> [TASK] Remove unused methods and a constant from `Event`

CHANGELOG.md, Classes/BackEnd/EmailService.php, Tests/Functional/BackEnd/EmailServiceTest.php, phpstan-baseline.neon
This was not documented, not intuitive and hard to use.
=> [TASK] Drop automatic salutations from the backend module emails

Tests/Functional/BackEnd/EmailServiceTest.php, Tests/Functional/BackEnd/Fixtures/BackEndUser.csv
We don't need a BE user for this test.
=> [TASK] Simplify `EmailServiceTest`

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationsList.php, Classes/OldModel/AbstractModel.php, Tests/Functional/OldModel/AbstractModelTest.php, Tests/Unit/OldModel/AbstractModelTest.php, phpstan-baseline.neon
=> [TASK] Drop `AbstractModel::comesFromDatabase()`

CHANGELOG.md, Classes/OldModel/LegacyRegistration.php, Tests/LegacyFunctional/OldModel/LegacyRegistrationTest.php
This method is not used anymore.
=> [TASK] Drop `LegacyRegistration::commitToDatabase()`

Classes/Model/Event.php, Tests/Unit/Model/EventTest.php
This reverts commit 2476733fadceb9c7b1ffe17140cf62d1e23aac1e.
Part of #3994
=> Revert "[TASK] Drop `Event.getRegistrationsAfterLastDigest` (#3941)"

CHANGELOG.md, Classes/SchedulerTasks/RegistrationDigest.php, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/Functional/SchedulerTasks/RegistrationDigestTest.php, Tests/LegacyFunctional/SchedulerTasks/MailNotifierTest.php
This will make using DI with it easier.
=> [TASK] Make `RegistrationDigest` a singleton

phpstan-baseline.neon, phpstan.neon
=> [TASK] PHPStan-ignore instanceof checks only in the tests

phpstan-baseline.neon, phpstan.neon
=> [TASK] Also check `ext_(localconf|tables).php` with PHPStan

CHANGELOG.md, composer.json, ext_emconf.php, phpstan-baseline.neon
=> [TASK] Require oelib >= 6.1.0

CHANGELOG.md, composer.json, ext_emconf.php
=> [TASK] Require feuserextrafields >= 6.4.0

Classes/Domain/Repository/EventTypeRepository.php, Classes/Domain/Repository/OrganizerRepository.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Classes/Domain/Repository/SpeakerRepository.php, Classes/Domain/Repository/VenueRepository.php
=> [TASK] Stop using the deprecated `StoragePageAgnostic` trait

Classes/Domain/Repository/Event/EventRepository.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
=> [TASK] Stop using the deprecated `DirectPersist` trait/interface

CHANGELOG.md, composer.json
=> [TASK] Allow `typo3fluid/fluid:^4.0`

CHANGELOG.md, Resources/Private/Language/locallang.xlf
This helps the event lists render nicely even within narrow page layouts.
=> [TASK] Shorten some labels for the event lists

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Event/Vacancies.html, Tests/Functional/Controller/EventControllerTest.php, Tests/Functional/Controller/Fixtures/EventController/outlookAction/FutureEventWithEnoughVacanciesButDeadlineOver.csv, Tests/Functional/Controller/Fixtures/EventController/outlookAction/FutureEventWithoutRegistration.csv
- display an infinity symbol for infinite seats
- display the threshold for enough seats
=> [TASK] Make the display for "enough vancancies" more concise

Resources/Private/Partials/EventDate.html
Avoid nested inline view helpers - for the sake of the sanity of all of us.
=> [TASK] Simplify the date formatting partial even more

CHANGELOG.md, Resources/Private/Language/locallang.xlf
=> [TASK] Fix the casing of some labels

CHANGELOG.md, Classes/Domain/Model/Registration/Registration.php, Configuration/TCA/tx_seminars_attendances.php, Resources/Private/Language/locallang_db.xlf
Also move the registration status above the attendance mode in the TCEforms.
This is a pre-patch to adding a third registration status (non-binding pre-preregistration).
=> [TASK] Make the registration status a drop-down

Documentation/Installation/GetAFront-endUserLogin(anyPossiblyRegistration)Running/Index.rst
This is the 5.x backport of #4107.
=> [DOCS] Document the required redirect settings for login

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/RegistrationList.html
This is the 5.x backport of #4111.
=> [BUGFIX] Improve display of users without full name in BE module

CHANGELOG.md, Classes/Domain/Model/Event/EventTopicTrait.php, Classes/Domain/Model/Registration/AttendeesTrait.php, Classes/Domain/Model/Registration/PaymentTrait.php, Classes/Domain/Model/Registration/Registration.php
This is the 5.x backport of #4115.
=> [BUGFIX] Improve type safety with lazy loading proxies

Resources/Private/Language/locallang.xlf
=> [TASK] Lowercase some labels in the flexforms

CHANGELOG.md, Configuration/TypoScript/PluginSettings.typoscript, Configuration/TypoScript/constants.typoscript
This setting will be removed again once we have the new price system in place.
=> [FEATURE] Add a temporary setting for the VAT rate

CHANGELOG.md, Configuration/TypoScript/PluginShared.typoscript, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
=> [TASK] CSV-export the registration date by default

CHANGELOG.md, ext_conf_template.txt
This double-serves as a feature flag for the incomplete feature.
=> [FEATURE] Add configuration for registrations PID in BE module

Documentation/Settings.yml
=> [TASK] Bump the copyright to 2025

README.md
=> [BUGFIX] Fix the CI status badge in the README

CHANGELOG.md
=> [DOCS] Move a changelog entry to the correct milestone

Documentation/Introduction/LiveExamples.rst
=> [DOCS] Add the JuBi Babenhausen to the references list

CHANGELOG.md, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html
This is the 5.x backport of #4195.
Fixes #4129
=> [TASK] Improve the hover texts in the BE module

Resources/Private/Language/locallang.xlf
=> [TASK] Simplify some labels

Classes/Hooks/Interfaces/SeminarListView.php, Documentation/Configuration/ConfiguringCss/Index.rst, Documentation/Reference/Hooks/Index.rst, Documentation/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/UsersManual/RolesRelatedToEventRecords/Index.rst
=> [DOCS] Remove residue of "my entered events"

CHANGELOG.md, Resources/Private/Language/locallang.xlf
Also fix a PR ID in the changelog.
=> [TASK] Make some labels keys more specific

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/OldModel/LegacyEvent.php, Documentation/Installation/EnablingUnregistration/Index.rst, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Tests/Functional/OldModel/LegacyEventTest.php, Tests/LegacyFunctional/OldModel/LegacyEventTest.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php, Tests/Unit/OldModel/Fixtures/TestingLegacyEvent.php, phpstan-baseline.neon
=> [TASK] Always allow unregistration with empty waiting list

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/Installation/SetUpThePlug-in/Index.rst, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Documentation/UsersManual/ManagingRegistrations/Index.rst
=> [TASK] Drop the unused `attendancesPID` configuration

Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf
This allows for autoformatting these files in the future, making development work less of a hassle.
=> [CLEANUP] Partially autoformat the XLF files

phpstan-baseline.neon, phpstan.neon
This will help avoid it suggesting things that are only possile in later PHP versions.
=> [TASK] Configure the target PHP version for PHPStan

Tests/Unit/Controller/EventUnregistrationControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Service/RegistrationGuardTest.php
This improves type safety (and also mocking it is not necessary).
Fixes #4256
=> [TASK] Do not mock `Context`

CHANGELOG.md, Tests/LegacyFunctional/OldModel/LegacyEventTest.php
=> [TASK] Drop obsolete data from tests

CHANGELOG.md, Resources/Private/Partials/MyRegistrations/Show.html
- move it up to directly below the event type
- style it as a Bootstrap alert depending on the registration status
=> [TASK] Update registration status display in "my registrations"

CHANGELOG.md, Classes/Domain/Model/Event/EventInterface.php, Classes/Domain/Model/Event/EventTrait.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAllFields.csv, Tests/Functional/Domain/Repository/Event/Fixtures/propertyMapping/SingleEventWithAllFields.csv, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php
Also move a DB fixture to a more specific folder.
=> [FEATURE] Add an `Event.slug` property

Tests/Functional/Controller/Fixtures/FrontEndEditorController/editAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newAction/AuxiliaryRecords.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php
Test that all form fields are present
(but do not test their contents yet).
=> [TASK] Add more tests field presence in the FE editor

composer.json
=> [BUGFIX] Use binaries directly in other Composer scripts

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/OldModel/LegacyEvent.php, Classes/Service/RegistrationGuard.php, Classes/Service/RegistrationManager.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/Installation/Upgrading.rst, Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/EventTitleAndDate.html, Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php, Tests/LegacyFunctional/OldModel/LegacyEventTest.php, Tests/LegacyFunctional/Service/RegistrationManagerTest.php, Tests/Unit/OldModel/Fixtures/TestingLegacyEvent.php, Tests/Unit/Service/RegistrationGuardTest.php, phpstan-baseline.neon
=> [TASK] Allow registrations for events without a date by default

CHANGELOG.md
=> [DOCS] Fix a PR ID in the changelog

.github/workflows/ci.yml, .github/workflows/codecoverage.yml, .github/workflows/release.yml
In this case, we don't need to quote the strings.
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
=> [CLEANUP] Do not quote workflow/job names for GitHub actions

CHANGELOG.md, Configuration/FlexForms/FrontEndEditor.xml, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/FrontEndEditor/Form.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/FrontEndEditorContentElement.csv
=> [FEATURE] Make the fields in the FE editor configurable

Configuration/FlexForms/FrontEndEditor.xml
=> [TASK] Insert another item slot in the fleforms configuration

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/FlexForms/FrontEndEditor.xml, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/FrontEndEditor/Form.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/FrontEndEditorContentElement.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createSingleEventAction/CreatedEventWithOfflineRegistrations.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editSingleEventAction/EventWithOwner.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php
=> [FEATURE] Add the number of offline registrations to the FE editor

Configuration/TCA/Overrides/fe_users.php, Resources/Private/Language/locallang_db.xlf
=> [TASK] Add separate TCEforms tab for seminars fields for FE users

Tests/Functional/Controller/Fixtures/FrontEndEditorController/editSingleEventAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newSingleEventAction/AuxiliaryRecords.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [TASK] Add tests for auxiliary records in the FE editor

Tests/Functional/Controller/Fixtures/FrontEndEditorController/createSingleEventAction/CreatedEventWithOfflineRegistrations.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createSingleEventAction/CreatedEventWithOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateSingleEventAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateSingleEventAction/UpdatedEventWithOrganizer.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php
=> [TASK] Add tests for setting the organizer in the FE editor

CHANGELOG.md, Classes/Domain/Model/Event/EventDateTrait.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php
=> [FEATURE] Add `Event.setSingleOrganizer()`

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Partials/FrontEndEditor/Form.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/FrontEndUserAndGroup.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createSingleEventAction/CreatedEventWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createSingleEventAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editSingleEventAction/EventWithOwnerWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editSingleEventAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newSingleEventAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateSingleEventAction/EventWithOwnerWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateSingleEventAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [FEATURE] Set the default organizer in the FE editor

CHANGELOG.md, Resources/Private/Language/locallang.xlf
=> [FEATURE] Add labels for categories in the FE editor

CHANGELOG.md, Classes/Domain/Repository/CategoryRepository.php, Tests/Functional/Domain/Repository/CategoryRepositoryTest.php, Tests/Functional/Domain/Repository/Fixtures/CategoryRepository/CategoryOnPage.csv, Tests/Functional/Domain/Repository/Fixtures/CategoryRepository/TwoCategoriesInReverseOrder.csv
- sort by title in ascending order
- ignore the storage PID
=> [FEATURE] Configure options for `CategoryRepository`

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/DeletedEventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/EventDate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/EventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/EventTopicOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/HiddenEventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/SingleEvent.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findAllTopics/TwoEventTopicsInReverseOrder.csv
=> [FEATURE] Add `EventRepository::findAllTopics()`

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/DeletedEventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/EventDate.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/EventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/EventTopicOnPage.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/HiddenEventTopic.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/SingleEvent.csv, Tests/Functional/Domain/Repository/Event/Fixtures/findTopicsByUids/TwoEventTopicsInReverseOrder.csv, phpstan-baseline.neon
=> [FEATURE] Add `EventRepository::findTopicsByUids()`

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php
=> [TASK] Rename an internal controller method

Tests/Functional/Controller/FrontEndEditorControllerTest.php
=> [TASK] Rename test helper methods and improve type annotations

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Configuration/TCA/tx_seminars_seminars.php, Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Private/Templates/FrontEndEditor/EditEventDate.html, Resources/Private/Templates/FrontEndEditor/Index.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventFromDifferentOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventWithOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventWithOwnerAndAllAssociations.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventWithOwnerWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventWithoutOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithDifferentPid.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithOwnerWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithTopicAndOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEvent.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEventWithOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEventWithTopicAndSlug.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEventWithUidOnlySlug.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, ext_localconf.php
=> [FEATURE] Allow editing existing event dates in the FE editor

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/FrontEndEditor/Form.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/EventWithOwnerAndTopic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editEventDateAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/editSingleEventAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newSingleEventAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEventWithTopic.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php
=> [FEATURE] Allow editing an event date topic in the FE editor

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
=> [TASK] Convert the topic finding methods to return arrays

CHANGELOG.md, Classes/Domain/Model/Event/NullEventTopic.php, Tests/Unit/Domain/Model/Event/NullEventTopicTest.php
=> [FEATURE] Add a `NullEventTopic`

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Templates/FrontEndEditor/NewEventDate.html, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventDate.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithOfflineRegistrations.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithPid.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithTopic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/CreatedEventWithTopicAndSlug.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/createEventDateAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newEventDateAction/AuxiliaryRecords.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newEventDateAction/FrontEndUserWithDefaultOrganizer.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/newEventDateAction/Topic.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/EventWithTopicAndOwner.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateEventDateAction/UpdatedEventWithTopicAndSlug.csv, Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateSingleEventAction/EventWithOwner.csv, Tests/Functional/Controller/FrontEndEditorControllerTest.php, ext_localconf.php
=> [FEATURE] Allow creating event date records in the FE editor

Configuration/FlexForms/FrontEndEditor.xml, Resources/Private/Language/locallang.xlf
This is a pre-patch to adding a configuration option for the type of event to create (single event or event date).
Part of #4282
=> [TASK] Change a flexforms label of the FE editor content element

CHANGELOG.md, Classes/Form/Element/EventDetailsElement.php, Configuration/TCA/tx_seminars_attendances.php, Tests/Functional/Form/Element/EventDetailsElementTest.php, Tests/Functional/Form/Element/Fixtures/AdminBackEndUser.csv, ext_localconf.php, phpstan-baseline.neon
This allows the BE user to easier recognize the event to which a registration belongs.
=> [FEATURE] Show event details in the registration TCEforms

CHANGELOG.md, Tests/Functional/Form/Element/EventDetailsElementTest.php
=> [BUGFIX] Make a test fixture 12LTS-compatible

CHANGELOG.md, Classes/Service/RegistrationProcessor.php, Tests/Functional/OldModel/LegacyRegistrationTest.php, Tests/Functional/Service/RegistrationProcessorTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
=> [BUGFIX] Fix crash in the registration form

CHANGELOG.md, Documentation/Reference/EventsHooks/Events/AfterSlugGeneratedEvent.rst, Documentation/Reference/EventsHooks/Events/Index.rst, Documentation/Reference/EventsHooks/Events/_AfterSlugGeneratedEvent/_Services.yaml, Documentation/Reference/EventsHooks/Events/_AfterSlugGeneratedEvent/_SlugGeneratorEventListener.php, Documentation/Reference/EventsHooks/Hooks.rst, Documentation/Reference/EventsHooks/Index.rst, Documentation/Reference/Index.rst
=> [FEATURE] Document the PSR-14 event for slug generation

CHANGELOG.md, Resources/Private/Language/locallang_db.xlf
=> [TASK] Change label for TCEforms billing tab of registrations

CHANGELOG.md, Classes/Domain/Model/Registration/BillingAddressTrait.php, Configuration/TCA/tx_seminars_attendances.php, Resources/Private/Templates/EventRegistration/New.html
This ensures that the billing address fields can be transmitted to accounting systems like Collmex.
=> [TASK] Reduce the length of the billing address fields

CHANGELOG.md, Resources/Private/Templates/EventRegistration/New.html
- full name
- street address
- ZIP code
- city
- email address
=> [TASK] Make some billing address fields required in the FE

CHANGELOG.md, Documentation/Installation/Upgrading.rst
=> [DOCS] Document the impact of removig the billing address field

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_speakers.php
This is the 5.x backport of #4536.
=> [BUGFIX] Validate email fields in the BE as emails

CHANGELOG.md, Resources/Private/Templates/EventRegistration/New.html
Some invoices will have only the company in the billing address.
So only the street address, ZIP code, city and email address should be required.
[ci skip]
=> [TASK] Do not make the name in the billing address required
