- .travis.yml
- CHANGELOG.md
- composer.json
This fixes the TYPO3 installation process using Composer on Travis
both for 7.6 as well as 8.7.
> [BUGFIX] Require typo3/minimal for installing TYPO3

- CHANGELOG.md
- Classes/Model/Event.php
- Classes/Service/RegistrationManager.php
- Configuration/TCA/tx_seminars_seminars.php
- Configuration/TypoScript/setup.txt
- Documentation/DE/Referenz/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Documentation/EN/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Resources/Private/Language/de.locallang_db.xlf
- Resources/Private/Language/locallang_db.xlf
- Tests/Unit/Model/EventTest.php
- Tests/Unit/Service/RegistrationManagerTest.php
- ext_tables.sql
Without the time zone information, the dates in the iCal files will be off
by the offset to UTC.
Fixes #32
> [BUGFIX] Provide time zone information in the iCal files

- CHANGELOG.md
- Tests/Unit/BackEnd/AbstractEventMailFormTest.php
- Tests/Unit/BackEnd/CancelEventMailFormTest.php
- Tests/Unit/BackEnd/ConfirmEventMailFormTest.php
- Tests/Unit/BackEnd/EventsListTest.php
- Tests/Unit/BackEnd/GeneralEventMailFormTest.php
- Tests/Unit/BackEnd/ModuleTest.php
- Tests/Unit/BackEnd/OrganizersListTest.php
- Tests/Unit/BackEnd/RegistrationsListTest.php
- Tests/Unit/BackEnd/SpeakersListTest.php
The tests will be reactivated with the new BE module.
> [TASK] Skip the tests for the old BE module in TYPO3 >= 8.7

- CHANGELOG.md
- Classes/Hooks/RegistrationEmailHookInterface.php
- Classes/Interface/Hook/Registration.php
- Classes/Service/RegistrationManager.php
- Documentation/DE/Referenz/Hooks/Index.rst
- Documentation/EN/Reference/Hooks/Index.rst
- Tests/Unit/Service/RegistrationManagerTest.php
This change adds the Mail object to the hook so the Mail object can be modified without using XClasses.
Because of that interface it would be breaking. I could also add another hook containing the mail object and let this hook untouched if you don´t want a breaking change.
> [FEATURE] Add new registrationEmailHook

- CHANGELOG.md
- Configuration/TypoScript/Page.txt
- Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Fix the async and defer attributes.
Also remove the "part of the TYPO3 CMS" header from the JavaScript file.
> [BUGFIX] Fix the inclusion of the JavaScript file

- CHANGELOG.md
- Classes/OldModel/Abstract.php
- Classes/OldModel/Registration.php
- Tests/Functional/OldModel/SpeakerTest.php
- Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
- Tests/LegacyUnit/OldModel/AbstractTest.php
- Tests/LegacyUnit/OldModel/CategoryTest.php
Also refactor the AbstractOldModel a bit.
Also convert the Category and SpeakerTests accordingly.
> [TASK] Allow testing the old models with fewer DB accesses

- CHANGELOG.md
- Tests/Functional/Mapper/RegistrationTest.php
- Tests/Functional/OldModel/SpeakerTest.php
The testing framework will flush the DB tables anyway, so there is no
need to do that ourselves.
This should improve test performance a bit.
> [TASK] Skip the DB cleanup in the new functional tests

- CHANGELOG.md
- Classes/EmailSalutation.php
- Documentation/EN/Reference/Hooks/Index.rst
- Tests/LegacyUnit/Service/EMailSalutationTest.php
Currently it isn´t possible to get the user object inside the
modifySalution hook. The change shouldn´t be breaking.
> [TASK] Pass user object in modifySalutation hook

- CHANGELOG.md
- composer.json
Also drop the dependency on `roave/security-advisories` as this dependency
should be in the distribution, not the individual extensions.
> [BUGFIX] Pin the dev dependency versions

- Classes/BagBuilder/Event.php
- Classes/FrontEnd/DefaultController.php
- Classes/OldModel/Event.php
- Classes/OldModel/Registration.php
- properly indent fall-through comments
- remove the `break` from the default case
> [CLEANUP] Clean up switch/case constructs

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
This prevents test failures with strict mode.
> [BUGFIX] Use real records in the FE editor tests

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
- Tests/LegacyUnit/Service/Fixtures/TestingRegistrationManager.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
This will help static code analysis and hopelfully also improve test
perfomance.
> [TASK] Avoid using eval in the tests

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/Hooks/Interfaces/SeminarSingleView.php
- Classes/Interface/Hook/EventSingleView.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
As requested by @oliverklee in #241
There is these open questions:
- Is the interface feature complete? Or add methods for next day events list / other dates list, too?
- Should I deprecate the old hook? If so, like for new RegistrationEmailHookInterface?
As a side note: One of the CsvDownloaderTests failed when I had an error (threw an unexpected Exception in GeneralUtility) in the test I added:
```
There was 1 failure:
1) Tx_Seminars_Tests_Unit_Csv_CsvDownloaderTest::createAndOutputListOfRegistrationsForInexistentEventUidReturn404
Failed asserting that 'Content-disposition: attachment; filename=' contains "404".
/home/michael/MXP/ext-seminars/Tests/LegacyUnit/Csv/CsvDownloaderTest.php:823
...
```
Should I open an issue for that? Or will the test be re-implemented anyways soon?
> [FEATURE] Add new seminar single view hook

- CHANGELOG.md
- Classes/OldModel/AbstractModel.php
This avoids problems when persisting models with the ConnectionPool.
> [BUGFIX] Internally store boolean properties as integers

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/Hooks/Interfaces/SeminarListView.php
- Classes/Interface/Hook/EventListView.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
As requested by @oliverklee in #241
- Deprecates Tx_Seminars_Interface_Hook_EventListView
- Adds hooks to bag builders, table header, list rows and table footer
- Tests for all hooks
I will add the changelog entry when this is almost finished (to prevent conflicts when rebasing).
> [FEATURE] Add seminar list view hooks

- .gitattributes
- .gitignore
- CHANGELOG.md
- composer.json
- docker-compose.yml
This is the official way to [test rendering the docs using docker-compose](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Index.html).
I found this being more convenient than using the image directly. It also should be more portable to Windows than creating a shell alias as the [official site suggests](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Quickstart.html#commands-to-render-documentation).
> [FEATURE] Add composer command to render the documentation using docker-compose

- CHANGELOG.md
- Documentation/DE/Referenz/Hooks/Index.rst
- Documentation/EN/Reference/Hooks/Index.rst
- fix double backslashes in namespaces
- use two colons in `::class`
Fixes #435
> [BUGFIX] Fix PHP syntax errors in the documentation

- CHANGELOG.md
- Classes/Hooks/HookProvider.php
- Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsArray.php
- Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsArray2.php
- Tests/Unit/Hooks/Fixtures/TestingHookInterfaceReturnsArray.php
- Tests/Unit/Hooks/HookProviderTest.php
Split #443 as requested by @oliverklee.
I chose a merged array to be able to return complex data sets, as it is the most flexible solution I could think of. All hooks registered get the same parameters, and the resulting arrays are merged and returned to the caller.
I will add the CHANGELOG line when it is ready to merge.
> [FEATURE] Enhance hook provider

- CHANGELOG.md
- Tests/Functional/Hooks/DataHandlerHookTest.php
- Tests/Functional/Hooks/Fixtures/DataMapperHook.xml
The DataMapper should set the registration deadline to zero if it
is later than the begin date.
Part of #450
> [FEATURE] Add tests for registration deadline sanitization

- CHANGELOG.md
- Tests/Functional/Hooks/DataHandlerHookTest.php
- Tests/Functional/Hooks/Fixtures/DataMapperHook.xml
The DataMapper should set the early-bird deadline to zero if it
is later than the begin date or the registration deadline.
> [FEATURE] Add tests for early-bird deadline sanitization

- CHANGELOG.md
- Configuration/TypoScript/Config.txt
- composer.json
- ext_emconf.php
This is the 2.2.x backport of #467.
Also update the oelib dependency.
Fixes #464
Fixes #465
> [BUGFIX] Update the locations of the mkforms JavaScript includes

- CHANGELOG.md
- Classes/OldModel/Event.php
- Classes/OldModel/Registration.php
- Tests/LegacyUnit/OldModel/EventTest.php
- Tests/LegacyUnit/OldModel/RegistrationTest.php
Some labels already have a colon that needs to be removed before a colon
is appended in order to avoid double colons.
> [BUGFIX] Avoid double colons for labels in organizer notification emails

- CHANGELOG.md
- Classes/OldModel/Event.php
- Classes/OldModel/Registration.php
- Tests/LegacyUnit/OldModel/EventTest.php
- Tests/LegacyUnit/OldModel/RegistrationTest.php
Some labels already have a colon that needs to be removed before a colon
is appended in order to avoid double colons.
> [BUGFIX] Avoid double colons for labels in organizer notification email

- Documentation/DE/Installation/DieErweiterungInstallieren/Index.rst
- Documentation/EN/Installation/InstallingTheExtension/Index.rst
The extension `cal_ts_service` is outdated (only for TYPO3 <= 7) and the extension `seminarscalredirect` is marked as abandoned in TER, so I think this sentence should be removed from the docs.
> [TASK] Remove outdated sentence from the installation section in the docs

- CHANGELOG.md
- Tests/Functional/OldModel/EventTest.php
- Tests/Functional/OldModel/Fixtures/Events.xml
- Tests/Functional/OldModel/Fixtures/Events/Checkboxes.xml
This should help keep the fixture files for the functional tests
shorter and speed up the tests.
> [TASK] Use separate fixture file tor the event checkboxes tests

- CHANGELOG.md
- composer.json
We cannot support PHP 7.0 and PHPUnit 7 at the same time due to the
required `void` return type declarations for `setUp` and `tearDown`
in PHPUnit 7.
> [BUGFIX] Downgrade to PHPUnit 6.5

- CHANGELOG.md
- Classes/FrontEnd/RegistrationForm.php
- Tests/Unit/FrontEnd/RegistrationFormTest.php
This property has been deprecated in TYPO3 9.
Fixes #522
Part of #521
> [BUGFIX] Stop accessing FrontEndController::loginUser in TYPO3 9

- CHANGELOG.md
- Classes/OldModel/Event.php
- Tests/Unit/OldModel/EventTest.php
This is a follow-up to #531.
Also add `Event::setTopic`.
> [BUGFIX] Check the dates for checkboxes, not the topics

- CHANGELOG.md
- Classes/OldModel/Event.php
- Classes/OldModel/Registration.php
`str_pad` does not work correctly with multibyte characters.
> [BUGFIX] Fix the alignment of labels with umlauts in the emails

- CHANGELOG.md
- Classes/Hooks/Interfaces/DateTimeSpan.php
- Classes/Hooks/Interfaces/TimeSpan.php
- Classes/OldModel/AbstractTimeSpan.php
- Documentation/DE/Referenz/Hooks/Index.rst
- Documentation/EN/Reference/Hooks/Index.rst
- Tests/Functional/OldModel/AbstractTimeSpanTest.php
The first hook to utilize the modified values hook.
I called the interface `TimeSpan` in accordance to your `AbstractTimeSpan` class. But I would also call it `DateTimeSpan` to better reflect that is used for both.
> [FEATURE] Add time span hooks, tests and docs

- CHANGELOG.md
- Classes/Csv/AbstractRegistrationListView.php
- Classes/Hooks/Interfaces/RegistrationListCsv.php
- Documentation/DE/Referenz/Hooks/Index.rst
- Documentation/EN/Reference/Hooks/Index.rst
- Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
Includes the instance flushing from Tx_Seminars_Tests_Unit_BackEnd_RegistrationsListTest (required for the legacy unit tests).
> [FEATURE] Add new registration list CSV hook

- CHANGELOG.md
- Configuration/php-cs-fixer.php
We are not using PSR-4 yet, and so we must not automatically convert
the class names accordingly in the CI builds.
This fixes the CI build with the latest version of the
PHP-CS-Fixer.
> [BUGFIX] Stop converting class names to PSR-4

- CHANGELOG.md
- Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
This fixes problems with return type declarations in oelib 3.2.
> [BUGFIX] Stop using event model prophecies in the scheduler task tests

- .github/workflows/release.yml
This makes sure we reap the performance and traffic benefits
of Composer V2.
> [TASK] Explicitly use Composer 2 in the release workflow

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/CategoryListTest.php
- Tests/LegacyUnit/OldModel/EventTest.php
These tests failed due to recent (correct) changes in oelib.
For seminars main, the tests have been adapted. For the maintenance
branch, we remove these tests to get the build to green in the meantime
so we can have a release.
> [BUGFIX] Drop some outdated tests

- .github/workflows/ci.yml
This allows us to receive feedback for which specific PHP
or TYPO3 versions we have broken something with a change.
Fixes #684
> [TASK] Set fail-fast: false in the CI configuration

- CHANGELOG.md
- Documentation/DE/Installation/DieErweiterungInstallieren/Index.rst
- Documentation/EN/Installation/InstallingTheExtension/Index.rst
The "Use the page browser" extension setting has been removed some
time ago.
Fixes #752
> [CLEANUP] Drop reference to a removed feature from the manual

- .gitattributes
- .github/workflows/release.yml
- CHANGELOG.md
- Resources/Private/Patches/testing-framework/faster-truncate.diff
- composer.json
We will be able to drop this change once the nimut testing framework
has adopted this change.
> [TASK] Truncate changed tables only for functional tests

- CHANGELOG.md
- Classes/BackEnd/TimeSlotWizard.php
- Classes/Hooks/DataHandlerHook.php
- ext_localconf.php
As this feature works in 9.5 after all, we can keep it for now.
> [FOLLOWUP] De-deprecate the time slot wizard

- CHANGELOG.md
- composer.json
We are using PDO classes.
Fixes #833
> [BUGFIX] Require `ext-pdo` in the `composer.json`

- Tests/Functional/Mapper/BackEndUserMapperTest.php
With oelib 3.6.1, this is no longer required.
FIxes #821
> [CLEANUP] Stop mocking the BE user in the BE user mapper test

- CHANGELOG.md
- Classes/BackEnd/AbstractEventMailForm.php
- Classes/BackEnd/CancelEventMailForm.php
- Classes/BackEnd/ConfirmEventMailForm.php
- Classes/BackEnd/GeneralEventMailForm.php
- Classes/Interfaces/Hook/BackEndModule.php
- Classes/OldModel/Event.php
- Documentation/EN/Reference/Hooks/Index.rst
- Tests/Functional/BackEnd/AbstractEventMailFormTest.php
- Tests/Functional/BackEnd/CancelEventMailFormTest.php
- Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
- Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
- Tests/Functional/BackEnd/GeneralEventMailFormTest.php
- Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
- phpstan-baseline.neon
> [CLEANUP] Switch emailing in the AbstractEventMailForm from oelib mail functions to the Core SwiftMailer

- CHANGELOG.md
- composer.json
This allows the tests to be run that require more fields
for the FE users.
Fixes #922
> [TASK] Add sr_feuser_register as a dev dependency

- CHANGELOG.md
- Classes/ConfigCheck.php
- Classes/Configuration/AbstractFrontEndConfigurationCheck.php
- Classes/Configuration/ListViewConfigurationCheck.php
- Classes/Configuration/SharedConfigurationCheck.php
- Classes/Configuration/SingleViewConfigurationCheck.php
- Classes/FrontEnd/DefaultController.php
- Tests/Functional/Configuration/ListViewConfigurationCheckTest.php
- Tests/Unit/Configuration/ListViewConfigurationCheckTest.php
Also properly encode quotes in the warning message HTML.
Also improve the code formatting to avoid a perpetual
tug-of-war between PHP-CS-Fixer and the PhpStorm code formatter.
Part of #236
> [TASK] Migrate the single view configuration check

- Classes/FrontEnd/DefaultController.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
This avoids some exceptions when configuring the extension.
> [BUGFIX] Do not continue after list view configuration problems

- CHANGELOG.md
- Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
- Tests/LegacyUnit/FrontEnd/CategoryListTest.php
- Tests/LegacyUnit/FrontEnd/CountdownTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
- Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
This make the tests compatible with the immutable `ConfigurationProxy`
from oelib 4.0.
> [BUGFIX] Use the dummy configuration in the tests for extension config

- CHANGELOG.md
- Classes/Mapper/FrontEndUser.php
- Tests/Functional/Mapper/FrontEndUserMapperTest.php
- phpstan-baseline.neon
This method is needed because we have switched from the oelib mapper
to the seminars mapper, and it is called in the registration manager.
Fixes #973
> [BUGFIX] Copy `FrontEndUserMapper::findByUserName` from oelib

- CHANGELOG.md
- Classes/Mapper/EventMapper.php
- Classes/Mapper/FrontEndUserGroup.php
- Classes/OldModel/LegacyEvent.php
- Tests/LegacyUnit/Mapper/EventMapperTest.php
- Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
This prevents problems when we namespace the seminars user (group)
mappers.
> [TASK] Use aliases for the oelib user (group) mappers

- CHANGELOG.md
- Classes/FrontEnd/EventEditor.php
- Classes/Model/FrontEndUser.php
- Classes/Model/FrontEndUserGroup.php
- Classes/OldModel/LegacyEvent.php
- Classes/Service/RegistrationManager.php
- Tests/LegacyUnit/Mapper/EventMapperTest.php
- Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
- Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
- Tests/LegacyUnit/Model/FrontEndUserTest.php
- Tests/LegacyUnit/Model/RegistrationTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
This prevents problems when we namespace the seminars user (group)
models.
> [TASK] Use aliases for the oelib user (group) models

- Classes/SchedulerTasks/MailNotifierConfiguration.php
- Tests/Unit/SchedulerTasks/MailNotifierConfigurationTest.php
This class was introduced in TYPO3 9LTS, and using it allows use
to remove some of our own code.
Fixes #990
> [CLEANUP] Use the new `AbstractAdditionalFieldProvider` class

- CHANGELOG.md
- Classes/Service/SingleViewLinkBuilder.php
Starting with TYPO3 9LTS, this method usually does not need to be
explictly called anymore.
> [TASK] Stop calling `initTemplate()` in the link builder

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/OldModel/AbstractModel.php
- Classes/OldModel/LegacyEvent.php
- Classes/OldModel/LegacySpeaker.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
This reduces dependencies on `ContentObjectRenderer` and improves
performance.
Fixes #1119
> [TASK] Stop using typolink for external links

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/EventEditorTest.php
- Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
- Tests/LegacyUnit/Service/EmailServiceTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
- phpstan-baseline.neon
This fixes those email tests in the legacy tests in V10.
Part of #1109
> [BUGFIX] Use the email abstractions in the legacy tests (part 1)

- CHANGELOG.md
- Classes/FrontEnd/AbstractEditor.php
This fixes a crash in the registration form and event editor
in TYPO3 V10.
Fixes #1188
> [BUGFIX] Create mkforms-related directories on the fly

- CHANGELOG.md
- Tests/Functional/FrontEnd/RegistrationFormTest.php
- Tests/LegacyUnit/Csv/CsvDownloaderTest.php
- Tests/LegacyUnit/FrontEnd/AbstractEditorTest.php
- Tests/LegacyUnit/FrontEnd/AbstractViewTest.php
- Tests/LegacyUnit/FrontEnd/CountdownTest.php
- Tests/LegacyUnit/FrontEnd/EventPublicationTest.php
- Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
- Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php
- Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
This helps fix link creation in the tests in V10.
Fixes #1210
> [BUGFIX] Always use a page UID for the fake FE in the tests

- CHANGELOG.md
- Configuration/FlexForms/flexforms_pi1.xml
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/dk.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/it.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Resources/Private/Language/ru.locallang.xlf
In TYPO3 10LTS and higher, file uploads without FAL are not supported
in the TCA or flexforms anymore and will lead to an exception.
Fixes #1220
> [BUGFIX] Remove the HTML template file settings from the flexforms

- composer.json
This is required for Composer 2.2.
> [BUGFIX] Explicitly allow the needed Composer plugins

- composer.json
- phpstan-baseline.neon
Also regenerate the PHPStan baseline to get rid of some warnings
which do not occur with the updated tools anymore.
> [TASK] Update the development dependencies

- .github/workflows/ci.yml
This avoids a problem with the sr_feuser_register dev dependency,
fixing the recent build breakage.
(We will be able to switch back to Composer 2 once we are using
feuserextrafields instead.)
> [BUGFIX] Use Composer 1 for the legacy tests

- CHANGELOG.md
- composer.json
Add a `prepare-release` script for Tailor.
> [BUGFIX] Keep development-only files out of the TER releases

- composer.json
This problem was fixed in Extbase 10.4.6. So we need to set this
version as minimum for TYPO3 10LTS.
> [BUGFIX] Avoid Extbase-related exception in TYPO3 10LTS

- CHANGELOG.md
- composer.json
This avoids a crash when installing the Composer packages (including
the development packages) with Composer 1 with the lowest
dependencies.
> [BUGFIX] Require `typo3/class-alias-loader` >= 1.1.0 for development

- CHANGELOG.md
- Classes/SchedulerTasks/MailNotifier.php
- Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
This removes one blocker for the upgrade to PHPUnit 8.
Fixes #1258
> [TASK] Stop using `getAccessibleMock`

- CHANGELOG.md
- composer.json
The install tool is optional for running the extension (as long
as the upgrade wizards do not get used). So add it as a suggestion
to the `composer.json`.
Also dev-require it to allow rector to parse the upgrade wizards.
> [BUGFIX] Dev-require and suggest the install tool

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/Model/EventTest.php
- Tests/LegacyUnit/Service/EmailServiceTest.php
- Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
- Tests/Unit/FrontEnd/DefaultControllerTest.php
- remove methods from partial mocks that do not exist
- fix the return types of mocked method calls
> [BUGFIX] Fix PHPUnit warnings

- CHANGELOG.md
- composer.json
This is required for V9 installations.
> [BUGFIX] Allow Composer plugins from `helhum/typo3-console-plugin`

- CHANGELOG.md
- Tests/LegacyUnit/Csv/EventListViewTest.php
- Tests/LegacyUnit/Email/SalutationTest.php
Testscases are not expected to be extended. So methods should be
`private` whenever possible.
> [CLEANUP] Avoid unnecessarily broad method visibility in tests

- CHANGELOG.md
- Tests/LegacyUnit/Csv/CsvDownloaderTest.php
This broken the fake FE in the affected testcase (and all subsequent tests)
on GitHub Actions.
> [BUGFIX] Remove a stray `backupGlobals` from a legacy test

- CHANGELOG.md
- composer.json
We should not depend on transitive dependencies.
> [BUGFIX] Make the Composer dependencies explicit

- CHANGELOG.md
- Tests/Functional/OldModel/Fixtures/SingleRootPage.xml
- Tests/Functional/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/FrontEnd/AbstractEditorTest.php
- Tests/LegacyUnit/FrontEnd/AbstractViewTest.php
- Tests/LegacyUnit/FrontEnd/CategoryListTest.php
- Tests/LegacyUnit/FrontEnd/CountdownTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/EventEditorTest.php
- Tests/LegacyUnit/FrontEnd/EventPublicationTest.php
- Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
- Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
- Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
- Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
This helps with link creation in the functional and legacy tests.
> [BUGFIX] Always set a slug for the fake homepage in the tests

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/CategoryListTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
Also make all pages subpages of the root page.
This gets more links in the legacy tests to run in V10.
Part of #1285
> [BUGFIX] Use proper slugs for pages in more legacy tests

- CHANGELOG.md
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
These tests are more of functional tests and should create real URLs.
Part of #1285
> [TASK] Stop mocking the link builder in some legacy tests

- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
This gets more links in the legacy tests to run in V10.
Fixes #1285
> [BUGFIX] Use proper slugs for pages in the legacy tests

- CHANGELOG.md
- composer.json
Suggestions in the `composer.json` do not have a version constraint.
Instead, they have a short text field.
> [CLEANUP] Remove the version constraints from the extension suggestions

- .github/workflows/ci.yml
This fixes a crash during `composer install` with TYPO3 8.7 on PHP 7.2
due to an imcompatibility in `class_alias_loader`.
> [BUGFIX] Downgrade the unit and functional tests on CI to Composer 1

- CHANGELOG.md
- Classes/FrontEnd/Editor.php
This fixes a potential crash in the FE event editor and registration
form.
Fixes #1366
> [BUGFIX] Add missing import in the FE form base class

- .github/workflows/ci.yml
The legacy tests were accidentally removed in #1388.
> [BUGFIX] Re-add the legacy tests to the CI builds

- composer.json
Without a PHP version set via `platform` in `composer.json`,
Dependabot will try to update to a version of `php-cs-fixer` that
our current PHP version does not support, which causes Dependabot
to choke.
> [BUGFIX] Configure the PHP platform for Dependabot

- CHANGELOG.md
- Tests/Functional/SchedulerTasks/MailNotifierConfigurationTest.php
- Tests/Functional/SchedulerTasks/MailNotifierTest.php
- Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
- Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
- Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
- Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
- Tests/LegacyUnit/FrontEnd/CountdownTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
- Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
- Tests/LegacyUnit/Model/AbstractTimeSpanTest.php
- Tests/LegacyUnit/Model/EventTest.php
- Tests/LegacyUnit/Model/EventTopicTest.php
- Tests/LegacyUnit/Model/FrontEndUserTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
- Tests/LegacyUnit/Service/EventStatusServiceTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
- Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
- Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
- Tests/Unit/FrontEnd/DefaultControllerTest.php
- Tests/Unit/Traits/EmailTrait.php
In many cases, PHPUnit's generics already provide all information needed
for static analysis of mocks.
Fixes #1371
> [CLEANUP] Drop redundant type annotations for mocks

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
Usually the testing framework automatically does this, but there seems to be a race condition resulting in the directory not getting consistently created.
> [BUGFIX] Always create the tests directory on CI

- .github/dependabot.yml
- composer.json
Also block PHPUnit updates by Dependabot as it cannot handle multi-version dependencies.
> [TASK] Update PHPUnit

- CHANGELOG.md
- Classes/Rendering/NullRenderingContext.php
- Classes/Rendering/NullRequest.php
- Tests/Unit/Rendering/NullRenderingContextTest.php
- Tests/Unit/Rendering/NullRequestTest.php
- phpstan-baseline.neon
This is required in 11LTS.
Also make the `NullRenderingContext` final.
Fixes #1516
> [BUGFIX] Provide the `NullRenderingContext` with a request

- CHANGELOG.md
- Tests/Functional/FrontEnd/CategoryListTest.php
- Tests/Functional/FrontEnd/DefaultController/ListViewTest.php
- Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php
This is required in TYPO3 11LTS.
Fixes #1517
> [BUGFIX] Provide a `Context` for the FE in the functional tests

- .github/dependabot.yml
Dependabot will happily mangle multi-version dependencies.
> [BUGFIX] Block multi-version dependencies in Dependabot

- composer.json
This probably got lost during some cleanup.
Fixes #1587
> [BUGFIX] Also run PHPStan as part of the `ci:static` Composer script

- .github/dependabot.yml
- composer.json
This is required as long as we are using Composer 1 for some CI tasks (as version 1.2.0 required Composer 2).
Fixes #1592
> [TASK] Pin `phpstan/extension-installer` to ~1.1.0

- Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
- Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
- Tests/LegacyUnit/BackEnd/EventsListTest.php
- Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
- Tests/LegacyUnit/Fixtures/OldModel/TestingLegacyEvent.php
- Tests/LegacyUnit/FrontEnd/CountdownTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
- Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
- Tests/LegacyUnit/Mapper/EventDateMapperTest.php
- Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
- Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
- Tests/LegacyUnit/Model/EventDateTest.php
- Tests/LegacyUnit/Model/EventTest.php
- Tests/LegacyUnit/Model/EventTopicTest.php
- Tests/LegacyUnit/Model/SingleEventTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
- Tests/Unit/OldModel/LegacyEventTest.php
> [CLEANUP] Use the `EventInterface::TYPE_*` constants in the tests

- Classes/Domain/Repository/Event/EventRepository.php
- Configuration/Extbase/Persistence/Classes.php
- ext_typoscript_setup.txt
This helps communicate that this property holds only a record UID, but not actually a relation to the record.
Part of #1646
> [TASK] Rename `Event.owner` to `.ownerUid`

- Classes/Domain/Model/NullEventType.php
- Resources/Private/Partials/FrontEndEditor/Form.html
- Tests/Unit/Domain/Model/NullEventTypeTest.php
> [BUGFIX] Make the value field for `NullEventType` auto-recognizable

- CHANGELOG.md
- Classes/Domain/Model/Event/EventTopicTrait.php
- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
- Tests/Unit/Domain/Model/Event/EventTopicTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
> [BUGFIX] Allow setting `Event.eventType` to null

- CHANGELOG.md
- Classes/Domain/Model/Event/EventDateInterface.php
- Classes/Domain/Model/Event/EventDateTrait.php
- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
This method was an alias for `Event.getFirstOrganizer()`.
According to the survey, there are enough installations that have events with more than one organizer.
Fixes #1722
> [TASK] Drop the `Event.getOrganizer()` alias method

- CHANGELOG.md
- Tests/Unit/Rendering/NullRenderingContextTest.php
- Tests/Unit/Rendering/NullRequestTest.php
> [CLEANUP] Stop using Prophecy in null object tests

- Classes/Domain/Model/Event/EventDate.php
The guard clause should handle the error/special cases, not the default cases.
> [CLEANUP] Flip the guard clauses in `EventDate`

- Classes/Configuration/SharedConfigurationCheck.php
> [BUGFIX] Drop extraneous whitespace in a configuration check message

- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
`DateTime(Immutable)` instances are no models.
> [CLEANUP] Rename some variables in the tests

- .editorconfig
- CHANGELOG.md
- Configuration/TsLint.yml
- Configuration/TypoScript/Config.typoscript
- Configuration/TypoScript/CsvExport.typoscript
- Configuration/TypoScript/Forms/EventEditor.typoscript
- Configuration/TypoScript/Forms/RegistrationStep1.typoscript
- Configuration/TypoScript/Forms/RegistrationStep2.typoscript
- Configuration/TypoScript/Forms/Unregistration.typoscript
- Configuration/TypoScript/FrontEnd.typoscript
- Configuration/TypoScript/ListView.typoscript
- Configuration/TypoScript/Page.typoscript
- Configuration/TypoScript/PluginSettings.typoscript
- Configuration/TypoScript/PluginShared.typoscript
- Configuration/TypoScript/Publication.typoscript
- Configuration/TypoScript/RegistrationDigestEmail.typoscript
- Configuration/TypoScript/constants.typoscript
- ext_typoscript_setup.txt
Now we are up to date with what the Core uses again, and autoformatting the TypoScript files does not create any warnings anymore.
Also autoformat all TypoScript files.
Fixes #1870
> [BUGFIX] Update the `.editorconfig` and TypoScript lint settings

- Classes/Configuration/LegacyRegistrationConfiguration.php
- Tests/Unit/Configuration/LegacyRegistrationConfigurationTest.php
This class exists only as long as the new registration form uses the legacy email functionality.
Closes #1905
> [FEATURE] Add a `LegacyRegistrationConfiguration`

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/FrontEnd/RequirementsList.php
- Classes/Service/RegistrationManager.php
- Configuration/Services.yaml
- Tests/Functional/Service/RegistrationManagerTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
We cannot use `inject*` methods for objects that do not get injected (by DI), but merely set.
Also generally preject the `SingleViewLinkBuilder` from getting injected.
> [BUGFIX] Make the `RegistrationManager` injectable

- CHANGELOG.md
- Classes/Domain/Model/Event/EventDateInterface.php
- Classes/Domain/Model/Event/EventDateTrait.php
- Classes/Service/PriceFinder.php
- Classes/Service/RegistrationGuard.php
- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
- Tests/Functional/Service/RegistrationProcessorTest.php
- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
- Tests/Unit/Service/PriceFinderTest.php
- Tests/Unit/Service/RegistrationGuardTest.php
Extbase cannot map `DateTimeImmutable` properties (at least not in TYPO3 10 LTS), and this breaks the FE editor.
> [BUGFIX] Use `DateTime` instead of `DateTimeImmutable` in models

- CHANGELOG.md
- Resources/Private/Templates/EventRegistration/Confirm.html
- Resources/Private/Templates/EventRegistration/New.html
- Resources/Public/CSS/FrontEnd/FrontEnd.css
- add a `fieldset` with a visually-hidden `legend` around the group of fields for the separate billing address
- add a `fieldset` with a visually-hidden `legend` around the checkbox groups
- stop using `label` for text that is no real form label
- use a real table for the information on the confirmation page
- prevent selection of label texts
Fixes #1976
[ci skip]
> [TASK] Improve accessibility in the registration form

- CHANGELOG.md
- Resources/Private/Templates/EventRegistration/New.html
For assistive technology, we already have visually-hidden `legend`s for checkbox groups and should hence should hide the visible `label`s from assistive technologies in order to avoid duplicate labels.
This improves accessibility.
[ci skip]
> [TASK] Hide duplicate labels from assitive technology

- CHANGELOG.md
- Resources/Private/Templates/EventRegistration/Confirm.html
- Resources/Private/Templates/EventRegistration/New.html
Using this translator has a performance penalty which we want to avoid.
(Also, using the standard Fluid translater will make the HTML templates a bit more compact.)
[ci skip]
> [TASK] Stop using a salutation-aware translator where not necessary

- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/EventRegistration/Confirm.html
- Resources/Private/Templates/EventRegistration/New.html
Now can use the label e.g., for the full name of the billing address also for the full name of the FE user data.
[ci skip]
> [TASK] Make some registration form labels reusable

- ext_tables.sql
This undoes part of 6dc3e999740611cb662445f71d78b9ef18f3e5cd.
The DB schema change is not really required, and we should avoid DB schema changes as much as possible in minor releases. Let's have this in #2044 for seminars 5.0 instead.
> [TASK] Undo a DB schema change

- CHANGELOG.md
- Classes/Controller/EventRegistrationController.php
- Resources/Private/Templates/EventRegistration/Confirm.html
- Resources/Private/Templates/EventRegistration/New.html
- Tests/Unit/Controller/EventRegistrationControllerTest.php
This fixes a crash on the confirmation page.
Fixes #2059
> [BUGFIX] Use the first applicable price if the price field is disabled

- CHANGELOG.md
- Resources/Private/Partials/FrontEndEditor/Form.html
`propertylabelPrefix` needs to be `propertyLabelPrefix`.
[ci skip]
> [BUGFIX] Fix the camelCase of a FE editor template Fluid variable

- Resources/Private/Partials/BackEnd/EventList.html
- use a variable for the label key prefix
- add `&nbsp;` to empty table headings
[ci skip]
> [CLEANUP] Refactor the BE module Fluid template

- CHANGELOG.md
- Classes/Configuration/CsvExportConfigurationCheck.php
- Classes/Csv/CsvDownloader.php
- Classes/Csv/CsvResponse.php
- Configuration/TypoScript/PluginShared.typoscript
- Documentation/DE/Referenz/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Documentation/EN/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
The will always be UTF-8 in seminars 5.0.
Fixes #2106
[ci skip]
> [TASK] Deprecate the `charsetForCsv` setting

- CHANGELOG.md
- Classes/Controller/BackEnd/RegistrationController.php
- Resources/Private/Partials/BackEnd/EventList.html
- Resources/Private/Partials/BackEnd/RegistrationList.html
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
Also use the UID column header for both the UID as well as the icon in order to save horizontal screen space.
> [FEATURE] Display icons for registrations in the BE module

- CHANGELOG.md
- Classes/Configuration/CsvExportConfigurationCheck.php
- Classes/Csv/CsvDownloader.php
- Classes/Csv/CsvResponse.php
- Configuration/TypoScript/PluginShared.typoscript
- Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
- Tests/LegacyUnit/Csv/CsvDownloaderTest.php
- Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
- Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
- Tests/LegacyUnit/Csv/EventListViewTest.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
- Tests/Unit/Csv/CsvResponseTest.php
- phpstan-baseline.neon
Also drop the the `charsetForCsv` setting
Fixes #2107
> [TASK] Always use UTF-8 for the CSV export

- CHANGELOG.md
- Configuration/TCA/Overrides/fe_users.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TCA/Overrides/tt_content.php
- Configuration/TCA/tx_seminars_attendances.php
- Configuration/TCA/tx_seminars_categories.php
- Configuration/TCA/tx_seminars_checkboxes.php
- Configuration/TCA/tx_seminars_event_types.php
- Configuration/TCA/tx_seminars_foods.php
- Configuration/TCA/tx_seminars_lodgings.php
- Configuration/TCA/tx_seminars_organizers.php
- Configuration/TCA/tx_seminars_payment_methods.php
- Configuration/TCA/tx_seminars_seminars.php
- Configuration/TCA/tx_seminars_sites.php
- Configuration/TCA/tx_seminars_skills.php
- Configuration/TCA/tx_seminars_speakers.php
- Configuration/TCA/tx_seminars_target_groups.php
- Configuration/TCA/tx_seminars_test.php
- Configuration/TCA/tx_seminars_timeslots.php
- ext_localconf.php
- ext_tables.php
> [BUGFIX] Stop using the deprecated `TYPO3_MODE` as security gate

- CHANGELOG.md
- Configuration/TypoScript/Config.typoscript
This was last used in TYPO3 6.2.
Fixes #1876
[ci skip]
> [TASK] Drop `config.uniqueLinkVars` from the TypoScript

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Configuration/TCA/tx_seminars_attendances.php
- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
- Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithHiddenRegistrationWithZeroCounterCache.xml
- Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenRegistrationWithEvent.xml
- Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenRegistrationWithEventAndUser.xml
- Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenWaitingListRegistrationWithEvent.xml
- Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenWaitingListRegistrationWithEventAndUser.xml
- Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
- Tests/LegacyUnit/Service/RegistrationManagerTest.php
- phpstan-baseline.neon
It's helpful to hide registrations after all, e.g., when someone cancels their registration.
This reverts commit 16d76a9c0f58f025699db6f5f51db327b31ea6cc.
Closes #2195
>  [TASK] Make registrations hideable again

- CHANGELOG.md
- Tests/Functional/BackEnd/AbstractEventMailFormTest.php
- Tests/Functional/BackEnd/GeneralEventMailFormTest.php
- Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
- Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
This allows us to remove the UI of the legacy BE module email form while still using it to send emails.
Fixes #2167
> [TASK] Add dedicated tests for `GeneralEventMailForm::sendEmailToAttendees`

- CHANGELOG.md
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Resources/Private/Partials/EventTitleAndDateAndUid.html
- Resources/Private/Templates/BackEnd/Email/Compose.html
- Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
To have this localized string reusable, we should have it in a shared namespace.
Fixes #2150
[ci skip]
> [TASK] Move `plugin.eventRegistration.heading.eventTitleAndDateAndUid`

- Classes/Mapper/EventMapper.php
- Classes/OldModel/LegacyEvent.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
This counter cache is a bad architectural decision, and we should get rid of it sooner or later.
> [TASK] Use the `Event.registrations` counter cache less

- CHANGELOG.md
- Configuration/TypoScript/Content.typoscript
- Configuration/TypoScript/setup.typoscript
This extension is not maintained and used anymore.
Fixes #1874
> [TASK] Drop obsolete TypoScript related to `sb_accessiblecontent`

- CHANGELOG.md
- Configuration/TypoScript/FrontEnd.typoscript
- Configuration/TypoScript/PluginShared.typoscript
- Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/dk.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/it.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Resources/Private/Language/ru.locallang.xlf
`strftime` is deprecated, and we cannot use its format anymore.
Also, are language- and region-specific and hence should come from the locallang files, not the configuration.
Hence also add the time format to the locallang files.
Fixes #2342
> [TASK] Deprecate the `dateFormat` and `timeFormat` settings

- .github/workflows/ci.yml
The TYPO3 Console currently breaks with Composer 2.5.
> [BUGFIX] Use Composer 2.4 for the legacy tests on CI

- Classes/FrontEnd/DefaultController.php
- Classes/FrontEnd/RegistrationsList.php
The TypoScrict configuration "plugin.tx_seminars_pi1.accessToFrontEndRegistrationLists" had no effect, the default value was always used (attendees_and_managers).
The adjustment ensures that the configured value is used if the canViewRegistrationsList-function is called.
This configuration is used inside the "Event List" and the "List of Registration" plugin.
> [BUGFIX] Correct use of the configuration "accessToFrontEndRegistrationLists"

- Classes/Csv/CsvResponse.php
- Tests/Unit/Csv/CsvResponseTest.php
> [TASK] Make the file name of `csvReponse` required and non-empty

- Classes/FrontEnd/DefaultController.php
Treats settings seminarImageSingleViewWidth/seminarImageSingleViewHeight as maximum image dimensions when invoking `IMAGE` cObject rendering. The change avoids that the image ratio is violated.
Fixes: #2395
> [BUGFIX] Use seminarImageSingleViewWidth/-Height as maximum

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/OldModel/AbstractModel.php
- Classes/OldModel/LegacyEvent.php
- Classes/OldModel/LegacySpeaker.php
- Tests/Functional/OldModel/LegacyEventTest.php
- Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
- Tests/LegacyUnit/OldModel/LegacyEventTest.php
- phpstan-baseline.neon
It has turned out that some installations use internal links for speakers instead of external links. So we need to support this as well again.
This partially reverts commit 4859335c8c3468135ad2b6018c86582821e84f84.
Fixes #2441
> [BUGFIX] Fix internal links to speakers and organizers

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
> [TASK] Drop the unused `DefaultController::registrationFormHookProvider`

- Tests/Unit/Controller/EventRegistrationControllerTest.php
When testing forwards/redirects, also test that no other forward/redirect happens.
Part of #1972
> [TASK] Make the `EventRegistrationControllerTest` more strict

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Tests/Functional/Service/RegistrationManagerTest.php
- phpstan-baseline.neon
In the plain-text email, linebreaks in the organizer signatures need to stay linebreaks, while they need to be converted to `<br/>` in the HTML emails.
Fixes #2473
> [BUGFIX] Convert linebreaks in the organizer signatures in HTML email

- Classes/Service/RegistrationManager.php
- Tests/Functional/Service/RegistrationManagerTest.php
Using `<hr/>` as a separator breaks the layout.
Fixes #2486
> [BUGFIX] Do not use a footer separator in the HTML emails

- CHANGELOG.md
- Resources/Private/Templates/EventRegistration/Confirm.html
If the checkbox "I register myself" is not shown, there is no point showing the default value on the confirmation page.
Fixes #2506
> [BUGFIX] Remove unnecessary information from the confirmation page

- CHANGELOG.md
- Classes/Controller/EventRegistrationController.php
- Tests/Unit/Controller/EventRegistrationControllerTest.php
- ext_localconf.php
This allows the heading to be different for waiting list registrations.
Fixes #2492
> [BUGFIX] Make registration available in the thank-you action template

- CHANGELOG.md
- Classes/Seo/SlugGenerator.php
- Configuration/TCA/tx_seminars_seminars.php
- Tests/Functional/Seo/SlugGeneratorTest.php
- Tests/Functional/UpgradeWizards/GenerateEventSlugsUpgradeWizardTest.php
- Tests/Unit/Seo/SlugGeneratorTest.php
The UID does not need to be part of the slug to make the slug unique as TYPO3 already ensures that the slug is unique by appending a number.
Fixes #2531
Fixes #2533
> [BUGFIX] Also create slugs for new records

- CHANGELOG.md
- Configuration/TCA/tx_seminars_seminars.php
> [BUGFIX] Add a maximum length for the seminar title in the TCA

- CHANGELOG.md
- Classes/Seo/SlugGenerator.php
- Tests/Functional/Seo/Fixtures/EventDateWithHiddenTopic.xml
- Tests/Functional/Seo/Fixtures/EventDateWithTimedTopic.xml
- Tests/Functional/Seo/SlugGeneratorTest.php
We want to be able to create a slug in more cases in order to avoid errors in the FE due to a missing slug.
Part of #2540
> [BUGFIX] Also create slugs if the related topic is hidden or timed

- CHANGELOG.md
- Configuration/TCA/tx_seminars_seminars.php
- Resources/Private/Language/de.locallang_db.xlf
- Resources/Private/Language/dk.locallang_db.xlf
- Resources/Private/Language/fr.locallang_db.xlf
- Resources/Private/Language/it.locallang_db.xlf
- Resources/Private/Language/locallang_db.xlf
- Resources/Private/Language/nl.locallang_db.xlf
- Resources/Private/Language/ru.locallang_db.xlf
This is required for the event type to get included in the slug calculation.
Part of #2536
> [TASK] Make the object type for events a drop-down

- CHANGELOG.md
- Classes/UpgradeWizards/SeparateBillingAddressUpgradeWizard.php
- Tests/Unit/UpgradeWizards/SeparateBillingAddressUpgradeWizardTest.php
If new registrations have been created/imported, they should get fixed as well.
As the legacy registration form does not exist anymore, this is an rare edge case and hence does not count as a real bugfix for real-world bugs.
> [TASK] Make the upgrade wizard for the billing address repeatable

- Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php
The wizard might still come in handy, e.g., when event records get imported.
[ci skip]
Fixes #2567
> [TASK] Do not deprecate the `GenerateEventSlugsUpgradeWizard`

- CHANGELOG.md
- Classes/Seo/Event/AfterSlugGeneratedEvent.php
- Classes/Seo/SlugContext.php
- Classes/Seo/SlugGenerator.php
- Tests/Functional/Seo/SlugGeneratorTest.php
Event listeners need to have access to the raw slugified title to work with. (The real current slug is also provided.)
Fixes #2610
> [BUGFIX] Provide non-suffixed slugified title to `AfterSlugGeneratedEvent`

- CHANGELOG.md
- Classes/Hooks/DataHandlerHook.php
- Classes/Seo/SlugGenerator.php
- Classes/UpgradeWizards/GenerateEventSlugsUpgradeWizard.php
- Tests/Functional/Seo/SlugGeneratorTest.php
- Tests/Unit/Seo/SlugGeneratorTest.php
Classes referenced in the TCA cannot have constructor injection as they are instantiated using `GeneralUtility::makeInstance`.
Fixes #2611
> [BUGFIX] Fix crash when editing an event in the BE

- CHANGELOG.md
- Classes/Seo/SlugGenerator.php
- Tests/Functional/Seo/SlugGeneratorTest.php
When the slug generator makes a slug unique, the new slug should be allowed to be identical to the current slug.
Fixes #2613
> [BUGFIX] Allow keeping an existing slugs when re-generating it

- Classes/Controller/BackEnd/RegistrationController.php
- Resources/Private/Partials/BackEnd/EventList.html
- Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
- phpstan-baseline.neon
This allows handling hidden events as well.
This is a pre-patch to #2653.
> [TASK] Switch the BE module to use event UIDs instead of models.

- CHANGELOG.md
- Classes/Rendering/NullRenderingContext.php
Fluid 2.10.0 introduced two new methods to `RenderingContextInterface` which we need to implement.
Fixes #2686
> [BUGFIX] Fix compatibility with `typo3fluid/fluid` 2.10.0

- Tests/LegacyUnit/PlaceholderTest.php
This will allow us to migrate the real legacy unit tests without having to remove the infrastructure in the same step.
> [TASK] Add placeholder legacy unit test

- CHANGELOG.md
- Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Now the event list selector widget (the last place still using jQuery) is VanillaJS instead.
Fixes #246
> [TASK] Do not require jQuery anymore

- CHANGELOG.md
- Resources/Private/Partials/BackEnd/RegistrationList.html
Hiding registration records is broken as a concept and creates all kinds of problems. We should not exacerbate this by providing a nice UI fot it.
This reverts commit f3676f26a039f8d5c378adcc7e54390d4b3e3010.
> [TASK] Remove the button for (un-)hiding registrations

- CHANGELOG.md
- composer.json
Require a version of `webmozart/assert` that fixes those warnings.
> [BUGFIX] Avoid warnings in the tests with PHP 8.3

- CHANGELOG.md
- Classes/SchedulerTasks/MailNotifier.php
- phpstan-baseline.neon
> [BUGFIX] Avoid usage of the deprecated `strftime` in `MailNotifier`

- CHANGELOG.md
- Tests/LegacyFunctional/FrontEnd/SelectorWidgetTest.php
- Tests/LegacyFunctional/Service/RegistrationManagerTest.php
- Tests/Unit/Traits/EmailTrait.php
> [TASK] Stop using the deprecated `Mock::setMethods()`

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
Instead of removing these method, the `RegistratonManager` will be completely removed at some time.
Fixes #2790
> [TASK] De-deprecate the singleton-related `RegistrationManager` methods

- Tests/Unit/OldModel/LegacyRegistrationTest.php
Here, we should rely on the (already tested) behavior of oelib.
Fixes #2848
> [TASK] Drop an overly specific test

- Tests/Functional/BackEnd/Fixtures/Records.xml
The real name of a FE user should be in the `name' field, not in the `username' field.
> [BUGFIX] Fix some nonsensical test data

- CHANGELOG.md
- Tests/LegacyFunctional/Mapper/EventMapperTest.php
- Tests/LegacyFunctional/Service/EventStatusServiceTest.php
Now that we have switched to the TYPO3 testing framework, this is no longer necessary.
> [TASK] Avoid using the deprecated mapper testing mode

- Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php
- Tests/LegacyFunctional/FrontEnd/RegistrationsListTest.php
- Tests/LegacyFunctional/Service/RegistrationManagerTest.php
`TestingFramework::isLoggedIn()` is deprecated and should be avoided.
> [BUGFIX] Use `Context` for login checks in the tests

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- Classes/OldModel/LegacyEvent.php
- Classes/SchedulerTasks/MailNotifier.php
- Classes/Service/RegistrationManager.php
- phpstan-baseline.neon
This allows us to avoid using the deprecated oelib login managers.
> [BUGFIX] Use the TYPO3 `Context` to check for logins

- CHANGELOG.md
- Classes/OldModel/AbstractModel.php
- Tests/Functional/OldModel/LegacyRegistrationTest.php
- Tests/LegacyFunctional/Bag/AbstractBagTest.php
- Tests/LegacyFunctional/Bag/CategoryBagTest.php
- Tests/LegacyFunctional/Bag/EventBagTest.php
- Tests/LegacyFunctional/Bag/OrganizerBagTest.php
- Tests/LegacyFunctional/BagBuilder/AbstractBagBuilderTest.php
- Tests/LegacyFunctional/OldModel/LegacyRegistrationTest.php
This removes usage of deprecated oelib functionality.
> [TASK] Stop explicitly tracking dummy records in the tests

- CHANGELOG.md
- Classes/Templating/TemplateHelper.php
> [BUGFIX] Avoid accessing the deprecated `TYPO3_MODE` constant

- CHANGELOG.md
- Classes/Controller/BackEnd/RegistrationController.php
- Classes/Service/EventStatisticsCalculator.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
- Tests/Unit/Service/EventStatisticsCalculatorTest.php
Some organizers manually close registration for an event when a certain number of registrations has been reached, and some organizers close the waiting list when it's getting too full.
In those cases, it should still be possible to see both the regular registrations as well as the waiting list registrations in the BE module.
Fixes #2654
> [BUGFIX] Display registration statistics in the BE in all cases

- CHANGELOG.md
- Resources/Private/Templates/BackEnd/Module/Overview.html
Also move the flash message about selecting a folder above the Events headline.
Fixes #2910
> [TASK] Use fewer flash messages in the backend module

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
This allows us to see (and fail on) PHP warnings and notices.
Fixes #2929
> [TASK] Use the development PHP INI file on CI

- CHANGELOG.md
- Classes/SchedulerTasks/RegistrationDigest.php
- Tests/LegacyFunctional/SchedulerTasks/RegistrationDigestTest.php
> [BUGFIX] Avoid using the deprecated `ObjectManager` for `StandAloneView`

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Tests/LegacyFunctional/Service/RegistrationManagerTest.php
- Tests/Unit/Service/RegistrationManagerTest.php
> [BUGFIX] Avoid deprecated HTTP functions in `RegistrationsManager`

- CHANGELOG.md
- Classes/SchedulerTasks/MailNotifier.php
- phpstan-baseline.neon
> [BUGFIX] Avoid usage of deprecated `strftime` in `MailNotifier`

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
Instead of removing these method, the `RegistrationManager` will be completely removed at some time.
Fixes #2790
> [TASK] De-deprecate singleton-related `RegistrationManager` methods

- .github/workflows/ci.yml
This speeds up the CI jobs while ensuring we don't break anything.
> [TASK] Reduce the CI test run to the version edges

- Classes/Domain/Repository/Event/EventRepository.php
- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
- Tests/Functional/Domain/Repository/Event/Fixtures/BackEndUser.csv
- Tests/Functional/Domain/Repository/Event/Fixtures/DeletedHiddenSingleEventOnPage.csv
- Tests/Functional/Domain/Repository/Event/Fixtures/DeletedSingleEventOnPage.csv
- Tests/Functional/Domain/Repository/Event/Fixtures/HiddenSingleEventOnPage.csv
- Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventOnPage.csv
- phpstan-baseline.neon
This allows cache clearing.
Fixes #3140
Closes #2915
> [TASK] Switch (un)hiding events to using the `DataHandler`

- CHANGELOG.md
- Classes/Controller/BackEnd/EventController.php
- Classes/Domain/Repository/Event/EventRepository.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
Now that we're using the `DataHandler`, we can rely on it doing the permission check for the current BE user.
This reverts commit 45a726d85ca01ef4baca886bb8ef423f133dcbf6.
> [TASK] Drop duplicate permissions check when (un)hiding events

- CHANGELOG.md
- Classes/Rendering/NullRenderingContext.php
- Tests/Unit/Rendering/NullRenderingContextTest.php
This is the 5.5.x backport of #3158.
Fixes #3152
> [BUGFIX] Avoid crash with `typo3fluid/fluid` 2.14.0

- CHANGELOG.md
- Classes/Controller/BackEnd/EmailController.php
- Tests/Unit/Controller/BackEnd/EmailControllerTest.php
This is the 5.5.x backport of #2968.
Fixes #3153
> [BUGFIX] Redirect to events list after sending email in the BE module

- CHANGELOG.md
- Classes/Templating/TemplateHelper.php
- phpstan-baseline.neon
> [BUGFIX] Avoid usage of `empty` in `TemplateHelper`

- CHANGELOG.md
- Configuration/TypoScript/FrontEnd.typoscript
The option `loadJsFramework` is a left-over from FORMidable, which we're not using anymore.
Fixes #3292
[ci skip]
> [TASK] Drop obsolete TypoScript option

- composer.json
This is necessary due to a bug in static_info_tables.
> [BUGFIX] Add `typo3/cms-extensionmanager` as a dev dependency

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- .github/workflows/release.yml
This avoids runaway jobs eating into the runners budget.
> [TASK] Limit the runtime of the CI jobs

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Tests/Functional/Service/RegistrationManagerTest.php
A subtitle is not description, and having it in the calendar invite does not make any sense.
> [TASK] Do not use the event subtitle as calendar invite description

- .github/dependabot.yml
- composer.json
This package no longer is a dependency of ours.
> [CLEANUP] Drop residual entries for `helhum/typo3-console`

- CHANGELOG.md
- Classes/Model/Event.php
> [TASK] Deprecate `Event.getRegisteredSeats/.hasEnoughRegistrations()`

- CHANGELOG.md
- Classes/Model/Event.php
- `getAttendeeNames`
- `getRegistrationsAfterLastDigest`
- `getAttendeeNamesAfterLastDigest`
- `getVacancies`
- `hasVacancies`
- `isFull`
Fixes #3421
[ci skip]
> [TASK] Deprecate some functions from the old `Event` model

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- `allowsRegistrationByDate`
- `allowsRegistrationBySeats`
- `canRegisterIfLoggedInMessage`
- `canRegisterIfLoggedIn`
- `couldThisUserRegister`
- `existsSeminar`
- `existsSeminarMessage`
- `isUserRegistered`
- `registrationHasStarted`
Fixes #3423
Fixes #3428
Fixes #3431
Fixes #3434
Fixes #3437
> [TASK] Deprecate some `RegistrationManager` methods

- .github/dependabot.yml
- composer.json
This paves to way to Symfony 6 and 7.
> [TASK] Allow higher versions of `helmich/typo3-typoscript-lint`

- Tests/Unit/ViewHelpers/RichTextViewHelperTest.php
The mock was only needed in 10LTS.
Fixes #3276
> [TASK] Drop mock that is not needed anymore

- composer.json
> [TASK] Drop the `symfony/property-info` development dependency

- CHANGELOG.md
- composer.json
Also drop the now obsolete `ext-pdo` dependency.
> [TASK] Sync the allowed DBAL versions with the Core dependencies

- CHANGELOG.md
- composer.json
- ext_emconf.php
This version includes a fix for functional tests with TYPO3 12LTS.
> [TASK] Require oelib >= 6.0.1

- composer.json
> [TASK] Drop the CS-Fixer workaround for PHP 8.2 from `composer.json`

- CHANGELOG.md
- Classes/Templating/TemplateHelper.php
> [BUGFIX] Avoid using the deprecated `GeneralUtility::_GPmerged()`

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
> [TASK] Drop `RegistrationManager::isUserRegisteredMessage()`

- CHANGELOG.md
- Tests/Functional/OldModel/Fixtures/Events/EventsWithPlaces.xml
- Tests/Functional/OldModel/LegacyEventTest.php
- phpstan-baseline.neon
This is not possible in TYPO3 12LTS anymore as the DB then prohibits duplicate keys.
Fixes #3544
> [BUGFIX] Drop tests for duplicated place associations

- Classes/OldModel/LegacyEvent.php
Events with time slots, but without a begin date schould not be considered to have a date.
Fixes #3635
> [BUGFIX] Make the check for the begin date consistent

- CHANGELOG.md
- Classes/Controller/EventRegistrationController.php
- Classes/Controller/EventUnregistrationController.php
- Tests/Unit/Controller/EventRegistrationControllerTest.php
- Tests/Unit/Controller/EventUnregistrationControllerTest.php
- phpstan-baseline.neon
> [BUGFIX] Avoid the deprecated `ActionController::forward()` method

- Classes/Controller/BackEnd/EmailController.php
- Classes/Controller/BackEnd/EventController.php
- Classes/Controller/BackEnd/ModuleController.php
- Classes/Controller/BackEnd/RegistrationController.php
- Classes/Controller/EventRegistrationController.php
- Classes/Controller/EventUnregistrationController.php
- Classes/Controller/FrontEndEditorController.php
- Tests/Unit/Controller/BackEnd/EmailControllerTest.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/ModuleControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
- Tests/Unit/Controller/EventRegistrationControllerTest.php
- Tests/Unit/Controller/EventUnregistrationControllerTest.php
- Tests/Unit/Controller/FrontEndEditorControllerTest.php
Not returning anything in controller actions was deprecated in TYPO3 11LTS and removed in TYPO3 12LTS.
This commit takes care of `htmlResponse()`.
Part of #1482
> [BUGFIX] Return a response rendered controller actions

- CHANGELOG.md
- Tests/Unit/Controller/BackEnd/EmailControllerTest.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/ModuleControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
- Tests/Unit/Controller/EventRegistrationControllerTest.php
- Tests/Unit/Controller/EventUnregistrationControllerTest.php
- Tests/Unit/Controller/FrontEndEditorControllerTest.php
- Tests/Unit/Controller/RedirectMockTrait.php
Also reduce code duplication.
This is for calls to `redirect`, not for `redirectToUri`, which will come in a later change.
Part of #1482
> [BUGFIX] Mock redirects both for 11LTS and 12LTS

- CHANGELOG.md
- composer.json
- ext_emconf.php
This version brings some bug fixes related to testing with TYPO3 12LTS.
> [TASK] Require oelib >= 6.0.2

- CHANGELOG.md
- Tests/Functional/OldModel/LegacyEventTest.php
- Tests/Unit/Service/OneTimeAccountConnectorTest.php
Use fewer mocks, and provide the request where it is necessary.
Fixes #3600
> [BUGFIX] Streamline the `TYPO3_REQUEST` in some more tests

- CHANGELOG.md
- Classes/Csv/CsvDownloader.php
> [BUGFIX] Avoid using the deprecated `GeneralUtility::_GET()`

- CHANGELOG.md
- Classes/FrontEnd/DefaultController.php
- phpstan-baseline.neon
Nowadays, we can use the page title provider API (which we already are offering).
Fixes #3738
> [BUGFIX] Avoid using the deprecated `TSFE->indexedDocTitle`

- CHANGELOG.md
- Resources/Private/Templates/BackEnd/Email/Compose.html
- Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
This avoids usage of a deprecated view helper.
Part of #3743
> [TASK] Make back buttons in the BE module to regular links

- Classes/BackEnd/AbstractEventMailForm.php
- Classes/Controller/BackEnd/EmailController.php
- Classes/Controller/BackEnd/EventController.php
- Classes/Controller/BackEnd/ModuleController.php
- Classes/Controller/BackEnd/RegistrationController.php
- Resources/Private/Layouts/BackEndModule.html
- Tests/Unit/Controller/BackEnd/EmailControllerTest.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/ModuleControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
The `be:moduleLayout` view helper was deprecated in TYPO3 11LTS and removed in TYPO3 12LTS.
Fixes #3743
> [BUGFIX] Switch from the `be:moduleLayout` VH to `ModuleTemplate`

- Tests/Unit/Controller/BackEnd/EmailControllerTest.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/ModuleControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
These tests need to be rewritten as functional tests.
> [TASK] Skip the BE controller unit tests in V12

- Classes/OldModel/LegacyRegistration.php
- Tests/Functional/Service/RegistrationManagerTest.php
- Tests/LegacyFunctional/OldModel/LegacyRegistrationTest.php
- Tests/LegacyFunctional/Service/RegistrationManagerTest.php
Models should not cache anything, particularly not for other models.
Fixes #3649
> [TASK] Drop the cached seminars from `LegacyRegistration`

- CHANGELOG.md
- Classes/Domain/Repository/Event/EventRepository.php
- Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventAndDuplicateWithResetData.csv
- Tests/Functional/Domain/Repository/Event/Fixtures/duplicateViaDataHandler/SingleEventWithDataToReset.csv
This is the 5.x backport of #3805
Fixes #3757
> [BUGFIX] Ignore the webinar URL when duplicating an event

- CHANGELOG.md
- Configuration/TCA/tx_seminars_seminars.php
The field for the additional email text in the registration email only makes sense for events that offer/require a registration.
Conditionally hiding this field improves usability.
This is the 5.x backport of #3807.
Fixes #3756
> [TASK] Hide registration-related field for events without registration

- CHANGELOG.md
- Classes/Controller/BackEnd/EventController.php
- Classes/Controller/BackEnd/RegistrationController.php
- Tests/Unit/Controller/BackEnd/EventControllerTest.php
- Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
This is the 5.x backport of #3810.
Fixes #3468
> [BUGFIX] Fix translation for flash message in BE module

- CHANGELOG.md
- Classes/OldModel/LegacyTimeSlot.php
- Tests/LegacyFunctional/OldModel/LegacyTimeSlotTest.php
This is the 5.x backport of #3816.
Part of #3463
> [TASK] Do not display "will be announced" for time slots

- CHANGELOG.md
- Classes/OldModel/AbstractTimeSpan.php
- Tests/Functional/OldModel/AbstractTimeSpanTest.php
This makes the display a bit more compact.
This is the 5.x backport of #3836.
Fixes #3814
> [TASK] Do not display "will be announced" for date or time of not set

- CHANGELOG.md
- Classes/OldModel/LegacyEvent.php
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithBeginAndWithEndDate.csv
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithBeginAndWithoutEndDate.csv
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithOneTimeSlot.csv
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithTwoTimeSlots.csv
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithoutBeginAndWithEndDate.csv
- Tests/Functional/OldModel/Fixtures/Events/hasTime/SingleEventWithoutDate.csv
- Tests/Functional/OldModel/LegacyEventTest.php
This is the 5.x backport of #3838.
Fixes #3646
> [BUGFIX] Only display the event times if there are no time slots

- .gitattributes
- Build/phpunit/FunctionalTests.xml
- Build/phpunit/UnitTests.xml
- README.md
- composer.json
This follows current best practices.
> [TASK] Move the PHPUnit configuration files to `Build/`

- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
This is the 5.x backport of #3883.
[ci skip]
> [DOCS] Fix version number in deprecation comment

- CHANGELOG.md
- Classes/Domain/Repository/Event/EventRepository.php
- phpstan-baseline.neon
> [BUGFIX] Use variadic parameters when calling `logicalAnd`

- .github/workflows/ci.yml
- .github/workflows/release.yml
Sometimes, installing PHP can take up to 1.5 minutes.
> [TASK] Increase some CI timeouts event more

- Configuration/TCA/Overrides/tt_content.php
- ext_localconf.php
The event registration plugin is used more often than the FE editor and hence should come first.
Also make the configuration a bit more compact.
> [TASK] Reorder plugin definitions

- CHANGELOG.md
- Resources/Private/Language/locallang.xlf
This reduces the width of the FE events list, which is particularly helpful on mobile devices.
Fixes #3919
> [TASK] Shorten the registation/unregistration link label

- CHANGELOG.md
- Resources/Private/Language/locallang_db.xlf
To improve usability, the changes label makes it more clear that this is the full address.
Fixes #3400
> [TASK] Make the TCEforms label for the venue address more specific

- CHANGELOG.md
- Classes/Service/RegistrationManager.php
- Resources/Private/Language/locallang.xlf
- Tests/Functional/Service/RegistrationManagerTest.php
- Tests/LegacyFunctional/FrontEnd/DefaultControllerTest.php
This helps reduce the width and height of the event list view, particularly on mobile devices.
Also shorten the label for prebooking.
Fixes #3925
> [TASK] Shorten the link label for the waiting list registration

- CHANGELOG.md
- Resources/Private/Language/locallang_db.xlf
This record type represents all types of events, not only seminars.
Fixes #3466
> [TASK] Use the term "event" instead of "seminars" in the TCEforms

- CHANGELOG.md
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_db.xlf
The label now communicates better that there can be additional attendees, too.
Fixes #3662
> [TASK] Improve the label for "register myself (as well)"

- CHANGELOG.md
- Resources/Private/Language/locallang_db.xlf
This makes the labels consistent with the Core labels.
Fixes #2921
> [TASK] Always use the singular form for table names in the backend

- CHANGELOG.md
- Classes/Model/Event.php
- Tests/LegacyFunctional/Model/EventTest.php
- Tests/Unit/Model/EventTest.php
This method is only called from tests.
Part of #3422
> [TASK] Drop `Event.hasQueueRegistrations`

- CHANGELOG.md
- Classes/Model/Event.php
- Tests/Unit/Model/EventTest.php
These methods are only called from tests.
Part of #3422
> [TASK] Drop `Event.hasVacancies` and `.hasUnlimitedVacancies`

- CHANGELOG.md
- Classes/Model/Event.php
- Tests/LegacyFunctional/Model/EventTest.php
This method is only called from tests.
Part of #3422
> [TASK] Drop `Event.getQueueRegistrations`

- CHANGELOG.md
- Classes/Model/Event.php
- Tests/Unit/Model/EventTest.php
This method is only called from tests.
Part of #3422
> [TASK] Drop `Event.getRegistrationsAfterLastDigest`

- Classes/Email/EmailBuilder.php
- Tests/Unit/Email/EmailBuilderTest.php
- phpstan-baseline.neon
This paves the way to using Extbase models as senders or recipients when sending emails.
> [FEATURE] Also allow `Frontenduser` instances for `EmailBuilder`

- CHANGELOG.md
- Classes/Service/EventStatisticsCalculator.php
- Tests/Unit/Service/EventStatisticsCalculatorTest.php
This helps improve performance in the list view.
Also add missing words to some test names.
> [TASK] Make `enrichWithStatistics` keep existing statistics

- CHANGELOG.md
- Classes/Domain/Model/Event/EventDateInterface.php
- Classes/Domain/Model/Event/EventDateTrait.php
- Classes/Service/RegistrationGuard.php
- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
The naming now is Fluid-friendly and more intuitive.
> [TASK] Rename `Event.allowsUnlimitedRegistrations`

- CHANGELOG.md
- Classes/Domain/Model/Event/EventStatistics.php
- Tests/Unit/Domain/Model/Event/EventStatisticsTest.php
This makes the naming consistent with the corresponding method in `EventDateInterface`.
It also makes the method name Fluid-friendly (as Fluid does not support differentiating between `getFoo`, `hasFoo` and `isFoo`).
> [TASK] Rename and flip `EventStatistics.hasSeatsLimit`

- CHANGELOG.md
- Resources/Private/Partials/Event/ArchiveList.html
- Resources/Private/Partials/Event/OutlookList.html
- Resources/Private/Partials/Event/Vacancies.html
- do not allow a line break for the vacancies before the traffic light icon
- allow breaking the (potentially long) dates
> [TASK] Optimize line breaks in the event lists

- Configuration/FlexForms/EventArchive.xml
- Configuration/FlexForms/EventOutlook.xml
- Configuration/FlexForms/flexforms_pi1.xml
This avoids mistakes when a developer edits the flexforms or TCA.
> [TASK] Always have `minitems` first before `maxitems`

- CHANGELOG.md
- Classes/Domain/Model/Event/EventDateInterface.php
- Classes/Domain/Model/Event/EventDateTrait.php
- Classes/Domain/Model/Event/EventInterface.php
- Classes/Domain/Model/Event/EventStatistics.php
- Classes/Domain/Model/Event/EventTopic.php
- Classes/Service/EventStatisticsCalculator.php
They will be refactored quite soon and hence will change drastically.
Hence they must not be public interface.
Fixes #4073
> [TASK] Make the event statistics internal

- CHANGELOG.md
- Classes/Model/Place.php
- Classes/Service/RegistrationManager.php
- Tests/LegacyFunctional/Model/PlaceTest.php
This only affects the old model, not the legacy model or the new domain model for venues.
Fixes #3922
> [TASK] Rename `Place::getAddress()` to `Place::getFullAddress()`

- CHANGELOG.md
- Classes/Domain/Model/Registration/Registration.php
- Classes/Domain/Repository/Registration/RegistrationRepository.php
- Classes/Service/RegistrationProcessor.php
- Configuration/Extbase/Persistence/Classes.php
- Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
- Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Also change it from a `bool` to an `int`.
This is in preparation for adding a third status
(nonbinding reservation) to the status drop-down.
> [TASK] Rename/retype `Registration.onWaitingList` to `.status`

- CHANGELOG.md
- Classes/Domain/Model/Event/EventTopicTrait.php
- Classes/Domain/Model/Registration/AttendeesTrait.php
- Classes/Domain/Model/Registration/PaymentTrait.php
- Classes/Domain/Model/Registration/Registration.php
- Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
- Tests/Functional/Domain/Repository/Event/Fixtures/propertyMapping/SingleEventWithDeletedEventType.csv
- Tests/Functional/Domain/Repository/Registration/Fixtures/propertyMapping/RegistrationWithDeletedEvent.csv
- Tests/Functional/Domain/Repository/Registration/Fixtures/propertyMapping/RegistrationWithDeletedPaymentMethod.csv
- Tests/Functional/Domain/Repository/Registration/Fixtures/propertyMapping/RegistrationWithDeletedUser.csv
- Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
- phpstan-baseline.neon
This is the 5.x backport of #4109.
> [BUGFIX] Avoid crashes for deleted lazy-loaded associations

- CHANGELOG.md
- Resources/Private/Language/locallang.xlf
This is the 5.x backport of #4126.
> [BUGFIX] Fix a copy'n'paste error in a label

- Classes/Configuration/CsvExportConfigurationCheck.php
- Configuration/TypoScript/PluginShared.typoscript
We don't have a CSV export for events anymore.
Fixes #4131
> [TASK] Remove left-over code from CSV export of events

- CHANGELOG.md
- Classes/Localization/TranslateTrait.php
- Classes/Service/RegistrationManager.php
This is the 5.8.x backport of #3866.
Fixes #3865
> [BUGFIX] Avoid empty localized email subjects in some cases

- CHANGELOG.md
- Classes/Configuration/CsvExportConfigurationCheck.php
- Classes/Csv/CsvDownloader.php
- Classes/SchedulerTasks/MailNotifier.php
- Configuration/TypoScript/PluginShared.typoscript
- Documentation/Installation/SettingUpTheSchedulerTask/Index.rst
- Documentation/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst
- Tests/Functional/Csv/CsvDownloaderTest.php
- Tests/LegacyFunctional/SchedulerTasks/MailNotifierTest.php
- phpstan-baseline.neon
It is now hardcoded to `registrations.csv`.
> [TASK] Remove the configuration for the CSV file name

- CHANGELOG.md
- Classes/Domain/Model/Registration/Registration.php
- Configuration/TCA/tx_seminars_attendances.php
- Resources/Private/Language/locallang_db.xlf
This avoids confusion with the new labels from `main`.
Fixes #4162
This is the 5.8.1 backport of #4192.
> [BUGFIX] Change the registration status from checkbox to drop-down

- CHANGELOG.md
- Classes/Domain/Repository/Registration/RegistrationRepository.php
- Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
- phpstan-baseline.neon
This allows for further processing in the method without having to change the API.
> [TASK] Switch `findActiveRegistrationsByUser` to return array

- CHANGELOG.md
- Resources/Private/Language/locallang.xlf
This is more accurate than "my events" (which would also fit for the list view of the FE editor).
> [TASK] Rename the new plugin to "my registrations"

- .gitattributes
- .github/workflows/ci.yml
- composer-unused.php
- composer.json
Due to other dependencies, this tool now crashes.
As it does not bring much additional value, we now remove it again.
> [TASK] Drop `composer-unused`

- Classes/Domain/Model/Event/EventDateInterface.php
- Classes/Domain/Model/Event/EventDateTrait.php
- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
Rename to `isDownloadsPossibleByDate` to make this method usable in Fluid (which only recognizes the prefixes `get`, `is` and `has`).
> [TASK] Rename `Registration.areDownloadsPossibleByDate()`

- CHANGELOG.md
- Resources/Private/Partials/MyRegistrations/Show.html
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/NonBindingReservationWithDownload.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithDownloadStartInFuture.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithDownloadStartInPast.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/WaitingListRegistrationWithDownload.csv
- Tests/Functional/Controller/MyRegistrationsControllerTest.php
Registered persone may only download event downloads
- if their registration is a regular registration (instead of a waiting list registration or non-binding reservation)
- and if the download embargo has passed (if there is any)
> [TASK] Restrict access to event downloads

- CHANGELOG.md
- Classes/Model/Place.php
- Classes/OldModel/LegacyEvent.php
- Configuration/TCA/tx_seminars_sites.php
- Resources/Private/Language/locallang_db.xlf
- Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithOneVenue.csv
- Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithTwoVenuesInDifferentCities.csv
- Tests/Functional/Controller/Fixtures/EventController/archiveAction/PastEventWithTwoVenuesInSameCity.csv
- Tests/Functional/Controller/Fixtures/EventController/outlookAction/FutureEventWithOneVenue.csv
- Tests/Functional/Controller/Fixtures/EventController/outlookAction/FutureEventWithTwoVenuesInDifferentCities.csv
- Tests/Functional/Controller/Fixtures/EventController/outlookAction/FutureEventWithTwoVenuesInSameCity.csv
- Tests/Functional/Controller/Fixtures/EventController/showAction/PastEventWithOneVenue.csv
- Tests/Functional/Controller/Fixtures/EventController/showAction/PastEventWithTwoVenuesInSameCity.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithOneVenue.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithTwoVenuesInSameCity.csv
- Tests/Functional/OldModel/Fixtures/Events/EventsWithPlaces.xml
- Tests/LegacyFunctional/Model/PlaceTest.php
- Tests/LegacyFunctional/OldModel/LegacyEventTest.php
- ext_tables.sql
This is now part of the "full address" field.
Part of #3923
Closes #3923
Closes #4087
> [TASK] Drop `Venue.zip`

- CHANGELOG.md
- Configuration/TypoScript/PluginShared.typoscript
> [TASK] Drop removed configuration option from default TypoScript

- Tests/LegacyFunctional/FrontEnd/SelectorWidgetTest.php
- Tests/LegacyFunctional/Model/PlaceTest.php
Now that venus don't have a country anymore, we don't need to create test data for this anymore.
Followup to #4273.
> [TASK] Avoid creating country records in the tests

- Tests/Functional/Controller/Fixtures/FrontEndEditorController/createAction/NewlyCreatedEvent.csv
- Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateAction/EventWithOwner.csv
- Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateAction/UpdatedEvent.csv
- Tests/Functional/Controller/FrontEndEditorControllerTest.php
- Tests/Unit/Controller/FrontEndEditorControllerTest.php
- Drop unit tests for functionality that now is covered by functional tests.
- Use CSV DB assertions for checking the contents of the database.
- Use dedicated per-action DB fixtures.
> [TASK] Streamline `FrontEndEditorControllerTest`

- CHANGELOG.md
- Classes/Controller/FrontEndEditorController.php
- Tests/Functional/Controller/Fixtures/FrontEndEditorController/createAction/CreatedEventWithSlug.csv
- Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateAction/EventWithOwner.csv
- Tests/Functional/Controller/Fixtures/FrontEndEditorController/updateAction/UpdatedEventWithSlug.csv
- Tests/Functional/Controller/FrontEndEditorControllerTest.php
- Tests/Unit/Controller/FrontEndEditorControllerTest.php
This covers single event records. Event date records will come in a later change.
Fixes #4283
> [BUGFIX] Update slug after editing an event in the FE editor

- Resources/Private/Language/locallang.xlf
The label for the country was not only used in the FE, but also in the emails.
Followup to #4261
Fixes #4359
> [BUGFIX] Reconstitute a label that was erroneously deleted

- Classes/Controller/FrontEndEditorController.php
- Tests/Functional/Controller/FrontEndEditorControllerTest.php
- Tests/Unit/Controller/FrontEndEditorControllerTest.php
With recent TYPO3 versions, form values on failed validation are restored in a different way, and so this mechanism is no longer needed.
Fixes #4358
> [TASK] Drop default argument from `newSingleEventAction`

- CHANGELOG.md
- Classes/BackEnd/EmailService.php
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/Registration/AttendeesTrait.php
- Classes/Domain/Model/Registration/Registration.php
- Classes/Domain/Repository/FrontendUserRepository.php
- Classes/Email/EmailBuilder.php
- Classes/Service/RegistrationProcessor.php
- Configuration/Extbase/Persistence/Classes.php
- Tests/Functional/Domain/Repository/Fixtures/FrontendUserRepository/propertyMapping/FrontendUserWithAllScalarData.csv
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
- Tests/Functional/Service/RegistrationProcessorTest.php
- Tests/Unit/Controller/EventUnregistrationControllerTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- Tests/Unit/Domain/Model/Registration/RegistrationTest.php
- Tests/Unit/Email/EmailBuilderTest.php
- Tests/Unit/Service/RegistrationProcessorTest.php
- phpstan-baseline.neon
This is required so we can store the per-user default organizer for the FE editor.
> [FEATURE] Add seminars-specific frontend user model/repository

- CHANGELOG.md
- Classes/Domain/Model/Event/EventDate.php
- Classes/Domain/Model/Event/EventInterface.php
- Classes/Domain/Model/Event/EventTopic.php
- Classes/Domain/Model/Event/SingleEvent.php
- Tests/Unit/Domain/Model/Event/EventDateTest.php
- Tests/Unit/Domain/Model/Event/EventTopicTest.php
- Tests/Unit/Domain/Model/Event/SingleEventTest.php
These methods are needed to differentiate between different object types in the FE editor form.
Part of #4282
> [FEATURE] Add STI type check methods to the event methods

- CHANGELOG.md
- Classes/Controller/FrontEndEditorController.php
When editing event date records, we don't need some auxiliary records (event types, categories), but we need the topics.
Follow-up to #4407
> [TASK] Add helper method for date aux records in the FE editor

- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/NonBindingReservationWithDownload.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithDownloadStartInFuture.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegistrationWithDownloadStartInPast.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegularRegistrationWithDownloadWithTitle.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/RegularRegistrationWithDownloadWithoutTitle.csv
- Tests/Functional/Controller/Fixtures/MyRegistrationsController/showAction/WaitingListRegistrationWithDownload.csv
- Tests/Functional/Controller/MyRegistrationsControllerTest.php
This works around a problem in the testing framework for non-text response contents.
> [BUGFIX] Use a different MIME type in the functional tests

- CHANGELOG.md
- ext_tables.sql
This prevents the newly created records to be processed by the upgrade wizard (which would overwrite the billing address the attendee entered).
> [TASK] Set the default for the hidden billing address flag

- Classes/Service/RegistrationManager.php
This is the 5.x backport of #4520.
> [BUGFIX] Avoid inlining CSS into empty HTML for the email

- CHANGELOG.md
- Configuration/TCA/tx_seminars_attendances.php
- Configuration/TCA/tx_seminars_organizers.php
- Configuration/TCA/tx_seminars_sites.php
- Configuration/TCA/tx_seminars_speakers.php
This is the 5.8.x backport of #4536.
> [BUGFIX] Validate email fields in the BE as emails
