oliverklee/ext-seminars

CHANGELOG.md, composer.json, ext_emconf.php
This is the earliest version available on Packagist.
=> [TASK Rrequire static_info_tables >= 6.3.7

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> [BUGFIX] Add missing localized label for organizer in notification email

CHANGELOG.md, composer.json, ext_emconf.php
This fixes some issues with PHP 7.
=> [BUGFIX] Require mkforms >= 3.0.14

CHANGELOG.md, Configuration/TCA/tx_seminars_categories.php, Configuration/TCA/tx_seminars_seminars.php
=> [BUGFIX] Increase the maximum file sizes for images

CHANGELOG.md, Classes/FrontEnd/CategoryList.php, Classes/FrontEnd/DefaultController.php, Classes/OldModel/Event.php, Tests/Unit/FrontEnd/DefaultControllerTest.php
=> [BUGFIX] Adapt the calls to cObj->IMAGE to TYPO3 8.7

CHANGELOG.md, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_speakers.php
Now whitespace tags like `<br>` will not be removed on saving anymore.
Fixes #37
=> [BUGFIX] Update the RTE configuration

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/AbstractList.php, Classes/BackEnd/CancelEventMailForm.php, Classes/BackEnd/ConfirmEventMailForm.php, Classes/BackEnd/EventsList.php, Classes/BackEnd/GeneralEventMailForm.php, Classes/BackEnd/Module.php, Classes/BackEnd/OrganizersList.php, Classes/BackEnd/RegistrationsList.php, Classes/BackEnd/index.php, Classes/Bag/Registration.php, Classes/ConfigCheck.php, Classes/Csv/AbstractListView.php, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/Editor.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/OldModel/Event.php, Classes/Service/RegistrationManager.php, Classes/Service/SingleViewLinkBuilder.php, Classes/ViewHelper/DateRange.php, Configuration/TypoScript/setup.txt, Tests/Unit/BackEnd/OrganizersListTest.php, Tests/Unit/BackEnd/RegistrationsListTest.php, Tests/Unit/BackEnd/SpeakersListTest.php, Tests/Unit/Csv/AbstractRegistrationListViewTest.php, Tests/Unit/FrontEnd/CountdownTest.php, Tests/Unit/Mapper/CheckboxTest.php
=> [BUGFIX] Fix code inspection warnings about undefined things

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/AbstractList.php, Classes/BackEnd/EventsList.php, Classes/BackEnd/Module.php, Classes/BackEnd/OrganizersList.php, Classes/BackEnd/SpeakersList.php, Classes/Bag/Abstract.php, Classes/Csv/AbstractListView.php, Classes/Csv/CsvDownloader.php, Classes/EmailSalutation.php, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/Countdown.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventHeadline.php, Classes/FrontEnd/RegistrationsList.php, Classes/FrontEnd/RequirementsList.php, Classes/FrontEnd/SelectorWidget.php, Classes/OldModel/Abstract.php, Classes/OldModel/Event.php, Classes/OldModel/Registration.php, Classes/Service/RegistrationManager.php, Classes/Service/SingleViewLinkBuilder.php, Classes/ViewHelper/Countdown.php, Classes/ViewHelper/DateRange.php, Classes/ViewHelper/TimeRange.php
In modern PHP, those are not needed anymore.
=> [CLEANUP] Drop the destructors

CHANGELOG.md, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/Model/Event.php, Classes/Model/FrontEndUser.php, Classes/OldModel/Event.php
This class is a simple container that will not be XClassed and where
instantiation is performance-critical.
=> [TASK] Use new instead of makeInstance for Tx_Oelib_List

CHANGELOG.md, Classes/BackEnd/TceForms.php, Configuration/TCA/Overrides/fe_users.php, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_categories.php, Configuration/TCA/tx_seminars_checkboxes.php, Configuration/TCA/tx_seminars_event_types.php, Configuration/TCA/tx_seminars_foods.php, Configuration/TCA/tx_seminars_lodgings.php, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_payment_methods.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_skills.php, Configuration/TCA/tx_seminars_speakers.php, Configuration/TCA/tx_seminars_target_groups.php, Configuration/TCA/tx_seminars_test.php, Configuration/TCA/tx_seminars_timeslots.php, ext_tables.php
Also drop the getPathToDbLL function.
=> [CLEANUP] Update and clean up the TCA

CHANGELOG.md
=> [BUGFIX] Move some changelog lines to the correct release

Documentation/EN/Introduction/Sponsorship/Index.rst
Also use HTTPS for the sites that offer it.
[ci skip]
=> [TASK] Add the new sponsors to the manual

Classes/BackEnd/AbstractList.php
=> [CLEANUP] Minor code reformatting

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_test.php, Configuration/TCA/tx_seminars_timeslots.php
=> [BUGFIX] Fix error messages in the TCA for date/time fields

CHANGELOG.md, Resources/Private/Language/FrontEnd/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf
=> [BUGFIX] Make the TCA "speakers" tab gender-neutral

CHANGELOG.md, Configuration/TypoScript/setup.txt, Documentation/DE/AnmeldungenVerwalten/AnmeldestatistikAnzeigen/Index.rst, Documentation/DE/Benutzerhandbuch/DasBack-end-modulVeranstaltungen/Index.rst, Documentation/DE/Benutzerhandbuch/ErstellungEinesSeminarsInWebListe/Index.rst, Documentation/DE/Installation/DasPluginKonfigurieren/Index.rst, Documentation/DE/Referenz/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/DE/Seminar-organisation/Index.rst, Resources/Private/Language/BackEnd/de.locallang.xlf, Resources/Private/Language/BackEnd/dk.locallang.xlf, Resources/Private/Language/BackEnd/fr.locallang.xlf, Resources/Private/Language/BackEnd/it.locallang.xlf, Resources/Private/Language/BackEnd/locallang.xlf, Resources/Private/Language/BackEnd/nl.locallang.xlf, Resources/Private/Language/FrontEnd/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf
The term "sys folder"/"sysfolder" has been deprecated for quite a while now.
=> [BUGFIX] Update the term "sys folder" to "folder"

Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [BUGFIX] prevent IE from sending the registration form multiple times

CHANGELOG.md
=> [TASK] Add missing changelog entry

CHANGELOG.md, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst
=> [BUGFIX] Update the documentation of the hooks

Classes/Mapper/Event.php
=> [CLEANUP] Autoformat the event mapper

CHANGELOG.md, Configuration/TypoScript/setup.txt
=> [BUGFIX] Fix crash in the CSV download

Classes/FrontEnd/RegistrationForm.php, Classes/OldModel/Event.php, Tests/Unit/FrontEnd/RegistrationFormTest.php, Tests/Unit/Model/EventTest.php
=> [CLEANUP] Some code autoformatting

Classes/Service/RegistrationManager.php, Tests/Unit/Service/RegistrationManagerTest.php
=> [CLEANUP] Code autoformat

Documentation/EN/Introduction/LiveExamples/Index.rst
=> [BUGFIX] Fix/remove outdated live example URLs

.gitignore, CHANGELOG.md
- PHP-CS-Fixer cache file
- backup files with `~`
[ci skip]
=> [BUGFIX] Add more common files to the .gitignore

CHANGELOG.md, LICENSE, composer.json
This will allow integrators to use this extension in projects that also
have GPL V2-only extensions.
=> [TASK] Change from GPL V3 to GPL V2+

CHANGELOG.md, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EMailSalutationTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
This fixes the tests with PHPUnit 5.7.
=> [BUGFIX] Initialize a BE user in the BE-related tests

Documentation/EN/Introduction/Sponsorship/Index.rst
=> [TASK] Add more sponsors to the manual

Classes/Hooks/RegistrationEmailHookInterface.php
=> [CLEANUP] Drop obsolete comment code block

CHANGELOG.md, Classes/OldModel/Event.php, Classes/Service/RegistrationManager.php, Classes/Service/SingleViewLinkBuilder.php
Also make two parameter type declarations more specific.
=> [CLEANUP] Fix more PHPDoc type annotations

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
As requested by @oliverklee in https://github.com/oliverklee/ext-seminars/pull/238/files/48e50e10472da840c6e6613973aa704e0b603d41#r344122156
=> [FEATURE] Refactor registration form footer creation

CHANGELOG.md, Classes/BagBuilder/Abstract.php, Tests/LegacyUnit/BagBuilder/AbstractTest.php
As requested _by @oliverklee in https://github.com/oliverklee/ext-seminars/pull/238_.
=> [FEATURE] Enable modifying the BagBuilder limitations for hooks

CHANGELOG.md, Classes/BagBuilder/Abstract.php, Classes/BagBuilder/Category.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/Model/Event.php, Classes/OldModel/Abstract.php, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/Event.php, Classes/OldModel/Registration.php, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/BagBuilder/AbstractTest.php
=> [BUGFIX] Fix more type errors

CHANGELOG.md, composer.json, ext_emconf.php
Also update the recommendations for adding FE user fields.
=> [TASK] Bump the static_info_tables dependency

CHANGELOG.md, ext_localconf.php, ext_tables.php
- reduce code duplication
- stop polluting the global namespace
=> [CLEANUP] Streamline ext_localconf.php and ext_tables.php

Classes/OldModel/AbstractModel.php, Tests/LegacyUnit/Fixtures/Bag/TestingBag.php, Tests/LegacyUnit/OldModel/AbstractModelTest.php, Tests/Unit/OldModel/AbstractModelTest.php, Tests/Unit/OldModel/Fixtures/TestingModel.php, Tests/Unit/OldModel/Fixtures/TestingModelWithConfiguration.php
This is the first step towards decoupling the old model from the DB.
=> [TASK] Make all constructor parameters of the old model optional

CHANGELOG.md, Tests/Unit/Hooks/Fixtures/TestingHookImplementor.php, Tests/Unit/Hooks/Fixtures/TestingHookImplementor2.php, Tests/Unit/Hooks/Fixtures/TestingHookImplementorNotImplementsInterface.php, Tests/Unit/Hooks/Fixtures/TestingHookInterface.php, Tests/Unit/Hooks/Fixtures/TestingHookInterfaceNotExtendsHook.php, Tests/Unit/Hooks/HookProviderTest.php
=> [CLEANUP] Move the fixture classes around

CHANGELOG.md, Classes/OldModel/AbstractModel.php, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/Category.php, Classes/OldModel/Organizer.php, Classes/OldModel/Registration.php, Classes/OldModel/TimeSlot.php
This should improve performance and allow more tests to be unit tests.
=> [TASK] Stop initializing the TemplateHelper for some old models

.travis.yml, CHANGELOG.md, composer.json
Now Travis CI checks that php-cs-fix will not change anything.
=> [FEATURE] Add php-cs-fixer to the CI

CHANGELOG.md, Classes/OldModel/AbstractModel.php
=> [TASK] Move the AbstractModel constructor to the top of the class

CHANGELOG.md, Tests/Functional/Configuration/TypoScriptSetupTest.php, Tests/Functional/Fixtures/FrontEndUsers.xml, Tests/Functional/Fixtures/Registrations.xml, Tests/Functional/Fixtures/Speakers.xml, Tests/Functional/FrontEnd/DefaultControllerTest.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Mapper/BackEndUserGroupTest.php, Tests/Functional/Mapper/RegistrationTest.php, Tests/Functional/Model/SpeakerTest.php, Tests/Functional/OldModel/AbstractModelTest.php, Tests/Functional/OldModel/SpeakerTest.php, Tests/Functional/RealUrl/ConfigurationTest.php, Tests/Functional/SchedulerTask/RegistrationDigestTest.php, Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Also convert some functional tests to unit tests.
=> [TASK] Streamline the functional tests

CHANGELOG.md, Classes/OldModel/AbstractModel.php, Classes/OldModel/Category.php, Classes/OldModel/Organizer.php, Classes/OldModel/Speaker.php, Tests/Unit/OldModel/Fixtures/TestingModel.php, Tests/Unit/OldModel/Fixtures/TestingModelWithConfiguration.php, Tests/Unit/OldModel/Fixtures/TestingTimeSpan.php
This should improve performance and also make unit testing easier.
=> [TASK] Stop eagerly loading the language files in the BE

CHANGELOG.md, Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/Functional/BackEnd/EventsListTest.php, Tests/Functional/BackEnd/Fixtures/Records.xml, Tests/Functional/BackEnd/Fixtures/TestingEventMailForm.php, Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php, Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php, Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php, Tests/LegacyUnit/BackEnd/EventsListTest.php, Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
=> [BUGFIX] Move fragile back-end tests to the new testing framework

CHANGELOG.md, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/LegacyUnit/Csv/CsvDownloaderTest.php
=> [TASK] Move a fragile CSV download test to the new TF

CHANGELOG.md, Tests/Functional/BagBuilder/EventBagBuilderTest.php, Tests/Functional/BagBuilder/Fixtures/Records.xml, Tests/LegacyUnit/BagBuilder/EventTest.php
=> [TASK] Convert some fragile bag builder tests to the new TF

Tests/LegacyUnit/OldModel/AbstractModelTest.php, Tests/LegacyUnit/OldModel/CategoryTest.php, Tests/LegacyUnit/OldModel/EventTest.php, Tests/LegacyUnit/OldModel/OrganizerTest.php, Tests/LegacyUnit/OldModel/RegistrationTest.php, Tests/LegacyUnit/OldModel/TimeSlotTest.php, Tests/LegacyUnit/Service/EMailSalutationTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Service/EventStateServiceTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php, Tests/LegacyUnit/ViewHelper/DateRangeTest.php, Tests/LegacyUnit/ViewHelper/TimeRangeTest.php
- make some test classes final
- use private fields
- fix a typo
- use the fully-qualified function name in more places
- drop a useless property
=> [CLEANUP] Some testcase cleanup

CHANGELOG.md, Classes/OldModel/TimeSlot.php, Tests/LegacyUnit/OldModel/TimeSlotTest.php
=> [BUGFIX] Convert the time slot model to the ConnectionPool

CHANGELOG.md, Classes/OldModel/AbstractModel.php, Classes/OldModel/Event.php, Classes/OldModel/Registration.php, Classes/OldModel/Speaker.php
Also refactor to make a method reusable across models.
=> [BUGFIX] Convert the registration model to the ConnectionPool

Tests/Functional/Csv/CsvDownloaderTest.php, Tests/Functional/Csv/Fixtures/EventsAndRegistrations.xml, Tests/LegacyUnit/Csv/CsvDownloaderTest.php
=> [BUGFIX] Fix failing CSV downloader tests in 9.5

CHANGELOG.md, Classes/BackEnd/AbstractList.php
This fixes the backend tests in 9.5.
=> [BUGFIX] Stop using getLinkToDataHandlerAction

Classes/FrontEnd/DefaultController.php, Classes/Hooks/Interfaces/SeminarRegistrationForm.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
As requested by @oliverklee in #241
* Hooks to header, form and footer
* Test for the hooks
I will add the changelog entry when this is almost finished (to prevent conflicts when rebasing).
=> [FEATURE] Add registration form hooks

CHANGELOG.md, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst
Add missing documentation updates for #338 and #408
=> [FEATURE] Update documentation on hooks

CHANGELOG.md, Classes/FrontEnd/SelectorWidget.php, Classes/Hooks/Interfaces/SeminarSelectorWidget.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
Replaces #240. I will add the CHANGELOG line when it is ready to merge.
=> [FEATURE] Add selector widget hook, test and docs

CHANGELOG.md, Classes/BackEnd/RegistrationsList.php, Classes/Hooks/Interfaces/BackendRegistrationListView.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
Replaces #241. I will add the CHANGELOG line when it is ready to merge.
I also fixed some missing translations in German manual (comments inside code blocks).
=> [FEATURE] Add backend registration list view hooks, test and docs

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/Model/AbstractTimeSpan.php, Classes/Model/Event.php, Classes/OldModel/TimeSlot.php, Configuration/TCA/tx_seminars_timeslots.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang_db.xlf, Tests/LegacyUnit/Mapper/TimeSlotTest.php, Tests/LegacyUnit/Model/AbstractTimeSpanTest.php, Tests/LegacyUnit/Model/EventTest.php, Tests/Unit/Model/EventTest.php, ext_tables.sql
Now the begin date always is used as the label in the back end.
=> [TASK] Drop the title field for time slots

CHANGELOG.md, Classes/OldModel/Event.php
Users should be able to enter any prices they want.
Part of #450
=> [TASK] Stop automatically unsetting invalid prices in the BE

CHANGELOG.md, Classes/Hooks/Interfaces/RegistrationEmail.php, Classes/Hooks/RegistrationEmailHookInterface.php, Classes/Service/RegistrationManager.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/Service/RegistrationManagerTest.php
Converts the previously existing hook to the new HookProvider and adds some parameters to enhance usability.
I will add docs and CHANGELOG.md later to this PR.
=> [FEATURE] Enhance email registration hook in RegistrationManager

Classes/BackEnd/RegistrationsList.php, Classes/Hooks/Interfaces/BackendRegistrationListView.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
Solves #457.
I have added the mocked instances cleanup to the test, too. CHANGELOG update when review seems finished.
=> [CLEANUP] Convert new hooks to new models

CHANGELOG.md, Classes/Hooks/HookProvider.php, Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsModifiedValue.php, Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsModifiedValue2.php, Tests/Unit/Hooks/Fixtures/TestingHookInterfaceReturnsModifiedValue.php, Tests/Unit/Hooks/HookProviderTest.php
This is required for the next hooks that modify method scoped values.
=> [FEATURE] Enhance hook provider with methods passing on the modified value

CHANGELOG.md, Classes/OldModel/Event.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Hooks/Fixtures/DataMapperHook/TimeSlots.xml
=> [BUGFIX] Fix the event begin/end date calculation by timeslots

Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/Hooks/Fixtures/DataMapperHook/NoPlacesFromTimeSlots.xml, Tests/Functional/Hooks/Fixtures/DataMapperHook/PlacesFromTimeSlots.xml
=> [TASk] Add tests for copying places from time slots to events

Classes/Hooks/DataHandlerHook.php, Tests/Functional/Hooks/DataHandlerHookTest.php
=> [CLEANUP] Refactor the data handler tests

Classes/Hooks/DataHandlerHook.php, Tests/Functional/Hooks/DataHandlerHookTest.php
Now only one hook method is used, not two anymore.
=> [TASK] Simplify the data handler hooks

Classes/OldModel/Registration.php
This is the 2.x backport of #475.
=> [CLEANUP] Code clean up in the old registration model

CHANGELOG.md, Classes/OldModel/Event.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_timeslots.php
=> [BUGFIX] Fix the rendering markup for locations

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/Event.php, Resources/Private/Templates/FrontEnd/FrontEnd.html, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
=> [TASK] Use an image tag instead of background image in the detail view

CHANGELOG.md, Configuration/TCA/Overrides/fe_users.php, Configuration/TCA/Overrides/sys_template.php, Configuration/TCA/Overrides/tt_content.php, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_categories.php, Configuration/TCA/tx_seminars_checkboxes.php, Configuration/TCA/tx_seminars_event_types.php, Configuration/TCA/tx_seminars_foods.php, Configuration/TCA/tx_seminars_lodgings.php, Configuration/TCA/tx_seminars_organizers.php, Configuration/TCA/tx_seminars_payment_methods.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TCA/tx_seminars_sites.php, Configuration/TCA/tx_seminars_skills.php, Configuration/TCA/tx_seminars_speakers.php, Configuration/TCA/tx_seminars_target_groups.php, Configuration/TCA/tx_seminars_test.php, Configuration/TCA/tx_seminars_timeslots.php, Configuration/php-cs-fixer.php, composer.json
Now the `php:fix` Composer script runs `phpcbf` in addition to
`php-cs-fixer`.
=> [TASK] Improve the code autoformatting

CHANGELOG.md, Classes/OldModel/Registration.php, Tests/LegacyUnit/OldModel/RegistrationTest.php
This will allow the tests to be simpler and faster.
=> [TASK] Allow empty user data for registrations

CHANGELOG.md, Classes/OldModel/Registration.php, Classes/Service/RegistrationManager.php, Tests/Unit/OldModel/RegistrationTest.php
This will improve performance and also make testing easier.
=> [FEATURE] Add Registration::setFrontEndUser() and cache it

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [BUGFIX] Remove whitespace around the email salutation

CHANGELOG.md, Classes/FrontEnd/RegistrationForm.php, Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php, Tests/Unit/FrontEnd/RegistrationFormTest.php
Also move more tests to the new testing framework.
=> [CLEANUP] Clean up the registration form class a bit

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/Hooks/Interfaces/DataSanitization.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/Hooks/DataHandlerHookTest.php
Superseeds #443
Rewrote the hook using more generic naming. I am still testing if passing the reference is working this way, so maybe I need to change the HookProvider usage.
=> Add DataSanitization hook to DataHandlerHook

Classes/BackEnd/AbstractList.php
The removed line is overwritten a few lines after.
=> [TASK] Remove redundant code line

CHANGELOG.md, README.md, composer.json
=> [TASK] Change the default git branch from master to main

.github/workflows/release.yml, .travis.yml, CHANGELOG.md
=> [TASK] Move the TER release from Travis CI to GitHub Actions

CHANGELOG.md, Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
=> [BUGFIX] Fix a test failure with mocks with PHP 7.4

Tests/LegacyUnit/OldModel/EventTest.php
=> [CLEANUP] Add more type declarations in the tests

Classes/FrontEnd/RegistrationForm.php
=> [CLEANUP] Use oelib's Typo3Version class for version checks

Classes/ConfigCheck.php
=> [CLEANUP] Stop using $this->getFrontEndController()->tmpl->getFileName()

Classes/BackEnd/FlexForms.php, Configuration/FlexForms/flexforms_pi1.xml, Tests/LegacyUnit/BackEnd/FlexFormsTest.php
=> [CLEANUP] Move FlexForms to Backend\FlexForms

Classes/FrontEnd/EventEditor.php, Classes/Model/BackEndUserGroup.php, Classes/Model/Category.php, Classes/Model/Checkbox.php, Classes/Model/Event.php, Classes/Model/EventType.php, Classes/Model/Food.php, Classes/Model/FrontEndUserGroup.php, Classes/Model/Interfaces/Titled.php, Classes/Model/Lodging.php, Classes/Model/Organizer.php, Classes/Model/PaymentMethod.php, Classes/Model/Place.php, Classes/Model/Registration.php, Classes/Model/Skill.php, Classes/Model/TargetGroup.php, Classes/ViewHelper/CommaSeparatedTitles.php, Tests/LegacyUnit/Fixtures/Model/TitledTestingModel.php, Tests/Unit/Model/EventTest.php
=> [CLEANUP] Migrate Tx_Seminars_Interface_Titled to Model namespace

Classes/Csv/AbstractBackEndAccessCheck.php, Classes/Csv/FrontEndRegistrationAccessCheck.php, Classes/Csv/Interfaces/CsvAccessCheck.php, Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php, Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php, Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
=> [CLEANUP] Move Tx_Seminars_Interface_CsvAccessCheck to Csv namespace

Classes/BackEnd/AbstractEventMailForm.php, Classes/Email/Salutation.php, Classes/Service/EmailService.php, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
=> [CLEANUP] Move EmailSalutation to Email\Salutation

Tests/LegacyUnit/OldModel/TimeSlotTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [CLEANUP]  Update \Tx_Oelib_Db calls in the tests

Classes/Service/RegistrationManager.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in the RegistrationManager to the new ConnectionPool

Classes/SchedulerTasks/MailNotifierConfiguration.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in the scheduler task to the new ConnectionPool

Classes/OldModel/Registration.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in RegistrationForm to the new ConnectionPool

Classes/FrontEnd/SelectorWidget.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in SelectorWidget to the new ConnectionPool

Classes/Mapper/Event.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in EventMapper to the new ConnectionPool

Classes/ConfigCheck.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in the ConfigCheck to the new ConnectionPool

Classes/OldModel/Event.php
=> [CLEANUP] Switch DB calls in OldModel\Event to the new ConnectionPool

Classes/BagBuilder/AbstractBagBuilder.php, Classes/BagBuilder/Registration.php
=> [CLEANUP] Remove \Tx_Oelib_Db call in BagBuilder\Registration

Classes/BagBuilder/AbstractBagBuilder.php, Classes/BagBuilder/Event.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in the BagBuilder\Event to the new ConnectionPool

.github/workflows/ci.yml, .github/workflows/release.yml
This should speed up the build a bit.
=> [TASK] Disable Xdebug for GitHub actions

Classes/Bag/AbstractBag.php
=> [CLEANUP] Switch \Tx_Oelib_Db calls in AbstractBag to the new ConnectionPool

CHANGELOG.md, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/Functional/FrontEnd/Fixtures/CategoryList/OneCategoryWithAsciiTitle.xml, Tests/Functional/FrontEnd/Fixtures/CategoryList/OneCategoryWithSpecialCharactersInTitle.xml, Tests/LegacyUnit/FrontEnd/CategoryListTest.php
Also drop some meaningless tests.
=> [TASK] Fix and update some category lists to the new testing framework

CHANGELOG.md, Classes/Bag/AbstractBag.php, Classes/BagBuilder/AbstractBagBuilder.php
=> [CLEANUP] Use the namespaced version of the oelib database service

CHANGELOG.md, Classes/BackEnd/AbstractList.php, Classes/Csv/AbstractBackEndAccessCheck.php, Classes/Csv/BackEndRegistrationAccessCheck.php, Classes/Csv/FrontEndRegistrationAccessCheck.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/FrontEnd/RequirementsList.php, Classes/OldModel/Event.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/RegistrationManager.php, Tests/Functional/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/BackEnd/EventsListTest.php, Tests/LegacyUnit/BackEnd/OrganizersListTest.php, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php, Tests/LegacyUnit/BackEnd/SpeakersListTest.php, Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php, Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php, Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [CLEANUP] Use the namespace oelib login managers

CHANGELOG.md, Classes/BackEnd/AbstractList.php, Classes/Csv/CsvDownloader.php, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/PublishEvent.php, Classes/Hooks/Interfaces/BackendRegistrationListView.php, Classes/Hooks/Interfaces/RegistrationEmail.php, Classes/Hooks/RegistrationEmailHookInterface.php, Classes/Interface/Hook/EventListView.php, Classes/Interface/Hook/EventSingleView.php, Classes/OldModel/AbstractModel.php, Classes/OldModel/Event.php, Classes/OldModel/Speaker.php, Classes/Service/ConfigurationService.php, Classes/Service/RegistrationManager.php, Classes/Service/SingleViewLinkBuilder.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php, Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
=> [CLEANUP] Use the namespaced oelib template classes

CHANGELOG.md, Classes/Bag/AbstractBag.php, Classes/BagBuilder/Event.php, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/DefaultController.php, Classes/Model/Organizer.php, Classes/Model/Speaker.php, Classes/OldModel/Event.php, Classes/OldModel/Organizer.php, Classes/OldModel/Registration.php, Classes/ViewHelper/Countdown.php, Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/OldModel/EventTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/LegacyUnit/ViewHelpers/CountdownViewHelperTest.php, Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
=> [CLEANUP] Use the namespaced oelib interfaces

CHANGELOG.md, Classes/Mapper/Category.php, Classes/Mapper/Checkbox.php, Classes/Mapper/Event.php, Classes/Mapper/EventType.php, Classes/Mapper/Food.php, Classes/Mapper/Lodging.php, Classes/Mapper/Organizer.php, Classes/Mapper/PaymentMethod.php, Classes/Mapper/Place.php, Classes/Mapper/Registration.php, Classes/Mapper/Skill.php, Classes/Mapper/Speaker.php, Classes/Mapper/TargetGroup.php, Classes/Mapper/TimeSlot.php
=> [CLEANUP] Use the namespaced oelib AbstractDataMapper

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/CancelEventMailForm.php, Classes/BackEnd/ConfirmEventMailForm.php, Classes/BackEnd/GeneralEventMailForm.php, Classes/FrontEnd/EventEditor.php, Classes/Hooks/Interfaces/RegistrationEmail.php, Classes/Hooks/RegistrationEmailHookInterface.php, Classes/Interface/Hook/BackEndModule.php, Classes/Model/Traits/EventEmailSenderTrait.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/EmailService.php, Classes/Service/RegistrationManager.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [CLEANUP] Use the namespaced oelib email-related classes

CHANGELOG.md, Classes/OldModel/Event.php, Classes/Service/RegistrationManager.php
=> [CLEANUP] Convert the remaning usages of non-namespaced oelib classes

Configuration/TCA/tx_seminars_seminars.php
=> [BUGFIX] Raise limit of field endtime to 2038-1-1

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
This restores compatibility with oelib 3.2.0.
Fixes #679
=> [BUGFIX] Add a missing return type declaration

Classes/FrontEnd/EventEditor.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php
=> [CLEANUP] Migrate EventEditor to SwiftMailer

Classes/Service/EmailService.php, Tests/LegacyUnit/Service/EmailServiceTest.php
=> [CLEANUP] Switch emailing in the EmailService from oelib mail functions to the Core SwiftMailer

Classes/ViewHelper/CommaSeparatedTitles.php, Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
=> [CLEANUP] Replace Tx_Seminars_Interface_Titled usages

Classes/BackEnd/AbstractEventMailForm.php, Classes/Email/Salutation.php, Classes/FrontEnd/DefaultController.php, Classes/Service/RegistrationManager.php
=> [CLEANUP] Replace GeneralUtility::getUserObj() with ::makeInstance

Resources/Private/Templates/BackEnd/EventsList.html, Resources/Private/Templates/BackEnd/OrganizersList.html, Resources/Private/Templates/BackEnd/RegistrationsList.html, Resources/Private/Templates/BackEnd/SpeakersList.html, Resources/Private/Templates/FrontEnd/FrontEnd.html
=> [CLEANUP] Drop the cellspacing HTML attribute from the HTML

.github/workflows/ci.yml
=> [CLEANUP] Replace the laravel_tags with legacy_tests

Classes/BackEnd/AbstractList.php, Classes/BackEnd/EventsList.php
=> [CLEANUP] Replace ExtensionManagementUtility::siteRelPath('seminars')

Classes/FrontEnd/Editor.php
=> [BUGFIX] Replace Tx_Rnbase_Configuration_Processor with Sys25\RnBase\Configuration\Processor

Tests/Functional/FrontEnd/DefaultControllerTest.php, Tests/Functional/FrontEnd/EventEditorTest.php
=> [CLEANUP] Stop calling ->initTemplate in TYPO3 >= 9

Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
=> [CLEANUP] Replace Bootstrap::getInstance for TYPO3 >= 9

Classes/Email/Salutation.php, Classes/ViewHelper/Countdown.php, Classes/ViewHelper/DateRange.php, Classes/ViewHelper/TimeRange.php
=> [CLEANUP] Stop using Translator and TranslatorRegistry

Tests/LegacyUnit/FrontEnd/PublishEventTest.php, Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [CLEANUP] Replace TestingFramework->existsRecord() and ->existsExactlyOneRecord() with the new Connection class

Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
=> [CLEANUP] Fix a typo in a test name

CHANGELOG.md, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_seminars.php
=> [BUGFIX] Drop the obsolete dividers2tabs option from TCA

Classes/BagBuilder/AbstractBagBuilder.php
=> [CLEANUP] Switch AbstractBagBuilder to PageRepository

Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/OldModel/EventTest.php, Tests/LegacyUnit/OldModel/RegistrationTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
=> [CLEANUP] Replace TestingFramework->countRecords with the new Connection class

Classes/Mapper/Event.php, Classes/Mapper/Registration.php, Tests/LegacyUnit/Mapper/EventMapperTest.php
=> [CLEANUP] Stop using ->findByWhereClause and ->countByWhereClause

CHANGELOG.md, Classes/Model/AbstractTimeSpan.php, Classes/Model/Event.php, Classes/Model/FrontEndUserGroup.php, Classes/Model/Registration.php, Classes/Model/Speaker.php
=> [CLEANUP] Replace the deprecated `getAsList` calls

Documentation/EN/Introduction/Sponsorship/Index.rst
- add new sponsors
- fix the ReST link syntax
- convert URLs from HTTP to HTTPS where possible
=> [TASK] Update the sponsors list

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Language/ru.locallang_db.xlf
This flag is not used, and it only increases file sizes.
=> [CLEANUP] Drop the `approved` flag from locallang labels

CHANGELOG.md, Documentation/DE/Installation/DasPluginKonfigurieren/Index.rst, Documentation/EN/Installation/SetUpThePlug-in/Index.rst, Documentation/EN/Introduction/Sponsorship/Index.rst, Documentation/Index.rst
=> [BUGFIX] Fix ReST rendering warnings in the documentation

Tests/Functional/Service/Fixtures/RegistrationManagerRecords.xml, Tests/Functional/Service/RegistrationManagerTest.php
=> [TASK] Convert some registration manager tests to the new TF

Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/EventEditor.php, phpstan.neon
This allows us to check `AbstractView` with PHPStan again.
Fixes #765
=> [TASK] Move `removePathFromWidgetData` to `EventEditor`

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf
=> [BUGFIX] Add a missing comma in a language label

CHANGELOG.md, Classes/Mapper/BackEndUser.php, Classes/Mapper/BackEndUserGroup.php, Classes/Mapper/FrontEndUser.php, Classes/Mapper/FrontEndUserGroup.php, Tests/Unit/Mapper/BackEndUserGroupMapperTest.php, Tests/Unit/Mapper/BackEndUserMapperTest.php, Tests/Unit/Mapper/FrontEndUserGroupMapperTest.php, Tests/Unit/Mapper/FrontEndUserMapperTest.php, phpstan-baseline.neon
This resolves problems with generics.
=> [TASK] Simplify the user and group mapper inheritance chains

Documentation/EN/Introduction/LiveExamples.rst, README.md
=> [TASK] Link to the testing distribution

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/dk.locallang_db.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/fr.locallang_db.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/it.locallang_db.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/nl.locallang_db.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Language/ru.locallang_db.xlf
=> [CLEANUP] Drop the `approved="yes"` from the locallang files

CHANGELOG.md, Classes/Hooks/DataHandlerHook.php, Classes/OldModel/Event.php, Tests/Functional/Hooks/DataHandlerHookTest.php, Tests/Functional/OldModel/EventTest.php, Tests/Functional/OldModel/Fixtures/Events/EventsWithPlaces.xml, Tests/LegacyUnit/OldModel/EventTest.php
=> [BUGFIX] Do not duplicate places when copying them from time slots

CHANGELOG.md, Classes/FrontEnd/EventHeadline.php, Tests/Functional/FrontEnd/EventHeadlineTest.php
=> [BUGFIX] Use the correct GET parameter for the UID in the event headline

CHANGELOG.md, Documentation/DE/BekannteProbleme/Index.rst, Documentation/EN/KnownProblems/Index.rst
=> [TASK] Document the required MySQL/MariaDB settings for the FE editor

CHANGELOG.md, Documentation/DE/Installation/Index.rst, Documentation/DE/Installation/Upgrading.rst, Documentation/EN/Installation/Index.rst, Documentation/EN/Installation/Upgrading.rst
=> [TASK] Document the upgrade path

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/FrontEnd/DefaultController.php, Classes/Interfaces/CsvAccessCheck.php, Classes/Interfaces/Hook/BackEndModule.php, Classes/Interfaces/Hook/EventListView.php, Classes/Interfaces/Hook/EventSingleView.php, Classes/Interfaces/Titled.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
=> [CLEANUP] Rename folder `Interface` to `Interfaces` to avoid keyword naming conflict

.gitattributes, .github/workflows/ci.yml, .gitignore, .phive/phars.xml, CHANGELOG.md, composer.json, phpstan-baseline.neon
=> [TASK] Move PHPStan from PHIVE to Composer

CHANGELOG.md, composer.json, ext_emconf.php
=> [TASK] Require rn_base >= 1.13.12

.gitignore, CHANGELOG.md, composer.json
=> [TASK] Upgrade to PHP-CS-Fixer V3

CHANGELOG.md, Classes/Bag/AbstractBag.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/OldModel/Event.php, Classes/Service/SingleViewLinkBuilder.php, Tests/Functional/FrontEnd/DefaultControllerTest.php, Tests/Functional/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
=> [TASK] Drop 8LTS-specific code

Classes/BackEnd/AbstractEventMailForm.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Classes/Model/Organizer.php, Classes/Model/Speaker.php, Classes/OldModel/Event.php, Classes/OldModel/Organizer.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/EmailService.php, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php, Tests/LegacyUnit/Model/OrganizerTest.php, Tests/LegacyUnit/Model/SpeakerTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php
=> [CLEANUP] Unify the casing of "EMail" to "Email"

.github/workflows/ci.yml, CHANGELOG.md, composer.json
=> [BUGFIX] Stop using patches for dependencies

CHANGELOG.md, Classes/Csv/AbstractListView.php, Classes/Csv/CsvDownloader.php, Classes/Csv/EventListView.php, Classes/FrontEnd/EventEditor.php, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/Functional/FrontEnd/EventHeadlineTest.php, Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php, Tests/LegacyUnit/Csv/CsvDownloaderTest.php, Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php, Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php, Tests/LegacyUnit/Csv/EventListViewTest.php, Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/FrontEnd/CountdownTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/OldModel/RegistrationTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php, Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php, Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php, Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php, Tests/Unit/SchedulerTask/RegistrationDigestTest.php
=> [CLEANUP] Use the dummy configuration class in the tests

CHANGELOG.md, ext_tables.sql
=> [CLEANUP] Drop autogeneratable fields from the SQL file

CHANGELOG.md, Classes/OldModel/AbstractModel.php, Classes/OldModel/AbstractTimeSpan.php, Classes/OldModel/TimeSlot.php, Tests/Functional/OldModel/AbstractTimeSpanTest.php, Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/OldModel/TimeSlotTest.php
=> [TASK] Use the new configuration class in `AbstractTimeSpan`

CHANGELOG.md, composer.json, phpstan-baseline.neon, phpstan.neon
This now allows more classes to be scanned with PHPStan.
=> [TASK] Bump the mkforms requirement

CHANGELOG.md, Classes/OldModel/Event.php, Tests/Functional/OldModel/EventTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/OldModel/EventTest.php
=> [TASK] Partially use the new configuration in FE tests

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [TASK] Use the new configuration for the email template path

CHANGELOG.md, composer.json
=> [BUGFIX] Complete `extras/typo3-cms` in the `composer.json`

Classes/Configuration/Traits/SharedPluginConfiguration.php, Classes/FrontEnd/DefaultController.php, Classes/OldModel/AbstractModel.php, Classes/Service/RegistrationManager.php
This reduces code duplication.
=> [CLEANUP] Move the shared configuration access to a trait

CHANGELOG.md, composer.json, ext_emconf.php
=> [TASK] Require static_info_tables >= 6.9.5

CHANGELOG.md, Classes/BackEnd/Controller.php, Classes/BackEnd/EventsList.php, Classes/BackEnd/OrganizersList.php, Classes/BackEnd/RegistrationsList.php, Classes/BackEnd/SpeakersList.php, Classes/Bag/AbstractBag.php, Classes/ConfigCheck.php, Classes/Configuration/SharedConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationsList.php, Classes/OldModel/AbstractModel.php, Tests/Functional/Configuration/SharedConfigurationCheckTest.php, Tests/Functional/Configuration/TypoScriptSetupTest.php, Tests/Unit/Configuration/SharedConfigurationCheckTest.php
=> [TASK] Convert the general configuration check to the new classes

CHANGELOG.md, Classes/ConfigCheck.php, Classes/Configuration/AbstractFrontEndConfigurationCheck.php, Classes/Configuration/RegistrationFormConfigurationCheck.php, Classes/Configuration/RegistrationListConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationsList.php, Tests/Functional/Configuration/RegistrationFormConfigurationCheckTest.php, Tests/Unit/Configuration/RegistrationFormConfigurationCheckTest.php
=> [TASK] Migrate the registration form config check

CHANGELOG.md, Classes/ConfigCheck.php, Classes/Configuration/AbstractFrontEndConfigurationCheck.php, Classes/Configuration/RegistrationFormConfigurationCheck.php, Classes/Configuration/SingleViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Tests/Functional/Configuration/SingleViewConfigurationCheckTest.php, Tests/Unit/Configuration/SingleViewConfigurationCheckTest.php
=> [TASK] Migrate the single view configuration check

CHANGELOG.md, Classes/ConfigCheck.php, Classes/Configuration/AbstractFrontEndConfigurationCheck.php, Classes/Configuration/CountdownConfigurationCheck.php, Classes/Configuration/ListViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Tests/Functional/Configuration/CountdownConfigurationCheckTest.php, Tests/Unit/Configuration/CountdownConfigurationCheckTest.php
=> [TASK] Migrate the countdown view configuration check

CHANGELOG.md, Classes/ConfigCheck.php, Classes/Configuration/EventHeadlineConfigurationCheck.php, Classes/Configuration/MyEnteredEventsConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Tests/Functional/Configuration/EventHeadlineConfigurationCheckTest.php, Tests/Unit/Configuration/EventHeadlineConfigurationCheckTest.php
=> [TASK] Migrate the configuration check for the event headline

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
=> [TASK] Drop more remnants of the legacy configuration check

Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
This gets the tests to run with oelib 4.0.
=> [BUGFIX] Provide the template file path in the default controller tests

CHANGELOG.md, Tests/LegacyUnit/FrontEnd/CategoryListTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php, Tests/LegacyUnit/FrontEnd/RequirementsListTest.php, Tests/LegacyUnit/OldModel/EventTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
This is needed due to changes in oelib 4.0.
=> [BUGFIX] Provide a page to the fake frontend where needed

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/AbstractList.php, Classes/Csv/AbstractListView.php, Classes/SchedulerTasks/MailNotifier.php, Classes/SchedulerTasks/MailNotifierConfiguration.php, Classes/Service/EmailService.php, Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php, Tests/LegacyUnit/Csv/CsvDownloaderTest.php, Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php, Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php, Tests/LegacyUnit/Csv/EventListViewTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php, Tests/Unit/Traits/LanguageHelper.php, composer.json
This package does not exist anymore.
Fixes #975
=> [BUGFIX] Drop the typo3/cms-lang dependency

CHANGELOG.md, Classes/FrontEnd/Countdown.php, Classes/FrontEnd/EventHeadline.php, Classes/Service/EmailService.php, Classes/ViewHelpers/CommaSeparatedTitlesViewHelper.php, Classes/ViewHelpers/CountdownViewHelper.php, Classes/ViewHelpers/DateRangeViewHelper.php, Classes/ViewHelpers/TimeRangeViewHelper.php, Tests/LegacyUnit/FrontEnd/CountdownTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php, Tests/LegacyUnit/ViewHelpers/CountdownViewHelperTest.php, Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php, Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
=> [TASK] Namespace all view helpers

CHANGELOG.md, Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/DownloadRegistrationListView.php, Classes/Csv/EmailRegistrationListView.php, Classes/Hooks/Interfaces/RegistrationListCsv.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
=> [TASK] Namespace `AbstractRegistrationListView`

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/Hooks/Interfaces/BackEndModule.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
=> [TASK] Namespace all interfaces

CHANGELOG.md, Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php, Classes/Hooks/Interfaces/SeminarListView.php, Classes/Hooks/Interfaces/SeminarRegistrationForm.php, Classes/Hooks/Interfaces/SeminarSingleView.php, Classes/Service/RegistrationManager.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php, Tests/LegacyUnit/OldModel/EventTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, ext_localconf.php, phpstan-baseline.neon
=> [TASK] Namespace the `DefaultController`

CHANGELOG.md, Classes/BackEnd/EventsList.php, Classes/Bag/EventBag.php, Classes/BagBuilder/EventBagBuilder.php, Classes/Csv/EventListView.php, Classes/FrontEnd/CategoryList.php, Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php, Classes/FrontEnd/RequirementsList.php, Classes/FrontEnd/SelectorWidget.php, Classes/Hooks/Interfaces/SeminarListView.php, Classes/Hooks/Interfaces/SeminarSelectorWidget.php, Classes/OldModel/LegacyEvent.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/RegistrationManager.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/BagBuilder/EventBagBuilderTest.php, Tests/LegacyUnit/Bag/EventBagTest.php, Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php, Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, phpstan-baseline.neon
=> [TASK] Namespace the event bag and event bag builder

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/RegistrationsList.php, Classes/Bag/RegistrationBag.php, Classes/BagBuilder/RegistrationBagBuilder.php, Classes/Csv/AbstractRegistrationListView.php, Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationsList.php, Classes/Hooks/Interfaces/BackendRegistrationListView.php, Classes/Hooks/Interfaces/SeminarListView.php, Classes/Service/RegistrationManager.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php, Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
=> [TASK] Namespace the registration bag and bag builder

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/RegistrationsList.php, Classes/Bag/RegistrationBag.php, Classes/Csv/AbstractRegistrationListView.php, Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php, Classes/FrontEnd/RegistrationForm.php, Classes/FrontEnd/RegistrationsList.php, Classes/OldModel/LegacyRegistration.php, Classes/Service/RegistrationManager.php, Tests/Functional/OldModel/LegacyRegistrationTest.php, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php, Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php, Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/Unit/OldModel/LegacyRegistrationTest.php, phpstan-baseline.neon
=> [TASK] Namespace the old registration class

CHANGELOG.md, Classes/BackEnd/OrganizersList.php, Classes/BackEnd/SpeakersList.php, Classes/Bag/CategoryBag.php, Classes/Bag/OrganizerBag.php, Classes/Bag/SpeakerBag.php, Classes/Bag/TimeSlotBag.php, Classes/BagBuilder/Category.php, Classes/BagBuilder/Organizer.php, Classes/BagBuilder/Speaker.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/TimeSlot.php, Tests/Functional/Bag/SpeakerBagTest.php, Tests/LegacyUnit/Bag/AbstractBagTest.php, Tests/LegacyUnit/Bag/CategoryBagTest.php, Tests/LegacyUnit/Bag/OrganizerBagTest.php, Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/Unit/OldModel/LegacyEventTest.php
=> [TASK] Namespace the remaining bag classes

CHANGELOG.md, Classes/BackEnd/OrganizersList.php, Classes/BackEnd/SpeakersList.php, Classes/BagBuilder/CategoryBagBuilder.php, Classes/BagBuilder/OrganizerBagBuilder.php, Classes/BagBuilder/SpeakerBagBuilder.php, Classes/FrontEnd/CategoryList.php, Classes/Hooks/Interfaces/SeminarListView.php, Classes/OldModel/LegacyEvent.php, Documentation/DE/Referenz/Hooks/Index.rst, Documentation/EN/Reference/Hooks/Index.rst, Tests/Functional/BagBuilder/AbstractBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/CategoryBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/OrganizerBagBuilderTest.php, Tests/LegacyUnit/BagBuilder/SpeakerBagBuilderTest.php
=> [TASK] Namespace the remaining bag builder classes

CHANGELOG.md, Classes/FrontEnd/AbstractEditor.php, Classes/FrontEnd/AbstractView.php, Classes/FrontEnd/CategoryList.php, Classes/FrontEnd/Countdown.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/EventHeadline.php, Classes/FrontEnd/RegistrationForm.php, Classes/FrontEnd/RegistrationsList.php, Classes/FrontEnd/RequirementsList.php, Classes/FrontEnd/SelectorWidget.php, Tests/LegacyUnit/Fixtures/FrontEnd/TestingView.php, Tests/LegacyUnit/FrontEnd/AbstractEditorTest.php, Tests/LegacyUnit/FrontEnd/AbstractViewTest.php, Tests/LegacyUnit/FrontEnd/Fixtures/TestingEditor.php, phpstan.neon
Also make the editor superclass abstract and provide a
subclass for testing.
Part of #1020
=> [TASK] Namespace the abstract front-end classes

phpstan-baseline.neon, phpstan.neon
This does not cause crashes anymore.
Fixes #1022
=> [TASK] Include `AbstractEditor` in the PHPStan checks

CHANGELOG.md, Classes/BackEnd/AbstractEventMailForm.php, Classes/BackEnd/RegistrationsList.php, Classes/FrontEnd/RegistrationForm.php, Classes/Mapper/EventMapper.php, Classes/Mapper/FrontEndUser.php, Classes/Mapper/RegistrationMapper.php, Classes/Service/RegistrationManager.php, Tests/Functional/Mapper/RegistrationMapperTest.php, Tests/LegacyUnit/Mapper/RegistrationMapperTest.php, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [TASK] Namespace the registration mapper

phpstan-baseline.neon, phpstan.neon
This reverts commit ecc11e1fc5bedecd289cdd82cbf43f54867d65e7.
=> Revert "[TASK] Include `AbstractEditor` in the PHPStan checks (#1024)"

CHANGELOG.md, Classes/Mapper/BackEndUserGroupMapper.php, Classes/Mapper/BackEndUserMapper.php, Classes/Mapper/Checkbox.php, Classes/Mapper/EventMapper.php, Classes/Mapper/FrontEndUserGroupMapper.php, Classes/Mapper/FrontEndUserMapper.php, Classes/Mapper/Place.php, Classes/Mapper/RegistrationMapper.php, Classes/Mapper/Speaker.php, Classes/Mapper/TargetGroup.php, Classes/Mapper/TimeSlot.php
=> [CLEANUP] Improve the type annotations for the mapper relations

CHANGELOG.md, phpcs.xml.dist
=> [TASK] Enable the sniff for namespaced classes

CHANGELOG.md, Classes/FrontEnd/EventEditor.php, Configuration/TypoScript/Forms/EventEditor.typoscript, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Templates/FrontEnd/EventEditor.html, Tests/Functional/FrontEnd/EventEditorTest.php
=> [TASK] Remove the file upload from the FE editor

CHANGELOG.md, Classes/Model/Event.php, Classes/Service/RegistrationManager.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/DE/Referenz/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Documentation/EN/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, ext_tables.sql
=> [TASK] Drop time zones and use floating dates for iCal

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/OldModel/AbstractTimeSpan.php, Classes/ViewHelpers/DateRangeViewHelper.php, Configuration/TypoScript/PluginShared.typoscript, Documentation/DE/Referenz/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Documentation/EN/Reference/SetupCommonForFront-endPlug-inAndBack-endModuleInPlugintxSeminars/Index.rst, Tests/Functional/OldModel/AbstractTimeSpanTest.php, Tests/LegacyUnit/Email/SalutationTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
=> [TASK] Drop the feature for abbreviated date ranges

Classes/FrontEnd/AbstractView.php, Configuration/FlexForms/flexforms_pi1.xml, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, ext_emconf.php
=> [CLEANUP] Drop any remaining references to the upload folder

Documentation/DE/Installation/Upgrading.rst, Documentation/EN/Installation/Upgrading.rst
=> [TASK] Add upgrade notes

CHANGELOG.md, Classes/Service/RegistrationManager.php
One more step towards getting rid of `TemplateHelper` in
`RegistrationManager`.
Fixes #1127
=> [TASK] Use the Extbase localization in `RegistrationManager`

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/AbstractModel.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/Model/OrganizerTest.php, Tests/LegacyUnit/Model/PlaceTest.php, Tests/LegacyUnit/Model/SpeakerTest.php, Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/LegacyUnit/OldModel/LegacyOrganizerTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [TASK] Use HTTPS for external links by default

CHANGELOG.md, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [TASK] Drop the `TemplateHelper` dependency from `RegistationManager`

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/OldModel/AbstractModel.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacySpeaker.php
=> [TASK] Use the HTML view helper for rendering RTE

CHANGELOG.md, Tests/Functional/Configuration/TypoScriptSetupTest.php, Tests/Functional/Csv/CsvDownloaderTest.php, Tests/Functional/FrontEnd/DefaultControllerTest.php, Tests/Functional/FrontEnd/EventHeadlineTest.php, Tests/Functional/FrontEnd/RegistrationFormTest.php, Tests/Unit/FrontEnd/RegistrationFormTest.php
This fixes a crash in some tests.
Fixes #1133
=> [BUGFIX] Provide fake frontends with a site in TYPO3 10LTS

CHANGELOG.md, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, phpstan-baseline.neon
=> [CLEANUP] Switch the Scheduler task tests to the new email API

Classes/Service/RegistrationManager.php, Documentation/EN/Installation/InstallingTheExtension/Index.rst
=> [CLEANUP] Correct the typo "be send" in comments and in the manual

.github/workflows/release.yml, CHANGELOG.md
=> [TASK] Switch the TER release to Tailor

composer.json, phpstan-baseline.neon
Also re-generate the PHPStan baseline for the latest TYPO3 V10 version.
=> [TASK] Update PHPStan

Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/Functional/BackEnd/ControllerTest.php, Tests/Functional/BackEnd/EventsListTest.php, Tests/Functional/BackEnd/Fixtures/Records.xml, Tests/Functional/BackEnd/Fixtures/TestingEventMailForm.php, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/Functional/FrontEnd/DefaultController/Fixtures/EventList.xml, Tests/Functional/FrontEnd/DefaultController/Fixtures/EventListWithCategories.xml, Tests/Functional/FrontEnd/DefaultController/Fixtures/EventListWithPlaces.xml, Tests/Functional/FrontEnd/DefaultController/Fixtures/EventListWithTypes.xml, Tests/Functional/FrontEnd/DefaultController/ListViewTest.php, Tests/Functional/FrontEnd/DefaultController/PluginDefinitionTest.php, Tests/Functional/FrontEnd/EventEditorTest.php, Tests/Functional/FrontEnd/EventHeadlineTest.php, Tests/Functional/FrontEnd/Fixtures/EventEditorTest.xml, Tests/Functional/FrontEnd/RegistrationFormTest.php, Tests/Functional/SchedulerTasks/Fixtures/MailNotifierConfiguration.xml, Tests/Functional/SchedulerTasks/MailNotifierConfigurationTest.php, phpstan-baseline.neon
Also improve some type annotations in the affected test cases.
=> [TASK] Use real slugs for pages in the functional tests

.github/workflows/ci.yml, CHANGELOG.md
This will help detect problems like those related to lower
Fluid versions.
=> [TASK] Also test with the highest and lowest dependencies in CI

CHANGELOG.md, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, phpstan-baseline.neon
=> [TASK] Convert some tests for `MailNotifier` to the new TF

Tests/Functional/BackEnd/ControllerTest.php, Tests/Functional/FrontEnd/EventHeadlineTest.php, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/Functional/Traits/FalHelper.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, Tests/Unit/FrontEnd/RegistrationFormTest.php, composer.json
Also clean up the Prophecy usage a bit.
=> [TASK] Add the Prophecy PHPStan plugin

rector.php
- add our non-standard autoloader location
- enable parallel processing to massively improve performance
=> [BUGFIX] Improve the Rector configuration

Classes/Service/SingleViewLinkBuilder.php
This class is used in FE context only and does not need to to create
a fake FE in other contexts.
Fixes #1144
=> [TASK] Make the `SingleViewLinkBuilder` FE-only

CHANGELOG.md, Classes/BagBuilder/EventBagBuilder.php, Classes/FrontEnd/SelectorWidget.php
The methods already worked fine (as proven by the new tests),
but the new implementation is cleaner.
=> [TASK] Harden some queries

.github/workflows/codecoverage.yml, CHANGELOG.md, README.md, composer.json
=> [FEATURE] Add a code coverage badge

CHANGELOG.md, Classes/Rendering/NullRenderingContext.php, Tests/Unit/Rendering/NullRenderingContextTest.php
Also improve the type annotations.
=> [TASK] Add more tests for `NullRenderingContext`

CHANGELOG.md, Classes/BackEnd/AbstractList.php, Documentation/DE/Index.rst, Documentation/EN/Index.rst, README.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
This reverts and updates commit
f17c3c3a11b2a0f490a413c6d5daf853b4d6c5c7.
=> [TASK] Advertise the 11LTS crowdfunding campaign

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
=> [BUGFIX] Avoid crash with empty file titles

.github/workflows/ci.yml, .github/workflows/release.yml
=> [TASK] Upgrade the Ubuntu version for the GitHub CI runners

CHANGELOG.md, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
=> [BUGFIX] Fix a flaky legacy test

CHANGELOG.md, Classes/BackEnd/Controller.php
=> [BUGFIX] Only show the configuration check with a logged-in BE admin

CHANGELOG.md, Classes/FrontEnd/Countdown.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/EventHeadline.php, Classes/FrontEnd/EventPublication.php, Classes/FrontEnd/RegistrationForm.php, Classes/Mapper/EventMapper.php, Classes/Mapper/FrontEndUserMapper.php, Classes/Model/Place.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/OldModel/LegacySpeaker.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/Model/PlaceTest.php
Also inline some local variables.
Fixes #1422
=> [CLEANUP] Drop type annotations for `Mapper->find*` calls

CHANGELOG.md, Classes/BackEnd/EventsList.php, Classes/Csv/AbstractRegistrationListView.php, Classes/Csv/EventListView.php, Classes/FrontEnd/RegistrationsList.php, Classes/OldModel/LegacyEvent.php, Classes/SchedulerTasks/MailNotifier.php, Classes/Service/RegistrationManager.php
This allows us to drop some redundant type annotations.
Fixes #1423
=> [CLEANUP] Rely on generics for the bag builders

.gitattributes, CHANGELOG.md, Configuration/FunctionalTests.xml, Configuration/UnitTests.xml, README.md, composer.json
=> [TASK] Run the unit and functional tests with all warnings enabled

CHANGELOG.md, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/Functional/FrontEnd/DefaultController/ListViewTest.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php
=> [BUGFIX] Stop calling the deprecated `disableCoreCaches`

.github/dependabot.yml, composer.json
=> [TASK] Drop PHPUnit 7

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/SelectorWidget.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
=> [BUGFIX] Stop calling the deprecated `ensureIntegerArrayValues`

CHANGELOG.md, Classes/FrontEnd/DefaultController.php, Classes/SchedulerTasks/MailNotifier.php, Tests/LegacyUnit/BackEnd/EventsListTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
=> [BUGFIX] Avoid more usages of removed `LoginManager` methods

Classes/BackEnd/AbstractEventMailForm.php, Classes/Email/Salutation.php, Classes/FrontEnd/DefaultController.php, Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php, Tests/Unit/Hooks/HookProviderTest.php, Tests/Unit/OldModel/LegacyEventTest.php, phpstan-baseline.neon
=> [BUGFIX] Avoid invalid array accesses

Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/Functional/BackEnd/ControllerTest.php, Tests/Functional/BackEnd/EventsListTest.php, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/Functional/FrontEnd/EventEditorTest.php, Tests/Functional/FrontEnd/RegistrationFormTest.php, Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php, Tests/LegacyUnit/BackEnd/AbstractModuleTest.php, Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php, Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php, Tests/LegacyUnit/BackEnd/EventsListTest.php, Tests/LegacyUnit/BackEnd/FlexFormsTest.php, Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php, Tests/LegacyUnit/BackEnd/OrganizersListTest.php, Tests/LegacyUnit/BackEnd/RegistrationsListTest.php, Tests/LegacyUnit/BackEnd/SpeakersListTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php, phpstan-baseline.neon
This code will not see the 11LTS-compatible release.
Fixes #1512
=> [TASK] Disable tests in 11LTS for code that will be removed soon

CHANGELOG.md, ext_tables.php
=> [TASK] Disable the legacy BE module in TYPO3 11LTS

CHANGELOG.md, Classes/SchedulerTasks/MailNotifier.php
=> [BUGFIX] Fix type warnings for `str_replace` in the `MailNotifier`

CHANGELOG.md, Tests/Functional/FrontEnd/CategoryListTest.php, Tests/Functional/FrontEnd/DefaultController/ListViewTest.php, Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php
This prevents errors in the functional tests in TYPO3 11LTS.
=> [BUGFIX] Provide a proper fake FE in the functional tests

CHANGELOG.md, Configuration/Services.yaml
=> [FEATURE] Add a services configuration file

.github/workflows/ci.yml, CHANGELOG.md, composer.json
Also add more script descriptions.
=> [TASK] Rename some Composer scripts

.github/dependabot.yml, .github/workflows/ci.yml, CHANGELOG.md, composer.json
Also normalize the `composer.json`.
Fixes #1551
=> [FEATURE] Add `composer normalize` to the CI toolchain

composer.json
=> [TASK] Also TypoScript-lint `ext_typoscript_setup.txt`

CHANGELOG.md, Classes/Domain/Model/Event.php, Classes/Domain/Model/EventDate.php, Classes/Domain/Model/EventInterface.php, Classes/Domain/Model/EventTopic.php, Classes/Domain/Model/SingleEvent.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Fixtures/EventRepository/EventDateAndTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Fixtures/EventRepository/EventTopicWithAllFields.xml, Tests/Unit/Domain/Model/EventDateTest.php, Tests/Unit/Domain/Model/EventTopicTest.php, Tests/Unit/Domain/Model/SingleEventTest.php, ext_typoscript_setup.txt
Now we have the `SingleEvent`, `EventTopic` and `EventDate` domain model classes.
=> [FEATURE] Implement STI for events

composer.json
=> [BUGFIX] Omit unnecessary PHP-CS-Fixer config file reference

CHANGELOG.md, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
=> [FEATURE] Add tests for persisting STI event records

Configuration/TCA/tx_seminars_seminars.php
=> [CLEANUP] Use the `EventInterface` constants in the TCA

Classes/BackEnd/EventsList.php, Classes/BagBuilder/EventBagBuilder.php, Classes/FrontEnd/DefaultController.php, Classes/Mapper/EventMapper.php, Classes/OldModel/LegacyEvent.php
=> [CLEANUP] Use the `EventInterface::TYPE_*` constants in `Classes/`

CHANGELOG.md, Classes/Domain/Model/Event/EventDate.php, Classes/Domain/Model/Event/EventInterface.php, Classes/Domain/Model/Event/EventTopic.php, Classes/Domain/Model/Event/EventTopicTrait.php, Classes/Domain/Model/Event/EventTrait.php, Classes/Domain/Model/Event/SingleEvent.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateAndTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php
- `displayTitle`
- `description`
=> [FEATURE] Add more text fields to the `Event` models

Classes/Domain/Model/Event/EventDate.php, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Classes/Domain/Model/Event/SingleEvent.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateAndTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateAndTopicWithoutData.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithoutData.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_typoscript_setup.txt
- `start`
- `end`
- `earlyBirdDeadline`
- `registrationDeadline`
=> [FEATURE] Add some `Event` date fields

Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateAndTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_typoscript_setup.txt
- `requiresRegistration`
- `hasWaitingList`
- `minimumNumberOfRegistrations`
- `maximumNumberOfRegistrations`
=> [FEATURE] Add more `Event` fields

CHANGELOG.md, Classes/Domain/Model/Event/EventTopic.php, Classes/Domain/Model/Event/EventTopicInterface.php, Classes/Domain/Model/Event/EventTopicTrait.php, Classes/Domain/Model/Event/SingleEvent.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventTopicWithAllFields.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithAllFields.xml, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_typoscript_setup.txt
- `standardPrice`
- `earlyBirdPrice`
=> [FEATURE] Add price fields to `Event`

composer.json
This avoids unwanted updates on CI.
=> [BUGFIX] Pin `saschaegerer/phpstan-typo3`

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithOrganizer.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithSpeaker.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithVenue.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithOrganizer.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithSpeaker.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithVenue.xml, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, ext_typoscript_setup.txt
- `venues`
- `speakers`
- `organizers` and `getFirstOrganizer`/`getOrganizer`
Closes #1579
=> [FEATURE] Add more `Event` associations

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithOwner.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventTopicWithOwner.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithOwner.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithOwnerOnPage.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithoutOwner.xml, Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/TwoSingleEventsWithOwner.xml, ext_typoscript_setup.txt, phpstan-baseline.neon
=> [FEATURE] Add `EventRepository::findSingleEventsByOwnerUid`

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Configuration/TCA/Overrides/tt_content.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Layouts/Default.html, Resources/Private/Templates/FrontEndEditor/Index.html, Tests/Unit/Controller/FrontEndEditorControllerTest.php, ext_localconf.php, phpstan-baseline.neon
Note: This is 10LTS-only.
Part of #1513
=> [FEATURE] Add an event list for the FE editor

Classes/Domain/Model/Event/EventTrait.php
=> [TASK] Make the event title required

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/FrontEndEditor/Index.html
=> [FEATURE] Add more columns to the FE editor event list

CHANGELOG.md, Classes/Domain/Repository/EventTypeRepository.php, Classes/Domain/Repository/OrganizerRepository.php, Classes/Domain/Repository/SpeakerRepository.php, Classes/Domain/Repository/VenueRepository.php, Tests/Functional/Domain/Repository/EventTypeRepositoryTest.php, Tests/Functional/Domain/Repository/Fixtures/EventTypeRepository/EventTypeOnPage.xml, Tests/Functional/Domain/Repository/Fixtures/OrganizerRepository/OrganizerOnPage.xml, Tests/Functional/Domain/Repository/Fixtures/SpeakerRepository/SpeakerOnPage.xml, Tests/Functional/Domain/Repository/Fixtures/VenueRepository/VenueOnPage.xml, Tests/Functional/Domain/Repository/OrganizerRepositoryTest.php, Tests/Functional/Domain/Repository/SpeakerRepositoryTest.php, Tests/Functional/Domain/Repository/VenueRepositoryTest.php
=> [TASK] Find auxiliary records on all pages

CHANGELOG.md, Resources/Private/Templates/FrontEndEditor/Index.html
=> [TASK] Make the FE editor index HTML template autoformattable

Resources/Private/Layouts/Default.html, Resources/Private/Layouts/FrontEndEditor.html, Resources/Private/Templates/FrontEndEditor/Index.html
=> [CLEANUP] Move the FE Editor auth check to a Fluid layout

Resources/Private/Templates/FrontEndEditor/Index.html
=> [CLEANUP] Streamline the date variables in the FE editor list

Resources/Private/Templates/FrontEndEditor/Index.html
=> [BUGFIX] Do not duplicate the FE editor table heading for each event

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Private/Templates/FrontEndEditor/Edit.html, Resources/Private/Templates/FrontEndEditor/Index.html, Resources/Public/CSS/FrontEnd/FrontEnd.css, Tests/Unit/Controller/FrontEndEditorControllerTest.php, ext_localconf.php
=> [FEATURE] Add an FE edit form with text fields

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [FEATURE] Add an owner check to the FE editor edit/update actions

Classes/Domain/Model/EventType.php, Classes/Domain/Model/EventTypeInterface.php, Classes/Domain/Model/NullEventType.php, Classes/Domain/Repository/EventTypeRepository.php, Tests/Unit/Domain/Model/EventTypeTest.php, Tests/Unit/Domain/Model/NullEventTypeTest.php
=> [CLEANUP] Introduce `EventTypeInterface`

CHANGELOG.md, Classes/Controller/FrontEndEditorController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Private/Templates/FrontEndEditor/Edit.html, Tests/Unit/Controller/Fixtures/TestingQueryResult.php, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [FEATURE] Add associations to the FE editor

Resources/Private/Partials/FrontEndEditor/Form.html
=> [TASK] Add spacing between sections in the FE editor

Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Private/Partials/FrontEndEditor/ValidationResult.html
=> [FEATURE] Add validation error messages to the FE editor

CHANGELOG.md, Configuration/FlexForms/FrontEndEditor.xml, Configuration/TCA/Overrides/tt_content.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> [FEATURE] Add FlexForms for the FE editor plugin

Classes/Controller/FrontEndEditorController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/FrontEndEditor/Index.html, Resources/Private/Templates/FrontEndEditor/New.html, Tests/Unit/Controller/FrontEndEditorControllerTest.php, ext_localconf.php
=> [FEATURE] Add form for creating new events in the FE

CHANGELOG.md, Documentation/DE/Konfiguration/SettingUpFront-endEditing/Index.rst, Documentation/EN/Configuration/SettingUpFront-endEditing/Index.rst
[ci skip]
Fixes #1419
Closes #1513
=> [TASK] Document the FE editor and deprecate the old one

CHANGELOG.md, Documentation/DE/Konfiguration/SettingUpFront-endEditing/Index.rst, Documentation/EN/Configuration/SettingUpFront-endEditing/Index.rst
=> [TASK] Document that the new FE editor is only for 10LTS and higher

CHANGELOG.md, Resources/Private/Partials/FrontEndEditor/Form.html
=> [BUGFIX] Allow saving events without event type in the FE editor

CHANGELOG.md, Classes/BackEnd/AbstractList.php, Documentation/Index.rst, README.md
=> [TASK] Add links to the feature survey in a few places

CHANGELOG.md, Classes/Domain/Model/AccommodationOption.php, Classes/Domain/Repository/AccommodationOptionRepository.php, Configuration/Extbase/Persistence/Classes.php, Tests/Functional/Domain/Repository/AccommodationOptionRepositoryTest.php, Tests/Functional/Domain/Repository/Fixtures/AccommodationOptionRepository/AccommodationOptionWithAllFields.xml, Tests/Unit/Domain/Model/AccommodationOptionTest.php, ext_typoscript_setup.txt, phpstan-baseline.neon
=> [FEATURE] Add an `AccommodationOption` model

Resources/Private/Partials/EventDate.html, Resources/Private/Templates/FrontEndEditor/Index.html
=> [CLEANUP] Move the date span rendering into a partial

CHANGELOG.md, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, Tests/Unit/Domain/Repository/Event/EventRepositoryTest.php, Tests/Unit/Domain/Repository/EventTypeRepositoryTest.php, Tests/Unit/Domain/Repository/OrganizerRepositoryTest.php, Tests/Unit/Domain/Repository/SpeakerRepositoryTest.php, Tests/Unit/Domain/Repository/VenueRepositoryTest.php
=> [CLEANUP] Stop using Prophecy for `ObjectManager(Interface)`

CHANGELOG.md, Tests/Unit/Controller/FrontEndEditorControllerTest.php
=> [CLEANUP] Stop using Prophecy in `FrontEndEditorControllerTest`

Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
A mock should only represent one object, not two.
=> [BUGFIX] Do not reuse mocks in tests

CHANGELOG.md, Tests/Functional/BackEnd/ControllerTest.php, Tests/Functional/FrontEnd/EventHeadlineTest.php, Tests/Functional/SchedulerTasks/MailNotifierTest.php, Tests/Functional/Traits/FalHelper.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, phpstan-baseline.neon
=> [CLEANUP] Drop more Prophecy usages

Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
=> [CLEANUP] Drop the remaining Prophecy usages

CHANGELOG.md, Classes/Model/Registration.php, Tests/LegacyUnit/Model/RegistrationTest.php
=> [BUGFIX] Fix a typo in a `Registration` model setter

Classes/BagBuilder/EventBagBuilder.php, Classes/Mapper/EventMapper.php, Classes/OldModel/LegacyEvent.php, Classes/SchedulerTasks/MailNotifier.php, Configuration/TCA/tx_seminars_seminars.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/LegacyUnit/BackEnd/EventsListTest.php, Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php, Tests/LegacyUnit/FrontEnd/CategoryListTest.php, Tests/LegacyUnit/Mapper/EventMapperTest.php, Tests/LegacyUnit/Model/EventTest.php, Tests/LegacyUnit/OldModel/LegacyEventTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/Service/EventStatusServiceTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php
=> [CLEANUP] Use the new event status constants in more places

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Classes/Service/PriceFinder.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, Tests/Unit/Service/PriceFinderTest.php
=> [TASK] Switch the new models from `DateTime` to `DateTimeImmutable`

CHANGELOG.md, Classes/Configuration/SingleViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
=> [TASK] Deprecate showing the owner data in the single view

CHANGELOG.md, Classes/Csv/CsvDownloader.php, Classes/Localization/TranslateTrait.php, Classes/OldModel/AbstractModel.php, Resources/Private/Language/locallang.xlf, Tests/Functional/Localization/TranslateTraitTest.php, phpstan-baseline.neon
=> [FEATURE] Add and use a `Translate` trait

CHANGELOG.md, Classes/ViewHelpers/SalutationAwareTranslateViewHelper.php, Resources/Private/Language/locallang.xlf, Tests/Functional/ViewHelpers/Fixtures/BackEndUser.xml, Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php, Tests/Unit/ViewHelpers/SalutationAwareTranslateViewHelperTest.php, phpstan-baseline.neon
=> [FEATURE] Add a `SalutationAwareTranslateViewHelper`

CHANGELOG.md, Classes/Configuration/SharedConfigurationCheck.php, Classes/Model/Event.php, Classes/OldModel/LegacyEvent.php, Classes/Service/RegistrationManager.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TypoScript/PluginShared.typoscript, ext_tables.sql
=> [TASK] Deprecate the collision check for registrations

CHANGELOG.md, Classes/Domain/Model/Registration/BillingAddressTrait.php, Configuration/TCA/tx_seminars_attendances.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAllFields.xml, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Unit/Domain/Model/Registration/RegistrationTest.php, ext_tables.sql
=> [FEATURE] Add `Registration.hasSeparateBillingAddress`

CHANGELOG.md, Documentation/DE/Konfiguration/SettingUpFront-endEditing/Index.rst, Documentation/EN/Configuration/SettingUpFront-endEditing/Index.rst
=> [BUGFIX] Fix renderings warnings in the documentation

CHANGELOG.md, Classes/Configuration/RegistrationFormConfigurationCheck.php, Classes/FrontEnd/RegistrationForm.php, Classes/Model/Registration.php, Classes/OldModel/LegacyRegistration.php, Classes/Service/RegistrationManager.php, Configuration/TCA/tx_seminars_attendances.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, ext_tables.sql
=> [TASK] Deprecate all bank-data-related fields

CHANGELOG.md, Classes/BagBuilder/EventBagBuilder.php, Classes/Configuration/CsvExportConfigurationCheck.php, Classes/Configuration/EventEditorConfigurationCheck.php, Classes/Configuration/SingleViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/Model/Event.php, Classes/OldModel/LegacyEvent.php, Classes/Service/RegistrationManager.php, Configuration/TCA/tx_seminars_seminars.php, ext_tables.sql
=> [TASK] Deprecate the board-related prices

CHANGELOG.md, Classes/Domain/Model/Registration/AttendeesTrait.php, Tests/Unit/Domain/Model/Registration/RegistrationTest.php
=> [TASK] Change `Registration` to have 1 seat by default

CHANGELOG.md, Classes/Email/Salutation.php
=> [TASK] Deprecate the automatic gender-specific salutations

CHANGELOG.md, Classes/FrontEnd/AbstractEditor.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/RegistrationForm.php, Configuration/TypoScript/Forms/EventEditor.typoscript, Configuration/TypoScript/Forms/RegistrationStep1.typoscript, Configuration/TypoScript/Forms/RegistrationStep2.typoscript, Configuration/TypoScript/Forms/Unregistration.typoscript
=> [TASK] Deprecate the legacy registration form

CHANGELOG.md, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/EventPublication.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
=> [TASK] Deprecate the FE editor approval workflow

Classes/Domain/Model/Event/Event.php, Classes/Domain/Model/Event/EventDate.php, Classes/Domain/Model/Event/EventInterface.php, Classes/Domain/Model/Event/EventTopic.php, Classes/Domain/Model/Event/SingleEvent.php, Classes/Service/RegistrationGuard.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, phpstan-baseline.neon
It has turned out that using this method gets in the way of static analysis.
=> [TASK] Remove `Event.isRegistrationPossibleForThisClass()`

Classes/BagBuilder/EventBagBuilder.php, Classes/Configuration/CsvExportConfigurationCheck.php, Classes/Configuration/EventEditorConfigurationCheck.php, Classes/Configuration/RegistrationFormConfigurationCheck.php, Classes/Configuration/SharedConfigurationCheck.php, Classes/Configuration/SingleViewConfigurationCheck.php, Classes/Email/Salutation.php, Classes/FrontEnd/AbstractEditor.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Classes/FrontEnd/EventPublication.php, Classes/FrontEnd/RegistrationForm.php, Classes/Model/Event.php, Classes/Model/Registration.php, Classes/OldModel/LegacyEvent.php, Classes/OldModel/LegacyRegistration.php, Classes/Service/RegistrationManager.php, Configuration/TCA/tx_seminars_attendances.php, Configuration/TCA/tx_seminars_seminars.php, Configuration/TypoScript/Forms/EventEditor.typoscript, Configuration/TypoScript/Forms/RegistrationStep1.typoscript, Configuration/TypoScript/Forms/RegistrationStep2.typoscript, Configuration/TypoScript/Forms/Unregistration.typoscript, Configuration/TypoScript/FrontEnd.typoscript, Configuration/TypoScript/PluginShared.typoscript, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, ext_tables.sql
This will make finding the code to remove for a ticket less of a hassle.
Fixes #1850
[ci skip]
=> [TASK] Add the issue number of removal ticket to `@deprecated` notices

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
=> [TASK] Deprecate hiding events in the FE editor

CHANGELOG.md, Classes/Configuration/MyVipEventsConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventEditor.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/DE/Konfiguration/DieFront-endBearbeitungFrVerwalterEinrichten/Index.rst, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Configuration/SettingUpFront-endEditingForManagers/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
=> [TASK] Deprecate FE editing for managers

CHANGELOG.md, Classes/Service/RegistrationManager.php, ext_conf_template.txt
=> [TASK] Deprecate the FE user email format settings

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Partials/EventRegistration/Headline.html, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Private/Templates/EventRegistration/ThankYou.html
=> [FEATURE] Polish the heading on the registration page

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
=> [FEATURE] Add buttons to the registration form

CHANGELOG.md, Classes/Mapper/EventMapper.php, Classes/Model/Event.php, Configuration/TCA/tx_seminars_seminars.php, ext_tables.sql
=> [TASK] Deprecate seeing registrations within an event in the TCEforms

CHANGELOG.md, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
=> [FEATURE] Add a back button to the registration form

CHANGELOG.md, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> [FEATURE] Add a configuration for the registration storage folder

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/ThankYou.html
=> [FEATURE] Add a thank-you message to the registration page

CHANGELOG.md, Classes/Configuration/ListViewConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Configuration/FlexForms/flexforms_pi1.xml, Configuration/TypoScript/FrontEnd.typoscript, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
=> [TASK] Deprecate the `omitDateIfSameAsPrevious` setting

Classes/Service/RegistrationManager.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/Unit/Service/RegistrationManagerTest.php
=> [FEATURE] Add some bridge code to `RegistrationManager`

CHANGELOG.md, Configuration/TCA/tx_seminars_seminars.php
=> [TASK] Deprecate using single events as topics for event dates

CHANGELOG.md, Classes/Model/Event.php
=> [TASK] Deprecate the `Event::STATUS_*` constants

Classes/OldModel/LegacyEvent.php
=> [TASK] Add missing deprecation markers

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
=> [TASK] Polish the thank-you message in the registration form

CHANGELOG.md, Configuration/TypoScript/View.typoscript, Configuration/TypoScript/setup.typoscript
=> [FEATURE] Add TypoScript settings for the Fluid templates

CHANGELOG.md, Classes/ViewHelpers/CommaSeparatedTitlesViewHelper.php
=> [TASK] Deprecate the `CommaSeparatedTitlesViewHelper`

Tests/Unit/Service/RegistrationManagerTest.php
=> [BUGFIX] Fix a typo in a test name

CHANGELOG.md, Classes/FrontEnd/Countdown.php, Classes/Mapper/EventMapper.php, Classes/ViewHelpers/CountdownViewHelper.php
=> [TASK] Deprecate the event countdown

CHANGELOG.md, Classes/Service/RegistrationGuard.php, Tests/Unit/Service/RegistrationGuardTest.php
=> [BUGFIX] Refuse registration if an event date has lost its topic

CHANGELOG.md, Classes/BagBuilder/EventBagBuilder.php, Classes/Service/RegistrationManager.php
=> [TASK] Deprecate the requirements check

Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Private/Templates/EventRegistration/ThankYou.html
=> [CLEANUP] Drop the debugging alerts in the registration templates

CHANGELOG.md, Classes/FrontEnd/DefaultController.php
=> [TASK] Deprecate the "duplicate event" functionality in the FE editor

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Classes/Service/RegistrationProcessor.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithDeletedRegistrationWithZeroCounterCache.xml, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithHiddenRegistrationWithZeroCounterCache.xml, Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithTwoRegistrationsWithZeroCounterCache.xml, Tests/Unit/Service/RegistrationProcessorTest.php
=> [FEATURE] Update the `Event.registrations` counter cache

CHANGELOG.md, Classes/Configuration/AbstractFrontEndConfigurationCheck.php, Classes/FrontEnd/DefaultController.php, Classes/FrontEnd/EventHeadline.php
=> [TASK] Deprecate the event headline view

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
- interests
- expectations
- background knowledge
- known from
[ci skip]
=> [FEATURE] Add more text fields to the registration form

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Templates/EventRegistration/New.html
=> [FEATURE] Add fieldsets to the registration form

CHANGELOG.md, Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Public/CSS/FrontEnd/FrontEnd.css
=> [TASK] Streamline the HTML and CSS for the FE editor

CHANGELOG.md, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
=> [TASK] Stop using inputs on the registration confirmation page

Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [CLEANUP] Autoformat the JavaScript file

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
=> [FEATURE] Add a "register myself" checkbox to the registration form

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Tests/Unit/Controller/EventRegistrationControllerTest.php
=> [FEATURE] Make the default value of `registeredThemselves` configurable

CHANGELOG.md, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
This improves usability.
Also autoformat that locallang files.
Fixes #1955
[ci skip]
=> [FEATURE] Add tabs to the registration form flexforms

Resources/Private/Templates/EventRegistration/Confirm.html
=> [CLEANUP] Drop unnecessary `f:then` from a template

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Public/CSS/FrontEnd/FrontEnd.css, Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Also drop unnecessary `f:then`.
=> [FEATURE] Add the billing address fields to the registration form

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [FEATURE] Add the attendees names to the registration form

Resources/Private/Templates/EventRegistration/Confirm.html
=> [BUGFIX] Hide labels for empty multiselects on the confirmation page

Resources/Private/Templates/EventRegistration/Confirm.html
=> [TASK] Render newlines from textareas on the confirmation page

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html
=> [FEATURE] Add the payment method to the registration form

CHANGELOG.md, Classes/Configuration/RegistrationFormConfigurationCheck.php, Classes/FrontEnd/RegistrationForm.php, Configuration/TypoScript/FrontEnd.typoscript, Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst, Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
=> [TASK] Deprecate the `logOutOneTimeAccountsAfterRegistration` setting

Classes/Service/RegistrationGuard.php
Also make it internal.
[ci skip]
=> [TASK] Deprecate `RegistrationGuard::assertBookableEventType`

CHANGELOG.md, Classes/Domain/Model/Registration/AttendeesTrait.php
=> [FEATURE] Validate `Registration.seats` to be >= 1

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf, Resources/Private/Partials/EventRegistration/EventTitleAndDateAndUid.html, Resources/Private/Partials/EventRegistration/Headline.html, Resources/Private/Templates/EventRegistration/Confirm.html
Also mention that the total price includes VAT.
Closes #1704
[ci skip]
=> [FEATURE] Add a registration summary to the confirmation page

CHANGELOG.md, Resources/Private/Partials/FrontEndEditor/Form.html, Resources/Private/Templates/EventRegistration/New.html
=> [TASK] Add `maxlength` to the `textareas` in the FE forms

CHANGELOG.md, Classes/Domain/Model/Registration/Registration.php, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Tests/Unit/Domain/Model/Registration/RegistrationTest.php
There is not validation yet, though.
=> [FEATURE] Add two terms & conditions checkboxes to the registration form

CHANGELOG.md, Classes/Domain/Model/Price.php
=> [CLEANUP] Make all `Price` properties transient

composer.json
=> [TASK] Enable caching for PHP-CS-Fixer

CHANGELOG.md, Classes/Mapper/RegistrationMapper.php, Configuration/TCA/tx_seminars_attendances.php, ext_tables.sql
=> [TASK] Deprecate `Registration.currency` and `Registration.includingTax`

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html
=> [FEATURE] Show the FE user data on the registration confirmation page

CHANGELOG.md, Classes/Configuration/EventRegistrationFlexForms.php, Classes/Domain/Model/Registration/PaymentTrait.php, Classes/Service/RegistrationProcessor.php, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Public/JavaScript/FrontEnd/FrontEnd.js, Tests/Unit/Configuration/EventRegistrationFlexFormsTest.php, Tests/Unit/Domain/Model/Registration/RegistrationTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
=> [FEATURE] Make the registration form fields configurable

Resources/Private/Templates/EventRegistration/New.html, Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [BUGFIX] Also use the configured "registered themselves" value if hidden

CHANGELOG.md, Classes/Domain/Repository/Registration/RegistrationRepository.php, Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedRegistrationWithEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenRegistrationWithEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithEventAndAdditionalEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/TwoMultiSeatRegistrationsWithSameEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/WaitingListRegistrationWithEvent.xml, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
=> [FEATURE] Add `RegistrationRepository::countSeatsByEvent`

CHANGELOG.md, Classes/Service/RegistrationGuard.php, Tests/Unit/Service/RegistrationGuardTest.php
=> [FEATURE] Add `RegistrationGuard.getVacancies()`

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf
=> [BUGFIX] Fix a typo in a label

Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [CLEANUP] Refactor the FronEnd.js and create a Seminars class

CHANGELOG.md, Resources/Public/JavaScript/FrontEnd/FrontEnd.js
=> [CLEANUP] Autoformat the JavaScript

CHANGELOG.md, Classes/Domain/Model/Registration/AttendeesTrait.php, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/EventRegistration/Confirm.html, Resources/Private/Templates/EventRegistration/New.html, Resources/Public/JavaScript/FrontEnd/FrontEnd.js, Tests/Unit/Domain/Model/Registration/RegistrationTest.php
=> [FEATURE] Provide separate inputs for each additional attendee

CHANGELOG.md, Classes/Controller/EventRegistrationController.php, Classes/Domain/Model/Registration/AttendeesTrait.php, Classes/Service/RegistrationProcessor.php, Configuration/FlexForms/EventRegistration.xml, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Tests/Unit/Controller/EventRegistrationControllerTest.php, Tests/Unit/Domain/Model/Registration/RegistrationTest.php, Tests/Unit/Service/RegistrationProcessorTest.php
=> [FEATURE] Allow saving additional registered persons as FE users

Documentation/EN/Installation/AddingPagesToTheFrontEnd/Index.rst, Documentation/EN/Installation/Upgrading.rst
=> [TASK] Write upgrade notes

Documentation/EN/Installation/Upgrading.rst
=> [TASK] Document the onetimeaccount type in the upgrade notes

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Resources/Private/Layouts/BackEndModule.html, Resources/Private/Templates/BackEnd/Event/Index.html, Tests/Unit/Controller/BackEnd/EventControllerTest.php, ext_tables.php
=> [FEATURE] Register the new BE module and add empty template files

CHANGELOG.md, Resources/Private/Layouts/BackEndModule.html
=> [FEATURE] Display flash messages in the new BE module

Resources/Private/Templates/FrontEndEditor/Index.html
=> [FEATURE] Make the event list for the FE editor striped

Resources/Private/Layouts/BackEndModule.html, Resources/Private/Templates/BackEnd/Event/Index.html
=> [CLEANUP] Move the BE module debug information to the layout

Resources/Private/Templates/BackEnd/Event/Index.html
=> [TASK] Hide the BE module events list if the user has no permissions

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/FlashMessage.html, Resources/Private/Templates/BackEnd/Event/Index.html
=> [FEATURE] Show a flash message in the BE if no page is selected

CHANGELOG.md, Resources/Private/Partials/EventDate.html, Resources/Private/Partials/FrontEndEditor/Form.html
=> [CLEANUP] Avoid unnecessary inline notation in the Fluid templates

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Templates/BackEnd/Event/Index.html
=> [FEATURE] Add event edit links to the BE module

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Classes/Domain/Repository/Event/EventRepository.php, Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, phpstan-baseline.neon
=> [TASK] Also show event topics in the BE module

CHANGELOG.md, Classes/Domain/Model/Event/EventDateInterface.php, Classes/Domain/Model/Event/EventDateTrait.php, Classes/Domain/Model/Event/EventInterface.php, Classes/Domain/Model/Event/EventStatistics.php, Classes/Domain/Model/Event/EventTopic.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Classes/Service/EventStatisticsCalculator.php, Classes/Service/RegistrationGuard.php, Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedWaitingListRegistrationWithEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenWaitingListRegistrationWithEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/TwoMultiSeatWaitingListRegistrationsWithSameEvent.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/TwoWaitingListRegistrationsWithSameEventAndUser.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/WaitingListRegistrationWithZeroSeats.xml, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Unit/Domain/Model/Event/EventDateTest.php, Tests/Unit/Domain/Model/Event/EventStatisticsTest.php, Tests/Unit/Domain/Model/Event/EventTopicTest.php, Tests/Unit/Domain/Model/Event/SingleEventTest.php, Tests/Unit/Service/EventStatisticsCalculatorTest.php, Tests/Unit/Service/RegistrationGuardTest.php
Also add and rename the necessary `RegistrationRepository` methods.
=> [FEATURE] Add `EventsStatisticsCalculator` and `Event/Statistics`

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/dk.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/it.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/nl.locallang.xlf, Resources/Private/Language/ru.locallang.xlf
=> [CLEANUP] Drop some space preservation from the locallang files

CHANGELOG.md, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/BackEnd/EventList.html
=> [FEATURE] Add icons for the event status to the BE module

CHANGELOG.md, Classes/Controller/BackEnd/EventController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, phpstan-baseline.neon
=> [BUGFIX] Fix the CSV download in the new BE module in TYPO3 11LTS

CHANGELOG.md, Classes/Controller/BackEnd/AbstractController.php, Classes/Controller/BackEnd/EventController.php, Classes/Controller/BackEnd/RegistrationController.php, Tests/Unit/Controller/BackEnd/EventControllerTest.php, Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php, phpstan-baseline.neon
Also add a shared abstraction for the BE module controllers to avoid code duplication.
=> [FEATURE] Add a `RegistrationController` for the BE module

CHANGELOG.md, Classes/Domain/Repository/Event/EventRepository.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenWaitingListRegistrationWithEventAndUser.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithEventAndUserOnPage.xml, Tests/Functional/Domain/Repository/Registration/Fixtures/WaitingListRegistrationWithEventAndUserOnPage.xml, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, phpstan-baseline.neon
- `findRegularRegistrationsByEvent`
- `findWaitingListRegistrationsByEvent`
Also polish the `EventRepository` a bit to keep things consistent.
=> [FEATURE] Add `RegistrationRepository` methods for the BE module

Classes/Domain/Model/Registration/Registration.php, Classes/Domain/Repository/Registration/RegistrationRepository.php, Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php, Tests/Unit/Domain/Model/Registration/RegistrationTest.php, Tests/Unit/Domain/Repository/Registration/RegistrationRepositoryTest.php
This is required for displaying registration icons in the backend.
=> [FEATURE] Make the `Repository` raw-data-capable

CHANGELOG.md, Resources/Private/Partials/BackEnd/RegistrationList.html, Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
=> [FEATURE] Add edit icons/links for registrations in the BE module

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html, Resources/Private/Partials/BackEnd/RegistrationList.html
This aligns the UI of the BE module more with the Web > List module.
Fixes #2136
[ci skip]
=> [FEATURE] Add button stubs to the BE module

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html
=> [TASK] Move the buttons in the BE events list further to the left

Classes/Domain/Repository/AbstractRawDataCapableRepository.php
=> [CLEANUP] Rename a variable in a repository method

CHANGELOG.md, Resources/Private/Partials/BackEnd/EventList.html
=> [TASK] Style the "list registrations" link as a button with an icon

Resources/Private/Layouts/BackEndModule.html
=> [TASK] Remove the debug output from the BE module

.github/workflows/ci.yml, .github/workflows/codecoverage.yml
=> [TASK] Use Composer V2 for the legacy tests on CI

CHANGELOG.md, Classes/Email/EmailBuilder.php, Tests/Functional/BackEnd/AbstractEventMailFormTest.php, Tests/Functional/BackEnd/CancelEventMailFormTest.php, Tests/Functional/BackEnd/ConfirmEventMailFormTest.php, Tests/Functional/BackEnd/GeneralEventMailFormTest.php, Tests/Functional/Service/RegistrationManagerTest.php, Tests/LegacyUnit/FrontEnd/EventEditorTest.php, Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php, Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php, Tests/LegacyUnit/Service/EmailServiceTest.php, Tests/LegacyUnit/Service/RegistrationManagerTest.php, Tests/Unit/Email/EmailBuilderTest.php, Tests/Unit/Traits/EmailTrait.php, Tests/Unit/Traits/EmailTraitTest.php, composer.json
=> [TASK] Drop the SwiftMailer dependency

Classes/Bag/AbstractBag.php, Classes/BagBuilder/AbstractBagBuilder.php
=> [BUGFIX] Use the Core `PageRepository`
